import {test,expect,login,api,evidence} from './fixture.mjs';
import {verifyNotificationPolling} from './announcement-polling.mjs';
import {auditNotificationUI,verifyInboxRecovery} from './notification-ux.mjs';

test('composer validation, empty audience, long content and list recovery',async({page},testInfo)=>{
  await login(page);
  await page.route('**/v2/announcements?*',route=>route.fulfill({status:503,json:{message:'UNAVAILABLE'}}));
  await page.goto('/announcements');
  await expect(page.getByText('Daftar pengumuman gagal dimuat.',{exact:true})).toBeVisible();
  await page.unroute('**/v2/announcements?*');
  await page.getByRole('button',{name:'Coba lagi',exact:true}).click();
  await expect(page.getByText('Belum ada pengumuman',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Buat pengumuman'}).click();
  const editor=page.getByRole('dialog',{name:'Tulis pengumuman',exact:true});
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await expect(editor.getByLabel('Judul',{exact:true})).toBeFocused();
  await editor.getByLabel('Judul',{exact:true}).fill('P'.repeat(160));
  await editor.getByLabel('Pesan',{exact:true}).fill('Informasi kegiatan untuk penerima terpilih.');
  await editor.getByRole('button',{name:'Tambahkan tautan (opsional)',exact:true}).click();
  await editor.getByLabel('Teks tombol',{exact:true}).fill('T'.repeat(100));
  await editor.getByLabel('Tautan HTTPS',{exact:true}).fill('http://example.com');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await expect(editor.getByText('Gunakan URL HTTPS yang lengkap.',{exact:true})).toBeVisible();
  await editor.getByLabel('Tautan HTTPS',{exact:true}).fill('https://example.com');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  const preview=page.getByRole('dialog',{name:'Pratinjau pengumuman',exact:true});
  await expect(preview.getByRole('button',{name:'Kirim sekarang'})).toBeDisabled();
  await expect(preview).toContainText('Belum ada penerima yang memenuhi syarat.');
  expect(await preview.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);
  await evidence(page,testInfo,'long-announcement-preview');
  await preview.getByRole('button',{name:'Ubah penerima'}).click();
  await editor.getByRole('checkbox',{name:'Admin',exact:true}).check();
  await editor.getByLabel('Semua admin aktif').check();
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  await expect(preview).toContainText('2 penerima');
  await preview.getByRole('button',{name:'Kirim sekarang'}).click();
  const published=page.getByRole('dialog',{name:'Pengumuman',exact:true});
  await expect(published).toContainText('2 penerima');
  expect(await published.evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);
});

test('announcements: compose, preview, publish, read, withdraw and role isolation',async({page,fixture},testInfo)=>{
  await page.clock.install();
  await login(page);
  await page.goto('/my-requests');
  await expect(page.getByRole('heading',{name:'Akses Saya',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Peran Anda saat ini',exact:true})).toBeVisible();
  await evidence(page,testInfo,'related-admin-page');
  await page.goto('/announcements');
  await expect(page.getByRole('heading',{name:'Pengumuman',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Buat pengumuman'}).click();
  let editor=page.getByRole('dialog',{name:'Tulis pengumuman',exact:true});
  await editor.getByLabel('Judul',{exact:true}).fill('Pertemuan pengurus');
  await editor.getByLabel('Pesan',{exact:true}).fill('Pesan untuk pengurus.\n<script>Ini teks biasa</script>');
  await expect(editor.getByRole('textbox')).toHaveCount(2);
  await expect(editor.getByRole('checkbox')).toHaveCount(0);
  await auditNotificationUI(page,'[role="dialog"]');
  await evidence(page,testInfo,'composer-message');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await evidence(page,testInfo,'composer-audience');
  await editor.getByRole('checkbox',{name:'Admin',exact:true}).check();
  await editor.getByLabel('Semua admin aktif').check();
  await editor.getByRole('button',{name:'Simpan draf'}).click();
  await expect(editor).not.toBeVisible();
  await page.getByRole('button',{name:'Edit draf'}).click();
  editor=page.getByRole('dialog',{name:'Tulis pengumuman',exact:true});
  await expect(editor.getByLabel('Judul',{exact:true})).toHaveValue('Pertemuan pengurus');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  const preview=page.getByRole('dialog',{name:'Pratinjau pengumuman',exact:true});
  await expect(preview).toContainText('2 penerima');
  await auditNotificationUI(page,'[role="dialog"]');
  await evidence(page,testInfo,'announcement-preview');
  await preview.getByRole('button',{name:'Kirim sekarang'}).click();
  await expect(preview).not.toBeVisible();
  await expect(page.getByRole('dialog',{name:'Pengumuman',exact:true})).toContainText('2 penerima');
  await page.getByRole('dialog',{name:'Pengumuman',exact:true}).getByRole('button',{name:'Tutup',exact:true}).click();
  const row=(await fixture.db.query('SELECT * FROM announcements')).rows[0];
  expect(row.recipient_count).toBe(2);
  await page.getByRole('button',{name:/Notifikasi, /}).click();
  await expect(page.getByRole('link',{name:'Pertemuan pengurus',exact:true})).toBeVisible();
  expect((await fixture.db.query('SELECT count(*)::int AS count FROM announcement_recipients WHERE read_at IS NOT NULL')).rows[0].count).toBe(0);
  await page.getByRole('link',{name:'Pertemuan pengurus',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('<script>Ini teks biasa</script>');
  await page.getByRole('dialog').getByRole('button',{name:'Tutup',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('button',{name:'Pertemuan pengurus',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:/Notifikasi, 0 belum/})).toBeVisible();
  await evidence(page,testInfo,'admin-inbox');
  await auditNotificationUI(page,'.guided-page');
  await verifyInboxRecovery(page,'/v2/notifications','Pertemuan pengurus');
  await verifyNotificationPolling(page,'/v2/notifications/unread-count');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  const second=await api('POST','/announcements',{title:'Pesan kedua',body:'Isi kedua',audience:{all_admins:true}});
  await api('POST',`/announcements/${second.id}/publish`,{version:1});
  await page.reload();
  await expect(page.getByRole('button',{name:'Pesan kedua',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Tandai dibaca',exact:true}).click();
  await expect(page.getByRole('button',{name:'Tandai dibaca',exact:true})).toHaveCount(0);
  const third=await api('POST','/announcements',{title:'Pesan ketiga',body:'Isi ketiga',audience:{all_admins:true}});
  await api('POST',`/announcements/${third.id}/publish`,{version:1});
  await page.reload();
  await page.getByRole('button',{name:'Tandai semua dibaca'}).click();
  await page.getByText('Belum dibaca',{exact:true}).click();
  await expect(page.getByText('Tidak ada notifikasi',{exact:true})).toBeVisible();
  await page.goto('/announcements');
  await page.locator('section').filter({has:page.getByRole('heading',{name:'Pertemuan pengurus',exact:true})}).getByRole('button',{name:'Tarik pengumuman'}).click();
  await page.getByRole('button',{name:'Tarik',exact:true}).click();
  await expect(page.locator('section').filter({hasText:'Pertemuan pengurus'})).toContainText('Ditarik');
  await page.goto('/notifications');
  await expect(page.getByRole('button',{name:'Pertemuan pengurus',exact:true})).toHaveCount(0);
  await page.route('**/v2/notifications?*',route=>route.fulfill({status:503,json:{message:'UNAVAILABLE'}}));
  await page.reload();
  await expect(page.getByText('Notifikasi belum dapat dimuat.',{exact:true})).toBeVisible();
  await page.unroute('**/v2/notifications?*');
  await page.getByRole('button',{name:'Coba lagi'}).click();
  await expect(page.getByRole('button',{name:'Pesan kedua',exact:true})).toBeVisible();
  await page.goto('/notifications?id=..%2Fadmin-users%2F1');
  await expect(page.getByRole('dialog')).toContainText('Pengumuman tidak tersedia.');
  await page.getByRole('dialog').getByRole('button',{name:'Tutup',exact:true}).click();
  await fixture.db.query("UPDATE admin_users SET role_code='admin' WHERE id=1");
  await page.goto('/announcements');
  await page.reload();
  await expect(page).toHaveURL(/\/forbidden$/);
});

test('targeted audience selection, saved labels and draft deletion',async({page,fixture})=>{
  const member=(await fixture.db.query("INSERT INTO public_users(email,account_status,created_at) VALUES('target@example.test','active',now()) RETURNING id")).rows[0];
  await fixture.db.query("INSERT INTO profiles(user_id,name) VALUES($1,'Anggota Pilihan')",[member.id]);
  await login(page);await page.goto('/announcements');
  await page.getByRole('button',{name:'Buat pengumuman'}).click();
  const editor=page.getByRole('dialog',{name:'Tulis pengumuman',exact:true});
  await editor.getByLabel('Judul',{exact:true}).fill('Pesan terarah');
  await editor.getByLabel('Pesan',{exact:true}).fill('Untuk penerima terpilih.');
  await editor.getByRole('button',{name:'Batal',exact:true}).click();
  await page.getByRole('button',{name:'Kembali ke editor',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Tutup tanpa menyimpan perubahan?',exact:true})).not.toBeVisible();
  await expect(editor.getByLabel('Judul',{exact:true})).toHaveValue('Pesan terarah');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await editor.getByRole('checkbox',{name:'Anggota website',exact:true}).check();
  await editor.getByRole('combobox',{name:'Anggota tertentu'}).click();
  await editor.getByRole('combobox',{name:'Anggota tertentu'}).fill('Anggota Pilihan');
  await page.locator('.ant-select-item-option-content').getByText('Anggota Pilihan · target@example.test',{exact:true}).click();
  await editor.locator('.ant-modal-title').click();
  await editor.getByRole('checkbox',{name:'Admin',exact:true}).check();
  await editor.getByRole('combobox',{name:'Peran admin',exact:true}).click();
  await page.locator('.ant-select-item-option-content').getByText('Super Admin',{exact:true}).click();
  await editor.locator('.ant-modal-title').click();
  await editor.getByRole('button',{name:'Simpan draf'}).click();await expect(editor).not.toBeVisible();
  const stored=(await fixture.db.query('SELECT audience FROM announcements')).rows[0].audience;
  expect(stored.member_ids).toEqual([member.id]);expect(stored.role_codes).toEqual(['super_admin']);
  await page.getByRole('button',{name:'Edit draf'}).click();
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await expect(editor.getByText('Anggota Pilihan · target@example.test',{exact:true})).toBeVisible();
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  const preview=page.getByRole('dialog',{name:'Pratinjau pengumuman',exact:true});
  await expect(preview).toContainText('1 anggota dan 1 admin');
  await preview.getByRole('button',{name:'Ubah penerima'}).click();
  await editor.getByRole('button',{name:'Kembali',exact:true}).click();
  await editor.getByRole('button',{name:'Batal',exact:true}).click();
  await page.getByRole('button',{name:'Hapus',exact:true}).click();
  await page.getByRole('tooltip').getByRole('button',{name:'Hapus',exact:true}).click();
  await expect(page.getByText('Belum ada pengumuman',{exact:true})).toBeVisible();
});

test('step navigation preserves input, removed choices stay cleared and preview retries safely',async({page,fixture},testInfo)=>{
  await login(page);await page.goto('/announcements');
  await page.getByRole('button',{name:'Buat pengumuman'}).click();
  const editor=page.getByRole('dialog',{name:'Tulis pengumuman',exact:true});
  await editor.getByLabel('Judul',{exact:true}).fill('Draf bertahap');
  await editor.getByLabel('Pesan',{exact:true}).fill('Pesan yang tetap tersimpan saat berpindah langkah.');
  await editor.getByRole('button',{name:'Tambahkan tautan (opsional)',exact:true}).click();
  await editor.getByLabel('Teks tombol',{exact:true}).fill('Lihat jadwal');
  await editor.getByLabel('Tautan HTTPS',{exact:true}).fill('https://example.com/jadwal');
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  for(const name of ['Anggota website','Pendaftar kegiatan','Anggota komunitas','Admin'])await editor.getByRole('checkbox',{name,exact:true}).check();
  await editor.getByLabel('Semua anggota dengan akun aktif').check();
  await editor.getByLabel('Semua admin aktif').check();
  for(const name of ['Simpan draf','Pratinjau','Kembali'])expect(await editor.getByRole('button',{name,exact:true}).evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;})).toBe(true);
  await auditNotificationUI(page,'[role="dialog"]');
  await evidence(page,testInfo,'expanded-audiences');
  await editor.getByRole('checkbox',{name:'Anggota website',exact:true}).uncheck();
  await editor.getByRole('checkbox',{name:'Pendaftar kegiatan',exact:true}).uncheck();
  await editor.getByRole('checkbox',{name:'Anggota komunitas',exact:true}).uncheck();
  await editor.getByRole('checkbox',{name:'Admin',exact:true}).focus();
  await page.keyboard.press('Space');
  await editor.getByRole('button',{name:'Kembali',exact:true}).click();
  await expect(editor.getByLabel('Judul',{exact:true})).toHaveValue('Draf bertahap');
  await expect(editor.getByLabel('Tautan HTTPS',{exact:true})).toHaveValue('https://example.com/jadwal');
  await editor.getByRole('button',{name:'Hapus tautan',exact:true}).click();
  await expect(editor.getByLabel('Tautan HTTPS',{exact:true})).toHaveCount(0);
  await editor.getByRole('button',{name:'Pilih penerima'}).click();
  await expect(editor.getByRole('checkbox',{checked:true})).toHaveCount(0);
  await editor.getByRole('checkbox',{name:'Admin',exact:true}).check();
  await expect(editor.getByLabel('Semua admin aktif')).not.toBeChecked();
  await editor.getByLabel('Semua admin aktif').check();
  await page.route('**/v2/announcements/*/preview',route=>route.fulfill({status:503,json:{message:'UNAVAILABLE'}}));
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  await expect(editor).toContainText('Draf tersimpan, tetapi penerima belum dapat dihitung.');
  await page.unroute('**/v2/announcements/*/preview');
  await editor.getByRole('button',{name:'Pratinjau',exact:true}).click();
  const preview=page.getByRole('dialog',{name:'Pratinjau pengumuman',exact:true});
  await expect(preview).toContainText('2 penerima');
  await expect(preview.getByRole('link')).toHaveCount(0);
  const rows=(await fixture.db.query('SELECT * FROM announcements')).rows;
  expect(rows).toHaveLength(1);expect(rows[0].version).toBe(2);
  expect(rows[0].link_url).toBeNull();expect(rows[0].link_label).toBeNull();
  expect(rows[0].audience.all_members).toBe(false);expect(rows[0].audience.member_ids??[]).toEqual([]);
  expect(rows[0].audience.activity_ids??[]).toEqual([]);expect(rows[0].audience.club_ids??[]).toEqual([]);
  await preview.getByRole('button',{name:'Ubah penerima'}).click();
  await editor.getByRole('button',{name:'Kembali',exact:true}).click();
  await editor.getByRole('button',{name:'Batal',exact:true}).click();
  await page.getByRole('button',{name:'Edit draf'}).click();
  await expect(editor.getByRole('button',{name:'Tambahkan tautan (opsional)',exact:true})).toBeVisible();
  await editor.getByRole('button',{name:'Simpan draf'}).click();
  await expect(editor).not.toBeVisible();
});
