import {test,expect,login,evidence} from './fixture.mjs';

test('calendar create, edit, delete and read-only roles',async({page,fixture},testInfo)=>{
  const activity=(await fixture.db.query("INSERT INTO activities(name,slug,is_published) VALUES('Kegiatan tertaut','calendar-linked',false) RETURNING id")).rows[0];
  await login(page);
  const activityLoaded=page.waitForResponse(response=>response.url().includes('/v2/activities?')&&response.status()===200);
  await page.goto('/activity');
  await activityLoaded;
  await evidence(page,testInfo,'related-activity');
  await page.goto('/calendar');
  await expect(page.getByRole('heading',{name:'Kalender Kegiatan'})).toBeVisible();
  if(testInfo.project.name==='mobile') {
    await expect(page.getByText('Belum ada acara pada periode ini')).toBeVisible();
  } else {
    await expect(page.getByRole('table')).toBeVisible();
    await expect(page.getByText('Belum ada acara pada periode ini')).toHaveCount(0);
  }
  await page.getByRole('button',{name:'Tambah acara'}).click();
  let dialog=page.getByRole('dialog',{name:'Tambah acara'});
  await dialog.getByLabel('Judul acara').fill('Musyawarah BMKA');
  await expect(dialog.getByRole('switch')).toHaveCount(0);
  await expect(dialog.locator('input[type="datetime-local"]')).toHaveCount(0);
  await expect(dialog.locator('.ant-picker')).toHaveCount(2);
  const today=new Date(Date.now()+7*3600000).toISOString().slice(0,10);
  await dialog.getByLabel('Tanggal mulai',{exact:true}).fill(new Date(today+'T12:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}));
  await dialog.getByLabel('Tanggal mulai',{exact:true}).press('Tab');
  await dialog.getByLabel('Tanggal terakhir (termasuk)').fill(new Date(today+'T12:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}));
  await dialog.getByLabel('Tanggal terakhir (termasuk)').press('Tab');
  await dialog.getByLabel('Lokasi (opsional)').fill('Masjid Salman');
  await dialog.getByLabel('Deskripsi (opsional)').fill('Koordinasi agenda bersama.');
  await dialog.getByRole('combobox',{name:'Kegiatan terkait (opsional)'}).fill('Kegiatan tertaut');
  await page.locator('.ant-select-item-option-content').getByText('Kegiatan tertaut',{exact:true}).click();
  await evidence(page,testInfo,'calendar-form');
  await dialog.getByRole('button',{name:'Simpan acara'}).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button',{name:/Musyawarah BMKA/}).first()).toBeVisible();
  const stored=(await fixture.db.query('SELECT * FROM calendar_events')).rows[0];
  expect(stored.ends_at.getTime()-stored.starts_at.getTime()).toBe(86400000);
  expect(stored.activity_id).toBe(activity.id);
  const query=new URLSearchParams({start:`${today}T00:00:00+07:00`,end:`${today}T23:59:59+07:00`});
  const publicEvents=await (await fetch(`http://localhost:3334/v2/calendar-events?${query}`)).json();
  expect(publicEvents.data.some(event=>event.title==='Musyawarah BMKA')).toBe(true);
  await evidence(page,testInfo,'calendar-default');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.getByRole('button',{name:/Musyawarah BMKA/}).first().press('Enter');
  dialog=page.getByRole('dialog',{name:'Musyawarah BMKA'});
  await expect(dialog.getByText('Koordinasi agenda bersama.')).toBeVisible();
  await dialog.getByRole('button',{name:'Ubah acara'}).click();
  dialog=page.getByRole('dialog',{name:'Ubah acara'});
  await expect(dialog.getByLabel('Tanggal terakhir (termasuk)')).toHaveValue(new Date(today+'T12:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}));
  await dialog.getByLabel('Judul acara').fill('Musyawarah diperbarui');
  await dialog.getByRole('button',{name:'Simpan acara'}).click();
  await expect(dialog).not.toBeVisible();
  await page.getByText(testInfo.project.name==='mobile'?'Bulan':'Agenda',{exact:true}).click();
  await expect(page.getByRole('button',{name:/Musyawarah diperbarui/}).first()).toBeVisible();
  await evidence(page,testInfo,'calendar-alternate-view');
  await page.route('**/v2/admin/calendar-events?*',route=>route.fulfill({status:503,json:{message:'UNAVAILABLE'}}));
  await page.getByRole('button',{name:'Bulan berikutnya'}).click();
  await expect(page.getByText('Kalender gagal dimuat')).toBeVisible();
  await page.unroute('**/v2/admin/calendar-events?*');
  await page.getByRole('button',{name:'Coba lagi'}).click();
  await expect(page.getByText('Kalender gagal dimuat')).not.toBeVisible();
  await page.getByRole('button',{name:'Hari ini'}).click();
  await page.getByRole('button',{name:/Musyawarah diperbarui/}).first().click();
  await page.getByRole('dialog',{name:'Musyawarah diperbarui'}).getByRole('button',{name:'Hapus acara'}).click();
  await page.getByRole('dialog',{name:'Hapus acara?'}).getByRole('button',{name:'Hapus acara',exact:true}).click();
  await expect(page.getByRole('button',{name:/Musyawarah diperbarui/})).toHaveCount(0);
  expect((await fixture.db.query('SELECT count(*)::int AS count FROM calendar_events')).rows[0].count).toBe(0);
  await fixture.db.query("UPDATE admin_users SET role_code='konselor' WHERE id=1");
  await page.reload();
  await expect(page.getByRole('heading',{name:'Kalender Kegiatan'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Tambah acara'})).toHaveCount(0);
});
