import {readFile} from 'node:fs/promises';
import {test,expect,login,evidence,api} from './fixture.mjs';
import {legacyRequire} from '../../scripts/fixture-db.mjs';

test('upload and publish template, issue, download, and revoke certificate',async({page,fixture},testInfo)=>{
  await api('POST','/members',{name:'Certificate browser member',email:'certificate-browser@example.test',gender:'F'});
  await api('POST','/activities',{name:'Browser certificate activity',activity_start:'2026-02-28'});
  await fixture.db.query("INSERT INTO activity_registrations(activity_id,user_id,status,created_at,updated_at) VALUES(1,1,'LULUS KEGIATAN','2024-01-01','2024-01-01')");
  await login(page);
  await page.goto('/digital-certificate');
  await page.getByRole('button',{name:/Buat desain$/}).click();
  let dialog=page.getByRole('dialog');
  await dialog.getByLabel('Nama Template',{exact:true}).fill('Browser certificate template');
  await dialog.getByRole('button',{name:'Buat desain',exact:true}).click();
  await expect(page).toHaveURL(/\/digital-certificate\/1\/edit$/);
  if(testInfo.project.name==='mobile'){
    await expect(page.getByRole('application',{name:'Kanvas desain sertifikat'})).toBeVisible();
    await evidence(page,testInfo,'mobile-certificate-editor');
    await page.getByRole('navigation',{name:'Alat editor'}).getByRole('button',{name:/Properti$/}).click();
  }
  const chooser=page.waitForEvent('filechooser');
  await page.getByRole('button',{name:/Unggah background$/}).click();
  const buffer=await legacyRequire('sharp')({create:{width:1200,height:849,channels:3,background:'#eef4ff'}}).png().toBuffer();
  const upload=page.waitForResponse(response=>response.url().endsWith('/certificate-templates/1/assets')&&response.request().method()==='POST');
  await (await chooser).setFiles({name:'synthetic-certificate.png',mimeType:'image/png',buffer});
  expect((await upload).status()).toBe(201);
  const background=page.getByAltText('Preview background sertifikat');
  await expect(background).toBeVisible();
  await expect.poll(()=>background.evaluate(image=>image.complete&&image.naturalWidth>0)).toBe(true);
  if(testInfo.project.name==='mobile'){
    await page.getByRole('dialog').getByRole('button',{name:'Selesai',exact:true}).click();
    await page.getByRole('button',{name:'Tindakan dokumen',exact:true}).click();
    await page.getByRole('menuitem',{name:'Publikasikan',exact:true}).click();
  }else await page.getByRole('button',{name:/Publikasikan$/}).click();
  dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'Publikasikan',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByText('Desain ini tersimpan sebagai versi terbit',{exact:true})).toBeVisible();
  const template=(await fixture.db.query('SELECT lifecycle_status,background_image FROM certificate_templates WHERE id=1')).rows[0];
  expect(template.lifecycle_status).toBe('published');expect(template.background_image).toBeTruthy();
  await evidence(page,testInfo,'published-certificate-template');
  await page.goto('/activity/1/certificates');
  await page.getByRole('radio',{name:'Browser certificate template',exact:true}).check();
  await page.getByRole('button',{name:'Lanjut ke penerima',exact:true}).click();
  await page.getByRole('button',{name:'Tinjau 1 sertifikat',exact:true}).click();
  await page.getByRole('button',{name:'Terbitkan 1 sertifikat',exact:true}).click();
  await expect.poll(async()=>Number((await fixture.db.query('SELECT count(*) FROM issued_certificates')).rows[0].count)).toBe(1);
  const certificate=(await fixture.db.query('SELECT id,template_snapshot,participant_snapshot FROM issued_certificates')).rows[0];
  expect(certificate.participant_snapshot.activity_date).toBe('28 Februari 2026');
  expect(certificate.template_snapshot.background_image).toBeTruthy();
  expect(certificate.template_snapshot.background_image).toBe(template.background_image);
  await page.goto(`/certificate-preview/${certificate.id}`);
  await expect.poll(()=>page.locator('img[crossorigin="anonymous"]').evaluateAll(images=>images.length>0&&images.every(image=>image.complete&&image.naturalWidth>0))).toBe(true);
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:/Unduh PDF$/}).click();
  const pdf=testInfo.outputPath('issued-certificate.pdf');await (await download).saveAs(pdf);
  expect((await readFile(pdf)).subarray(0,5).toString()).toBe('%PDF-');
  await testInfo.attach('issued-certificate',{path:pdf,contentType:'application/pdf'});
  await expect(page.getByRole('button',{name:/Unduh PDF$/})).toBeEnabled();
  await evidence(page,testInfo,'issued-certificate');
  await page.goto('/activity/1/participants');
  if(testInfo.project.name==='mobile')await page.getByRole('article').getByText(/^Detail lainnya/).click();
  await page.getByRole('button',{name:'Cabut sertifikat',exact:true}).click();
  dialog=page.getByRole('dialog');
  await dialog.getByLabel('Alasan pencabutan sertifikat',{exact:true}).fill('Browser verification revocation');
  await dialog.getByRole('button',{name:'Cabut sertifikat',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  const revoked=(await fixture.db.query('SELECT revoked_at,revoked_reason FROM issued_certificates WHERE id=$1',[certificate.id])).rows[0];
  expect(revoked.revoked_at).not.toBeNull();expect(revoked.revoked_reason).toBe('Browser verification revocation');
  await page.goto(`/certificate-preview/${certificate.id}`);
  await expect(page.getByRole('button',{name:/Unduh PDF$/})).toBeDisabled();
  await evidence(page,testInfo,'revoked-certificate');
});
