import {readFileSync} from 'node:fs';
import {test,expect,login,evidence,api} from './fixture.mjs';

const source=JSON.parse(readFileSync(new URL('../../internal/formschema/routing.fixtures.json',import.meta.url),'utf8')).schema;

test('form builder edits, previews branches, recovers drafts, and preserves routing metadata',async({page,fixture},testInfo)=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const form=await api('POST','/custom-forms',{formName:'Branching builder',formSchema:source,isActive:true});
  await login(page);
  await page.goto(`/custom-form/${form.id}/edit?tab=schema`);
  const choice=page.locator('#builder-section-choice');
  await choice.getByRole('button',{name:'Jalur',exact:false}).first().click();
  await choice.getByRole('textbox',{name:'Judul pertanyaan',exact:true}).fill('Pilih jalur');
  await choice.getByRole('textbox',{name:'Pilihan 2',exact:true}).fill('Lewati detail');
  await choice.getByRole('textbox',{name:'Nama bagian',exact:true}).fill('Pilihan peserta');
  await page.getByRole('button',{name:'Pratinjau',exact:true}).click();
  const preview=page.getByRole('dialog');
  await preview.getByText('Ponsel',{exact:true}).click();
  await expect(preview.locator('.builder-preview-mobile')).toBeVisible();
  await preview.getByText('Desktop',{exact:true}).click();
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await preview.getByRole('radio',{name:'Lewati detail',exact:true}).check();
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(preview.getByRole('heading',{name:'Penutup',exact:true})).toBeVisible();
  await expect(preview.getByRole('textbox',{name:'Alasan',exact:true})).toHaveCount(0);
  await preview.getByRole('button',{name:'Kembali',exact:true}).click();
  await preview.getByRole('radio',{name:'Detail',exact:true}).check();
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(preview.getByText('Alasan wajib diisi',{exact:true})).toBeVisible();
  await preview.getByRole('textbox',{name:'Alasan',exact:true}).fill('Alasan contoh');
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await preview.getByRole('button',{name:'Kirim (simulasi)',exact:true}).click();
  await expect(preview.getByText('Simulasi selesai',{exact:true})).toBeVisible();
  expect((await fixture.db.query('SELECT count(*)::int AS count FROM activity_registrations')).rows[0].count).toBe(0);
  await preview.getByRole('button',{name:'Mulai ulang',exact:true}).click();
  await preview.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await preview.getByRole('radio',{name:'Selesai',exact:true}).check();
  await preview.getByRole('button',{name:'Kirim (simulasi)',exact:true}).click();
  await expect(preview.getByText('Simulasi selesai',{exact:true})).toBeVisible();
  await preview.getByRole('button',{name:'Close',exact:true}).click();
  const saved=page.waitForResponse(response=>response.url().endsWith(`/custom-forms/${form.id}`)&&response.request().method()==='PUT');
  await page.getByRole('button',{name:'Simpan Perubahan',exact:true}).click();
  expect((await saved).status()).toBe(200);
  const schema=(await fixture.db.query('SELECT form_schema FROM custom_forms WHERE id=$1',[form.id])).rows[0].form_schema;
  expect(schema.version).toBe(2);expect(schema.fields[1].id).toBe('choice');
  expect(schema.fields[1].navigation).toEqual(source.fields[1].navigation);
  expect(schema.fields[1].fields[0].options[1]).toEqual({label:'Lewati detail',value:'skip'});
  await choice.getByRole('textbox',{name:'Deskripsi bagian',exact:true}).fill('Draf lokal yang dipulihkan');
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Draf tersimpan di perangkat ini');
  page.once('dialog',dialog=>dialog.accept());await page.reload();
  await expect(page.getByText('Draf yang belum disimpan tersedia',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Pulihkan draf',exact:true}).click();
  await expect(choice.getByRole('textbox',{name:'Deskripsi bagian',exact:true})).toHaveValue('Draf lokal yang dipulihkan');
  await page.getByRole('button',{name:'Menu bagian 2',exact:true}).click();
  await page.getByRole('menuitem',{name:'Duplikat bagian',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Nama bagian',exact:true})).toHaveCount(4);
  const copy=page.locator('.builder-section').filter({has:page.getByRole('textbox',{name:'Nama bagian',exact:true})}).nth(2);
  await copy.getByRole('button',{name:'Menu pertanyaan 1',exact:true}).click();
  await page.getByRole('menuitem',{name:'Duplikat pertanyaan',exact:true}).click();
  await expect(page.getByRole('menuitem',{name:'Duplikat pertanyaan',exact:true})).toBeHidden();
  await expect(copy.locator('.builder-question')).toHaveCount(2);
  await copy.getByRole('button',{name:'Menu pertanyaan 2',exact:true}).click();
  await page.getByRole('menuitem',{name:'Pindah ke atas',exact:true}).click();
  await expect(copy.locator('.builder-question-title').first()).toContainText('(salinan)');
  await page.getByRole('button',{name:'Simpan Perubahan',exact:true}).click();
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Semua perubahan tersimpan');
  await page.evaluate(()=>window.scrollTo(0,0));
  await evidence(page,testInfo,'form-builder-inline');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.goto('/activity/new');
  await expect(page.getByRole('heading',{name:'Buat kegiatan',exact:true})).toBeVisible();
  await evidence(page,testInfo,'form-builder-analogous-activity');
  expect(errors).toEqual([]);
});

test('legacy choices retain values and failed saves retain recoverable drafts',async({page,fixture},testInfo)=>{
  const legacy={fields:[{section_name:'Pilihan lama',fields:[{key:'legacy',label:'Pilihan',type:'select',required:false,options:[{label:'Nilai lama'}]}]}]};
  const form=await api('POST','/custom-forms',{formName:'Legacy recovery',isActive:true});
  await fixture.db.query('UPDATE custom_forms SET form_schema=$1::jsonb WHERE id=$2',[JSON.stringify(legacy),form.id]);
  const stored=async()=> (await fixture.db.query('SELECT form_schema FROM custom_forms WHERE id=$1',[form.id])).rows[0].form_schema;
  await login(page);await page.goto(`/custom-form/${form.id}/edit?tab=schema`);
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Semua perubahan tersimpan');
  expect(await stored()).toEqual(legacy);
  const section=page.locator('.builder-section').first();
  await section.getByRole('button',{name:'Pilihan',exact:true}).click();
  await section.getByRole('textbox',{name:'Pilihan 1',exact:true}).fill('Label baru');
  await page.getByRole('tab',{name:'Informasi Dasar',exact:true}).click();
  await page.getByRole('textbox',{name:/Nama Form$/}).fill('Draf gagal disimpan');
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Draf tersimpan di perangkat ini');
  const endpoint=`**/v2/custom-forms/${form.id}`;
  await page.route(endpoint,route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({message:'GENERAL_ERROR',error:'Synthetic save failure'})}):route.continue());
  await page.getByRole('button',{name:'Simpan Perubahan',exact:true}).click();
  await expect(page.getByText('Perubahan belum disimpan',{exact:true})).toBeVisible();
  expect(await stored()).toEqual(legacy);
  const draft=await page.evaluate(()=>{const key=Object.keys(localStorage).find(key=>key.startsWith('form-builder:v1:'));return key?JSON.parse(localStorage.getItem(key)):null;});
  expect(draft.schema.fields[1].fields[0].options[0]).toEqual({label:'Label baru',value:'Nilai lama'});
  await page.unroute(endpoint);
  await api('PUT',`/custom-forms/${form.id}`,{formDescription:'Versi server diperbarui'});
  page.once('dialog',dialog=>dialog.accept());await page.reload();
  await expect(page.getByText('Formulir di server telah berubah sejak draf dibuat. Memulihkan draf akan mengganti isi editor, belum menyimpan ke server.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Buang draf',exact:true}).click();
  await expect(page.getByRole('textbox',{name:/Nama Form$/})).toHaveValue('Legacy recovery');
  await page.getByRole('tab',{name:'Ubah Formulir',exact:true}).click();
  await section.getByRole('button',{name:'Pilihan',exact:true}).click();
  await section.getByRole('textbox',{name:'Pilihan 1',exact:true}).fill('Label tersimpan');
  await page.getByRole('button',{name:'Simpan Perubahan',exact:true}).click();
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Semua perubahan tersimpan');
  const saved=await stored();
  expect(saved.version).toBe(2);expect(saved.fields[1].id).toBeTruthy();
  expect(saved.fields[1].fields[0].options[0]).toEqual({label:'Label tersimpan',value:'Nilai lama'});
  await page.reload();expect((await stored()).fields[1].id).toBe(saved.fields[1].id);
  await evidence(page,testInfo,'form-builder-legacy-recovery');
});

test('builder keyboard sorting, routing repairs, validation settings, and empty sections',async({page,fixture},testInfo)=>{
  const controls=structuredClone(source);
  controls.fields[0].id='profile_fields';
  controls.fields[2].id='profile';
  controls.fields[3].id='submit';
  controls.fields[1].navigation.routes[0].target.sectionId='submit';
  const form=await api('POST','/custom-forms',{formName:'Builder controls',formSchema:controls,isActive:true});
  await login(page);await page.goto(`/custom-form/${form.id}/edit?tab=schema`);
  const choice=page.locator('#builder-section-choice');
  const detail=page.locator('#builder-section-profile');
  await choice.getByRole('button',{name:'Jalur',exact:false}).first().click();
  const handle=choice.getByRole('button',{name:'Geser pilihan 3',exact:true});
  await handle.focus();await page.keyboard.press('Space');
  await expect(handle).toHaveAttribute('aria-pressed','true');
  await page.keyboard.press('ArrowUp');
  await expect(page.locator('[id^="DndLiveRegion"]').filter({hasText:'over droppable area track:option:skip:1.'})).toHaveCount(1);
  await page.keyboard.press('Space');
  await expect(choice.getByRole('textbox',{name:'Pilihan 2',exact:true})).toHaveValue('Selesai');
  await choice.getByRole('button',{name:'Turunkan pilihan 2',exact:true}).click();
  await expect(choice.getByRole('textbox',{name:'Pilihan 2',exact:true})).toHaveValue('Lewati');
  await choice.getByRole('button',{name:'Naikkan pilihan 3',exact:true}).click();
  await choice.getByRole('button',{name:'Turunkan pilihan 2',exact:true}).click();
  await choice.getByRole('combobox',{name:'Tujuan untuk Detail',exact:true}).click();
  await page.getByRole('option',{name:'Kirim formulir',exact:true}).click();
  await choice.getByRole('combobox',{name:'Tujuan untuk Detail',exact:true}).click();
  await page.getByRole('option',{name:'Detail',exact:true}).click();
  await choice.getByRole('button',{name:'Tambah pilihan',exact:false}).click();
  await choice.getByRole('textbox',{name:'Pilihan 4',exact:true}).fill('Baru');
  await choice.getByRole('button',{name:'Hapus pilihan 4',exact:true}).click();
  await choice.getByRole('button',{name:'Hapus pilihan 3',exact:true}).click();
  await choice.getByRole('button',{name:'Hapus aturan',exact:true}).click();
  await expect(choice.getByText('Pilihan pada aturan sudah dihapus.',{exact:false})).toHaveCount(0);
  await detail.getByRole('button',{name:'Alasan',exact:false}).first().click();
  await detail.getByRole('button',{name:'Teks bantuan dan validasi',exact:false}).click();
  await detail.getByRole('textbox',{name:'Teks bantuan',exact:true}).fill('Gunakan huruf kapital');
  await detail.getByRole('textbox',{name:'Contoh jawaban',exact:true}).fill('SALMAN');
  await detail.getByRole('spinbutton',{name:'minLength',exact:true}).fill('3');
  await detail.getByRole('spinbutton',{name:'maxLength',exact:true}).fill('2');
  await expect(detail.getByText('Alasan: batas minimum melebihi maksimum.',{exact:true})).toBeVisible();
  await detail.getByRole('spinbutton',{name:'maxLength',exact:true}).fill('20');
  await detail.getByRole('textbox',{name:'Pola jawaban (regex)',exact:true}).fill('[');
  await expect(detail.getByText('Alasan: pola validasi tidak valid.',{exact:true})).toBeVisible();
  await detail.getByRole('textbox',{name:'Pola jawaban (regex)',exact:true}).fill('^[A-Z]+$');
  await detail.getByRole('textbox',{name:'Pesan kesalahan',exact:true}).fill('Isi huruf kapital');
  await detail.getByRole('switch',{name:'Wajib diisi',exact:true}).click();
  const sectionHandle=detail.getByRole('button',{name:'Geser bagian 2',exact:true});
  await sectionHandle.focus();await page.keyboard.press('Space');
  await expect(sectionHandle).toHaveAttribute('aria-pressed','true');
  await page.keyboard.press('ArrowUp');
  await expect(page.locator('[id^="DndLiveRegion"]').filter({hasText:'over droppable area choice.'})).toHaveCount(1);
  await page.keyboard.press('Space');
  await expect(page.getByRole('textbox',{name:'Nama bagian',exact:true}).first()).toHaveValue('Detail');
  await expect(choice.getByText('Tujuan tidak tersedia, pilih ulang',{exact:true})).toBeVisible();
  await detail.getByRole('button',{name:'Menu bagian 1',exact:true}).click();
  await page.getByRole('menuitem',{name:'Pindah ke bawah',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Nama bagian',exact:true}).first()).toHaveValue('Pilihan');
  await detail.getByRole('button',{name:'Menu pertanyaan 1',exact:true}).click();
  await page.getByRole('menuitem',{name:/^Pindah ke bagian/}).click();
  await page.getByRole('menuitem',{name:'Penutup',exact:true}).click();
  await expect(detail.locator('.builder-question')).toHaveCount(0);
  await choice.getByRole('combobox',{name:'Tujuan setelah bagian',exact:true}).focus();
  await choice.getByRole('combobox',{name:'Tujuan setelah bagian',exact:true}).press('ArrowDown');
  await page.getByRole('option',{name:'Penutup',exact:true}).click();
  await choice.getByRole('combobox',{name:'Tujuan setelah bagian',exact:true}).focus();
  await choice.getByRole('combobox',{name:'Tujuan setelah bagian',exact:true}).press('ArrowDown');
  await page.getByRole('option',{name:'Bagian berikutnya',exact:true}).click();
  await page.locator('.builder-canvas').getByRole('button',{name:'Tambah bagian',exact:false}).click();
  await page.locator('.builder-section').last().getByRole('button',{name:'Menu bagian 4',exact:true}).click();
  await page.getByRole('menuitem',{name:'Hapus bagian',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Batal',exact:true}).click();
  await page.locator('.builder-section').last().getByRole('button',{name:'Menu bagian 4',exact:true}).click();
  await page.getByRole('menuitem',{name:'Hapus bagian',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Hapus',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Nama bagian',exact:true})).toHaveCount(3);
  await page.locator('.builder-canvas').getByRole('button',{name:'Tambah bagian',exact:false}).click();
  const last=page.locator('.builder-section').last();
  await last.getByRole('textbox',{name:'Nama bagian',exact:true}).fill('Petunjuk akhir');
  await last.getByRole('textbox',{name:'Deskripsi bagian',exact:true}).fill('Terima kasih telah melengkapi formulir.');
  await last.getByRole('button',{name:'Tambah pertanyaan',exact:false}).click();
  await last.getByRole('textbox',{name:'Judul pertanyaan',exact:true}).fill('Angka');
  await last.getByRole('combobox',{name:'Jenis jawaban',exact:true}).click();
  await page.getByRole('option',{name:'Angka',exact:true}).click();
  await last.getByRole('button',{name:'Teks bantuan dan validasi',exact:false}).click();
  await last.getByRole('spinbutton',{name:'min',exact:true}).fill('0');
  await last.getByRole('spinbutton',{name:'max',exact:true}).fill('10');
  await last.getByRole('button',{name:'Menu pertanyaan 1',exact:true}).click();
  await page.getByRole('menuitem',{name:'Hapus pertanyaan',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Hapus',exact:true}).click();
  if(testInfo.project.name==='mobile'){
    await page.getByRole('button',{name:'Daftar bagian',exact:false}).click();
    await page.getByRole('dialog').getByRole('button',{name:'Data diri',exact:true}).click();
    await expect(page.locator('.builder-profile')).toBeFocused();
    await page.getByRole('button',{name:'Daftar bagian',exact:false}).click();
    await page.getByRole('dialog').getByRole('button',{name:/4\. Petunjuk akhir/}).click();
    await expect(last).toBeFocused();
  }else{
    await page.getByRole('navigation',{name:'Daftar bagian formulir',exact:true}).getByRole('button',{name:'Data diri',exact:true}).click();
    await expect(page.locator('.builder-profile')).toBeFocused();
  }
  await page.getByRole('button',{name:'Simpan Perubahan',exact:true}).click();
  await expect(page.getByRole('status',{name:'Status penyimpanan'})).toHaveText('Semua perubahan tersimpan');
  const schema=(await fixture.db.query('SELECT form_schema FROM custom_forms WHERE id=$1',[form.id])).rows[0].form_schema;
  expect(schema.fields.at(-1).fields).toEqual([]);
  expect(schema.fields.at(-1).description).toBe('Terima kasih telah melengkapi formulir.');
  expect(schema.fields.find(section=>section.id==='submit').fields.find(field=>field.key==='reason').validation).toEqual({minLength:3,maxLength:20,pattern:'^[A-Z]+$',customMessage:'Isi huruf kapital'});
  expect(schema.fields.find(section=>section.id==='choice').navigation.routes[0].target).toEqual({type:'section',sectionId:'submit'});
  await evidence(page,testInfo,'form-builder-controls');
});
