import { readFile } from 'node:fs/promises';
import { test, expect, login, evidence, api } from './fixture.mjs';

test('member export follows applied filters and supports both formats', async ({page}, testInfo) => {
  for (let i=0;i<12;i++) await api('POST','/members',{name:`Export browser ${String(i).padStart(2,'0')}`,email:`export-${i}@example.test`,whatsapp:'00123456789'});
  await login(page);
  await page.goto('/member');
  await expect(page.getByRole('button',{name:'Unduh Data',exact:true})).toBeVisible();
  await evidence(page,testInfo,'member-list-before-export');
  await page.getByRole('button',{name:/Tambah Anggota$/}).click();
  await expect(page.locator('.ant-modal:visible')).not.toHaveClass(/zoom/);
  await evidence(page,testInfo,'existing-create-member-dialog');
  await page.getByRole('dialog').getByRole('button',{name:'Batal',exact:true}).click();
  const mobile = testInfo.project.name === 'mobile';
  if(mobile) await page.getByRole('button',{name:/Filter/}).click();
  await page.getByPlaceholder('Cari nama atau email').fill('Export browser');
  if(mobile) await page.getByRole('button',{name:'Terapkan',exact:true}).click();
  else await page.getByRole('button',{name:'Terapkan pencarian anggota'}).click();
  await page.getByRole('button',{name:'Unduh Data',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Unduh Data Anggota',exact:true});
  await expect(dialog.getByText('12 baris',{exact:true})).toBeVisible();
  await expect(page.locator('.ant-modal:visible')).not.toHaveClass(/zoom/);
  await evidence(page,testInfo,'member-export-all-columns');
  await expect(dialog.getByRole('checkbox',{name:'Pilih semua kolom',exact:true})).toBeChecked();
  await dialog.getByRole('checkbox',{name:'Pilih semua kolom',exact:true}).uncheck();
  await expect(dialog.getByRole('button',{name:'Unduh',exact:true})).toBeDisabled();
  await dialog.getByRole('checkbox',{name:'Nama',exact:true}).click();
  await expect(dialog.getByRole('checkbox',{name:'Nama',exact:true})).toBeChecked();
  await dialog.getByRole('checkbox',{name:'Email',exact:true}).click();
  await expect(dialog.getByRole('checkbox',{name:'Email',exact:true})).toBeChecked();
  await dialog.getByRole('radio',{name:'CSV (.csv)',exact:true}).check();
  await evidence(page,testInfo,'member-export-selected-columns');
  const csvPromise=page.waitForEvent('download');
  await dialog.getByRole('button',{name:'Unduh',exact:true}).click();
  const csv=await csvPromise;
  expect(csv.suggestedFilename()).toBe('anggota.csv');
  const text=await readFile(await csv.path(),'utf8');
  expect(text.replace(/^\uFEFF/,'').trim().split('\n')).toHaveLength(13);
  expect(text).toContain('Nama,Email');
  expect(text).toContain('export-11@example.test');
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:'Unduh Data',exact:true}).click();
  await expect(dialog.getByText('12 baris',{exact:true})).toBeVisible();
  const xlsxPromise=page.waitForEvent('download');
  await dialog.getByRole('button',{name:'Unduh',exact:true}).click();
  const xlsx=await xlsxPromise;
  expect(xlsx.suggestedFilename()).toBe('anggota.xlsx');
  expect((await readFile(await xlsx.path())).subarray(0,2).toString()).toBe('PK');
  await page.getByRole('button',{name:'Unduh Data',exact:true}).click();
  await dialog.getByRole('button',{name:'Batal',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

test('member export handles retry and an empty filter result', async ({page}, testInfo) => {
  await api('POST','/members',{name:'Export retry member'});
  await login(page);
  await page.goto('/member');
  await page.route('**/profiles/export/preview?**',route=>route.abort());
  await page.getByRole('button',{name:'Unduh Data',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Unduh Data Anggota',exact:true});
  await expect(dialog.getByText('Jumlah anggota gagal dimuat.')).toBeVisible();
  await expect(dialog.getByRole('button',{name:'Unduh',exact:true})).toBeDisabled();
  await page.unroute('**/profiles/export/preview?**');
  await dialog.getByRole('button',{name:'Coba Lagi'}).click();
  await expect(dialog.getByText('1 baris',{exact:true})).toBeVisible();
  await page.route('**/profiles/export?**',route=>route.abort(),{times:1});
  await dialog.getByRole('button',{name:'Unduh',exact:true}).click();
  await expect(dialog.getByText(/Unduhan gagal/)).toBeVisible();
  const download=page.waitForEvent('download');
  await dialog.getByRole('button',{name:'Unduh',exact:true}).click();
  await download;
  await expect(dialog).not.toBeVisible();
  if(testInfo.project.name==='mobile') await page.getByRole('button',{name:/Filter/}).click();
  await page.getByPlaceholder('Cari nama atau email').fill('No matching export member');
  if(testInfo.project.name==='mobile') await page.getByRole('button',{name:'Terapkan',exact:true}).click();
  else await page.getByRole('button',{name:'Terapkan pencarian anggota'}).click();
  await page.getByRole('button',{name:'Unduh Data',exact:true}).click();
  await expect(dialog.getByText('0 baris',{exact:true})).toBeVisible();
  await expect(dialog.getByRole('button',{name:'Unduh',exact:true})).toBeDisabled();
  await expect(dialog.getByText('Tidak ada anggota yang sesuai filter.')).toBeVisible();
  await expect(dialog).not.toHaveClass(/zoom/);
  await dialog.getByRole('radio').first().focus();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
});

test('non-super admins cannot see member export', async ({page,fixture}) => {
  await fixture.db.query("UPDATE admin_users SET role_code='admin' WHERE id=1");
  await login(page);
  await page.goto('/member');
  await expect(page.getByRole('button',{name:/Tambah Anggota$/})).toBeVisible();
  await expect(page.getByRole('button',{name:'Unduh Data',exact:true})).toHaveCount(0);
});
