import {readFileSync} from 'node:fs';
import {test,expect,evidence,api} from '../browser/fixture.mjs';
import {fixturePassword} from '../../scripts/fixture-db.mjs';

const schema=JSON.parse(readFileSync(new URL('../../internal/formschema/routing.fixtures.json',import.meta.url),'utf8')).schema;
schema.fields[0].fields=[];

async function publicCall(method,path,body,token){
  const response=await fetch('http://localhost:3333/v2'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});
  return {status:response.status,body:await response.json()};
}

test('public branching preserves Back and recovery, prunes skipped answers, and validates response edits',async({page,fixture},testInfo)=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const member=await api('POST','/members',{name:'Routing member',email:'routing@example.test',password:fixturePassword,gender:'F'});
  const activity=await api('POST','/activities',{name:'Routing activity',activity_type:1,additional_config:{allow_guest_registration:true,custom_selection_status:[],mandatory_profile_data:[],additional_questionnaire:[]}});
  const form=await api('POST','/custom-forms',{formName:'Routing registration',featureType:'activity_registration',featureId:activity.id,isActive:true,formSchema:schema});
  await fixture.db.query("UPDATE activities SET is_published=true,is_registration_open=true,registration_start=CURRENT_DATE-1,registration_end=CURRENT_DATE+1 WHERE id=$1",[activity.id]);
  await page.goto('http://localhost:3000/login?redirect='+encodeURIComponent(`/custom-form/activity/${activity.id}`));
  await page.getByRole('textbox',{name:'Email',exact:true}).fill('routing@example.test');
  await page.getByPlaceholder('Password Anda',{exact:true}).fill(fixturePassword);
  await page.getByRole('button',{name:'Masuk',exact:true}).click();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('radio',{name:'Detail',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('textbox',{name:/^Alasan/}).fill('Jawaban yang harus dibuang');
  await page.getByRole('button',{name:'Kembali',exact:true}).click();
  await page.getByRole('radio',{name:'Lewati',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Penutup',exact:true})).toBeVisible();
  await expect(page.getByRole('textbox',{name:/^Alasan/})).toHaveCount(0);
  await page.getByRole('textbox',{name:'Catatan',exact:true}).fill('Catatan tersimpan');
  const storageKey=`customForm:v2:${member.user.id}:${form.id}`;
  await expect.poll(()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)||'null')?.answers?.note,storageKey)).toBe('Catatan tersimpan');
  await page.reload();
  await expect(page.getByRole('heading',{name:'Penutup',exact:true})).toBeVisible();
  await expect(page.getByRole('textbox',{name:'Catatan',exact:true})).toHaveValue('Catatan tersimpan');
  await evidence(page,testInfo,'public-branch-recovered');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Kembali',exact:true}).click();
  await page.getByRole('radio',{name:'Detail',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(page.getByRole('textbox',{name:/^Alasan/})).toHaveValue('');
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(page.getByText('Alasan wajib diisi',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Kembali',exact:true}).click();
  await page.getByRole('radio',{name:'Selesai',exact:true}).check();
  await page.getByRole('button',{name:'Kirim',exact:true}).click();
  await page.getByRole('dialog',{name:'Konfirmasi Pengiriman'}).getByRole('button',{name:'Ya, Kirim',exact:true}).click();
  await expect(page).toHaveURL(`http://localhost:3000/custom-form/activity/${activity.id}/success`);
  const row=async()=> (await fixture.db.query('SELECT questionnaire_answer FROM activity_registrations WHERE activity_id=$1 AND user_id=$2',[activity.id,member.user.id])).rows[0]?.questionnaire_answer;
  await expect.poll(row).toEqual({track:'finish'});
  expect(await page.evaluate(key=>localStorage.getItem(key),storageKey)).toBeNull();
  const auth=await publicCall('POST','/auth/login',{email:'routing@example.test',password:fixturePassword});
  const token=auth.body.data.token.token;
  expect((await publicCall('PUT',`/activities/${activity.slug}/registration`,{questionnaire_answer:{track:'detail'}},token)).status).toBe(422);
  expect((await publicCall('PUT',`/activities/${activity.slug}/registration`,{questionnaire_answer:{track:'skip',reason:'stale',note:'Updated'}},token)).status).toBe(200);
  expect(await row()).toEqual({track:'skip',note:'Updated'});
  await fixture.db.query('UPDATE activity_registrations SET questionnaire_answer=questionnaire_answer || $1::jsonb WHERE activity_id=$2',[JSON.stringify({removed_question:'Old response'}),activity.id]);
  await page.goto(`http://localhost:3000/profile/activity/${activity.slug}`);
  await page.getByRole('link',{name:'Ubah jawaban formulir',exact:true}).click();
  await expect(page.getByRole('radio',{name:'Lewati',exact:true})).toBeChecked();
  await page.getByRole('radio',{name:'Detail',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('textbox',{name:/^Alasan/}).fill('Jawaban yang diperbarui');
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('button',{name:'Simpan',exact:true}).click();
  await page.getByRole('dialog',{name:'Konfirmasi Pengiriman'}).getByRole('button',{name:'Ya, Kirim',exact:true}).click();
  await expect.poll(row).toEqual({track:'detail',reason:'Jawaban yang diperbarui',note:'Updated'});
  const club=await api('POST','/clubs',{name:'Routing club'});
  await api('POST','/custom-forms',{formName:'Routing club form',featureType:'club_registration',featureId:club.id,isActive:true,formSchema:schema});
  await api('PUT',`/clubs/${club.id}`,{is_show:true,is_registration_open:true});
  await page.goto(`http://localhost:3000/custom-form/club/${club.id}`);
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('radio',{name:'Selesai',exact:true}).check();
  await page.getByRole('button',{name:'Kirim',exact:true}).click();
  await page.getByRole('dialog',{name:'Konfirmasi Pengiriman'}).getByRole('button',{name:'Ya, Kirim',exact:true}).click();
  await expect(page).toHaveURL(`http://localhost:3000/custom-form/club/${club.id}/success`);
  expect((await fixture.db.query('SELECT additional_data FROM club_registrations WHERE club_id=$1',[club.id])).rows[0].additional_data).toEqual({track:'finish'});
  expect(errors).toEqual([]);
});

test('guest registration uses the same branching validation',async({page,fixture},testInfo)=>{
  const activity=await api('POST','/activities',{name:'Guest branching activity',activity_type:1,additional_config:{allow_guest_registration:true,custom_selection_status:[],mandatory_profile_data:[],additional_questionnaire:[]}});
  await api('POST','/custom-forms',{formName:'Guest routing registration',featureType:'activity_registration',featureId:activity.id,isActive:true,formSchema:schema});
  await fixture.db.query("UPDATE activities SET is_published=true,is_registration_open=true,registration_start=CURRENT_DATE-1,registration_end=CURRENT_DATE+1 WHERE id=$1",[activity.id]);
  await page.goto(`http://localhost:3000/custom-form/activity/${activity.id}?slug=${activity.slug}`);
  await page.getByRole('textbox',{name:/^Nama/}).fill('Guest routing');
  await page.getByRole('textbox',{name:/^Email/}).fill('guest-routing@example.test');
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('radio',{name:'Lewati',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Penutup',exact:true})).toBeVisible();
  await evidence(page,testInfo,'guest-branch-skips-required');
  await page.getByRole('button',{name:'Kirim',exact:true}).click();
  await page.getByRole('dialog',{name:'Konfirmasi Pengiriman'}).getByRole('button',{name:'Ya, Kirim',exact:true}).click();
  await expect(page).toHaveURL(`http://localhost:3000/custom-form/activity/${activity.id}/success`);
  const result=(await fixture.db.query('SELECT questionnaire_answer,guest_data FROM activity_registrations WHERE activity_id=$1',[activity.id])).rows[0];
  expect(result.questionnaire_answer.track).toBe('skip');expect(result.questionnaire_answer.reason).toBeUndefined();
  expect(result.guest_data.name).toBe('Guest routing');
});

test('changed schemas reset recovery safely and defaults determine the submit button',async({page,fixture},testInfo)=>{
  const activity=await api('POST','/activities',{name:'Recovery schema change',activity_type:1,additional_config:{allow_guest_registration:true,custom_selection_status:[],mandatory_profile_data:[],additional_questionnaire:[]}});
  const form=await api('POST','/custom-forms',{formName:'Recovery changes',featureType:'activity_registration',featureId:activity.id,isActive:true,formSchema:schema});
  await fixture.db.query("UPDATE activities SET is_published=true,is_registration_open=true,registration_start=CURRENT_DATE-1,registration_end=CURRENT_DATE+1 WHERE id=$1",[activity.id]);
  await page.goto(`http://localhost:3000/custom-form/activity/${activity.id}?slug=${activity.slug}`);
  await page.getByRole('textbox',{name:/^Nama/}).fill('Recovered guest');
  await page.getByRole('textbox',{name:/^Email/}).fill('recovery@example.test');
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await page.getByRole('radio',{name:'Lewati',exact:true}).check();
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect.poll(()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)||'null')?.currentId,`customForm:v2:guest:${form.id}`)).toBe('end');
  const changed=structuredClone(schema);changed.fields[1].fields[0].defaultValue='finish';changed.fields[1].id='__profile__';
  changed.fields[2].description='Petunjuk yang telah diperbarui';
  await api('PUT',`/custom-forms/${form.id}`,{formSchema:changed});
  await page.reload();
  await expect(page.getByText('Formulir atau masa penyimpanan telah berubah. Silakan isi kembali dari awal.',{exact:true})).toBeVisible();
  await page.getByRole('textbox',{name:/^Nama/}).fill('Recovered guest');
  await page.getByRole('textbox',{name:/^Email/}).fill('recovery@example.test');
  await page.getByRole('button',{name:'Lanjutkan',exact:true}).click();
  await expect(page.getByRole('radio',{name:'Selesai',exact:true})).toBeChecked();
  await expect(page.getByRole('button',{name:'Kirim',exact:true})).toBeVisible();
  await evidence(page,testInfo,'public-default-routing');
  await page.getByRole('button',{name:'Kirim',exact:true}).click();
  await page.getByRole('dialog',{name:'Konfirmasi Pengiriman'}).getByRole('button',{name:'Ya, Kirim',exact:true}).click();
  await expect(page).toHaveURL(`http://localhost:3000/custom-form/activity/${activity.id}/success`);
  expect((await fixture.db.query('SELECT questionnaire_answer FROM activity_registrations WHERE activity_id=$1',[activity.id])).rows[0].questionnaire_answer.track).toBe('finish');
});
