import {readFile} from 'node:fs/promises';
import {test,expect,evidence,api} from '../browser/fixture.mjs';
import {fixturePassword,legacyRequire} from '../../scripts/fixture-db.mjs';

test('public login, Go reference data, profile update, registration and certificate lifecycle',async({page,fixture,browser},testInfo)=>{
  const member=await api('POST','/members',{name:'Public browser member',email:'public-browser@example.test',password:fixturePassword,gender:'F'});
  await api('POST','/activities',{name:'Public browser activity',activity_start:'2026-02-28',is_published:1,additional_config:{custom_selection_status:[],mandatory_profile_data:[],additional_questionnaire:[]}});
  await api('POST','/activities/1/registrations',{user_id:member.profile.id,questionnaire_answer:{}});
  await api('PUT','/activity-registrations',{registrations_id:[1],status:'LULUS KEGIATAN'});
  await api('POST','/certificate-templates',{name:'Public browser template',templateData:{backgroundUrl:null,canvasWidth:800,canvasHeight:566,elements:[{id:'name',type:'variable-text',variable:'{{name}}',x:40,y:100,width:720,height:80,fontSize:28,fontFamily:'Arial',color:'#000000',textAlign:'center'}]}});
  const pixels=await legacyRequire('sharp')({create:{width:1200,height:849,channels:3,background:'#e7f0ff'}}).png().toBuffer();
  const form=new FormData();
  form.append('file',new Blob([pixels],{type:'image/png'}),'public-certificate-background.png');
  const background=await api('POST','/certificate-templates/1/background',form);
  expect(background.templateVersion).toBe(2);
  await api('POST','/certificate-templates/1/publish',{expectedVersion:background.templateVersion});
  await api('PUT','/activities/1',{certificate_template_id:1});
  const issued=await api('POST','/certificates/issue-single',{registration_id:1});
  const code=issued.certificate.certificate_code;
  const snapshot=(await fixture.db.query('SELECT template_snapshot FROM issued_certificates WHERE id=$1',[issued.certificate.id])).rows[0].template_snapshot;
  expect(snapshot.background_image).toBe(background.asset_key);
  await page.goto('http://localhost:3000/login?redirect=/profile');
  await page.getByRole('textbox',{name:'Email',exact:true}).fill('public-browser@example.test');
  await page.getByPlaceholder('Password Anda',{exact:true}).fill(fixturePassword);
  await page.getByRole('button',{name:'Masuk',exact:true}).click();
  await expect(page).toHaveURL('http://localhost:3000/profile');
  await expect(page.getByLabel('Nama Lengkap',{exact:true})).toHaveValue('Public browser member');
  await page.getByLabel('Nama Lengkap',{exact:true}).fill('Public updated member');
  await page.getByRole('combobox',{name:'Provinsi',exact:true}).click();
  await page.getByRole('option',{name:'Browser Province',exact:true}).click();
  await page.getByRole('combobox',{name:'Kota / Kabupaten',exact:true}).click();
  await page.getByRole('option',{name:'Browser City',exact:true}).click();
  await page.getByRole('combobox',{name:'Negara',exact:true}).click();
  await page.getByRole('option',{name:'Indonesia',exact:true}).click();
  await page.getByRole('button',{name:'Ubah Data Diri',exact:true}).click();
  await expect.poll(async()=> (await fixture.db.query('SELECT name,province_id,city_id,country FROM profiles WHERE id=1')).rows[0]).toEqual({name:'Public updated member',province_id:1,city_id:1,country:'Indonesia'});
  const updated=await api('GET','/profiles/1');expect(updated.profile[0].name).toBe('Public updated member');
  await evidence(page,testInfo,'public-profile-reference-data');
  await page.getByRole('tab',{name:'Kegiatan',exact:true}).click();
  await expect(page.getByText('Public browser activity',{exact:true})).toBeVisible();
  await evidence(page,testInfo,'public-registration');
  const backgroundResponse=page.waitForResponse(response=>response.url().endsWith(background.asset_key));
  await page.goto(`http://localhost:3000/certificate/${code}`);
  const imageResponse=await backgroundResponse;
  expect(imageResponse.ok()).toBe(true);
  await expect(page.getByText('Sertifikat atas nama Public browser member',{exact:true})).toBeVisible();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Unduh PDF',exact:true}).click();
  const pdf=testInfo.outputPath('public-owner-certificate.pdf');await (await download).saveAs(pdf);
  expect((await readFile(pdf)).subarray(0,5).toString()).toBe('%PDF-');
  expect(imageResponse.headers()['access-control-allow-origin']).toBe('http://localhost:3000');
  await testInfo.attach('public-owner-certificate',{path:pdf,contentType:'application/pdf'});
  await expect(page.getByRole('button',{name:'Unduh PDF',exact:true})).toBeEnabled();
  await expect(page.getByText('PDF sertifikat berhasil dibuat.',{exact:true})).toBeVisible();
  await expect(page.getByText('PDF sertifikat berhasil dibuat.',{exact:true})).not.toBeVisible();
  await evidence(page,testInfo,'public-issued-certificate');
  const guestContext=await browser.newContext({...testInfo.project.use,locale:'id-ID',timezoneId:'Asia/Jakarta'});
  try{
    const guest=await guestContext.newPage();
    await guest.goto(`http://localhost:3000/certificate/verify/${code}`);
    await expect(guest.getByText('Sertifikat valid',{exact:true})).toBeVisible();
    await expect(guest.getByText('public-browser@example.test',{exact:true})).toHaveCount(0);
    await evidence(guest,testInfo,'public-verification');
    await api('POST',`/certificates/${issued.certificate.id}/revoke`,{reason:'Public browser verification'});
    await guest.reload();
    await expect(guest.getByText('Sertifikat telah dicabut',{exact:true})).toBeVisible();
    await evidence(guest,testInfo,'public-revoked-verification');
    await page.reload();
    await expect(page.getByRole('button',{name:'Unduh PDF',exact:true})).toHaveCount(0);
  }finally{await guestContext.close();}
});
