// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const achievementByIdentifier = `-- name: AchievementByIdentifier :one
SELECT id, user_id, name, description, achievement_date, type, score, proof, is_proof_deleted, status, remark, approver_id, approved_at, created_at, updated_at FROM achievements WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) AchievementByIdentifier(ctx context.Context, identifier string) (Achievement, error) {
	row := q.db.QueryRow(ctx, achievementByIdentifier, identifier)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AchievementDate,
		&i.Type,
		&i.Score,
		&i.Proof,
		&i.IsProofDeleted,
		&i.Status,
		&i.Remark,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const achievementDetails = `-- name: AchievementDetails :one
SELECT a.id, a.user_id, a.name, a.description, a.achievement_date, a.type, a.score, a.proof, a.is_proof_deleted, a.status, a.remark, a.approver_id, a.approved_at, a.created_at, a.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,(to_jsonb(admin)-'password')::jsonb AS approver
FROM achievements a LEFT JOIN public_users u ON u.id=a.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users admin ON admin.id=a.approver_id
WHERE a.id = $1::integer
`

type AchievementDetailsRow struct {
	Achievement Achievement `json:"achievement"`
	PublicUser  []byte      `json:"public_user"`
	Profile     []byte      `json:"profile"`
	Approver    []byte      `json:"approver"`
}

func (q *Queries) AchievementDetails(ctx context.Context, id int32) (AchievementDetailsRow, error) {
	row := q.db.QueryRow(ctx, achievementDetails, id)
	var i AchievementDetailsRow
	err := row.Scan(
		&i.Achievement.ID,
		&i.Achievement.UserID,
		&i.Achievement.Name,
		&i.Achievement.Description,
		&i.Achievement.AchievementDate,
		&i.Achievement.Type,
		&i.Achievement.Score,
		&i.Achievement.Proof,
		&i.Achievement.IsProofDeleted,
		&i.Achievement.Status,
		&i.Achievement.Remark,
		&i.Achievement.ApproverID,
		&i.Achievement.ApprovedAt,
		&i.Achievement.CreatedAt,
		&i.Achievement.UpdatedAt,
		&i.PublicUser,
		&i.Profile,
		&i.Approver,
	)
	return i, err
}

const achievementExport = `-- name: AchievementExport :many
SELECT a.id, a.user_id, a.name, a.description, a.achievement_date, a.type, a.score, a.proof, a.is_proof_deleted, a.status, a.remark, a.approver_id, a.approved_at, a.created_at, a.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,(to_jsonb(admin)-'password')::jsonb AS approver
FROM achievements a LEFT JOIN public_users u ON u.id=a.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users admin ON admin.id=a.approver_id
ORDER BY a.created_at DESC
`

type AchievementExportRow struct {
	Achievement Achievement `json:"achievement"`
	PublicUser  []byte      `json:"public_user"`
	Profile     []byte      `json:"profile"`
	Approver    []byte      `json:"approver"`
}

func (q *Queries) AchievementExport(ctx context.Context) ([]AchievementExportRow, error) {
	rows, err := q.db.Query(ctx, achievementExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AchievementExportRow{}
	for rows.Next() {
		var i AchievementExportRow
		if err := rows.Scan(
			&i.Achievement.ID,
			&i.Achievement.UserID,
			&i.Achievement.Name,
			&i.Achievement.Description,
			&i.Achievement.AchievementDate,
			&i.Achievement.Type,
			&i.Achievement.Score,
			&i.Achievement.Proof,
			&i.Achievement.IsProofDeleted,
			&i.Achievement.Status,
			&i.Achievement.Remark,
			&i.Achievement.ApproverID,
			&i.Achievement.ApprovedAt,
			&i.Achievement.CreatedAt,
			&i.Achievement.UpdatedAt,
			&i.PublicUser,
			&i.Profile,
			&i.Approver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAchievements = `-- name: CountAchievements :one
SELECT count(*) FROM achievements a LEFT JOIN public_users u ON u.id=a.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users admin ON admin.id=a.approver_id
WHERE ($1::text IS NULL OR a.status=CAST(CAST($1 AS text) AS integer))
AND ($2::text IS NULL OR u.email=$2::text)
AND ($3::text IS NULL OR p.name ILIKE '%'||$3::text||'%')
AND ($4::text IS NULL OR a.type=CAST(CAST($4 AS text) AS integer))
`

type CountAchievementsParams struct {
	Status *string `json:"status"`
	Email  *string `json:"email"`
	Name   *string `json:"name"`
	Kind   *string `json:"kind"`
}

func (q *Queries) CountAchievements(ctx context.Context, arg CountAchievementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAchievements,
		arg.Status,
		arg.Email,
		arg.Name,
		arg.Kind,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLifetimeLeaderboard = `-- name: CountLifetimeLeaderboard :one
SELECT count(*) FROM lifetime_leaderboards b LEFT JOIN public_users u ON u.id=b.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN universities university ON university.id=p.university_id
WHERE ($1::text IS NULL OR u.email ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
`

type CountLifetimeLeaderboardParams struct {
	Email *string `json:"email"`
	Name  *string `json:"name"`
}

func (q *Queries) CountLifetimeLeaderboard(ctx context.Context, arg CountLifetimeLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLifetimeLeaderboard, arg.Email, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonthlyLeaderboard = `-- name: CountMonthlyLeaderboard :one
SELECT count(*) FROM monthly_leaderboards b LEFT JOIN public_users u ON u.id=b.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN universities university ON university.id=p.university_id
WHERE ($1::text IS NULL OR u.email ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
AND (NOT $3::boolean OR b.month IS NOT DISTINCT FROM CAST(CAST($4 AS text) AS date))
AND (NOT $5::boolean OR b.month BETWEEN CAST(CAST($6 AS text) AS date) AND CAST(CAST($7 AS text) AS date))
`

type CountMonthlyLeaderboardParams struct {
	Email       *string `json:"email"`
	Name        *string `json:"name"`
	FilterMonth bool    `json:"filter_month"`
	Month       *string `json:"month"`
	FilterYear  bool    `json:"filter_year"`
	StartDate   *string `json:"start_date"`
	EndDate     *string `json:"end_date"`
}

func (q *Queries) CountMonthlyLeaderboard(ctx context.Context, arg CountMonthlyLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMonthlyLeaderboard,
		arg.Email,
		arg.Name,
		arg.FilterMonth,
		arg.Month,
		arg.FilterYear,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLifetimeLeaderboard = `-- name: CreateLifetimeLeaderboard :one
INSERT INTO lifetime_leaderboards(user_id,score,score_academic,score_competition,score_organizational,created_at,updated_at) VALUES ($1::integer,CAST(CAST($2 AS text) AS integer),CAST(CAST($3 AS text) AS integer),CAST(CAST($4 AS text) AS integer),CAST(CAST($5 AS text) AS integer),now(),now()) RETURNING id, user_id, score_academic, score_competition, score_organizational, score, created_at, updated_at
`

type CreateLifetimeLeaderboardParams struct {
	UserID              *int32  `json:"user_id"`
	Score               *string `json:"score"`
	ScoreAcademic       *string `json:"score_academic"`
	ScoreCompetition    *string `json:"score_competition"`
	ScoreOrganizational *string `json:"score_organizational"`
}

func (q *Queries) CreateLifetimeLeaderboard(ctx context.Context, arg CreateLifetimeLeaderboardParams) (LifetimeLeaderboard, error) {
	row := q.db.QueryRow(ctx, createLifetimeLeaderboard,
		arg.UserID,
		arg.Score,
		arg.ScoreAcademic,
		arg.ScoreCompetition,
		arg.ScoreOrganizational,
	)
	var i LifetimeLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMonthlyLeaderboard = `-- name: CreateMonthlyLeaderboard :one
INSERT INTO monthly_leaderboards(user_id,month,score,score_academic,score_competition,score_organizational,created_at,updated_at) VALUES ($1::integer,$2::date,CAST(CAST($3 AS text) AS integer),CAST(CAST($4 AS text) AS integer),CAST(CAST($5 AS text) AS integer),CAST(CAST($6 AS text) AS integer),now(),now()) RETURNING id, user_id, month, score_academic, score_competition, score_organizational, score, created_at, updated_at
`

type CreateMonthlyLeaderboardParams struct {
	UserID              *int32      `json:"user_id"`
	Month               pgtype.Date `json:"month"`
	Score               *string     `json:"score"`
	ScoreAcademic       *string     `json:"score_academic"`
	ScoreCompetition    *string     `json:"score_competition"`
	ScoreOrganizational *string     `json:"score_organizational"`
}

func (q *Queries) CreateMonthlyLeaderboard(ctx context.Context, arg CreateMonthlyLeaderboardParams) (MonthlyLeaderboard, error) {
	row := q.db.QueryRow(ctx, createMonthlyLeaderboard,
		arg.UserID,
		arg.Month,
		arg.Score,
		arg.ScoreAcademic,
		arg.ScoreCompetition,
		arg.ScoreOrganizational,
	)
	var i MonthlyLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLifetimeLeaderboard = `-- name: FindLifetimeLeaderboard :one
SELECT id, user_id, score_academic, score_competition, score_organizational, score, created_at, updated_at FROM lifetime_leaderboards WHERE user_id IS NOT DISTINCT FROM $1::integer LIMIT 1
`

func (q *Queries) FindLifetimeLeaderboard(ctx context.Context, userID *int32) (LifetimeLeaderboard, error) {
	row := q.db.QueryRow(ctx, findLifetimeLeaderboard, userID)
	var i LifetimeLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMonthlyLeaderboard = `-- name: FindMonthlyLeaderboard :one
SELECT id, user_id, month, score_academic, score_competition, score_organizational, score, created_at, updated_at FROM monthly_leaderboards WHERE user_id IS NOT DISTINCT FROM $1::integer AND month=$2::date LIMIT 1
`

type FindMonthlyLeaderboardParams struct {
	UserID *int32      `json:"user_id"`
	Month  pgtype.Date `json:"month"`
}

func (q *Queries) FindMonthlyLeaderboard(ctx context.Context, arg FindMonthlyLeaderboardParams) (MonthlyLeaderboard, error) {
	row := q.db.QueryRow(ctx, findMonthlyLeaderboard, arg.UserID, arg.Month)
	var i MonthlyLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAchievements = `-- name: ListAchievements :many
SELECT a.id, a.user_id, a.name, a.description, a.achievement_date, a.type, a.score, a.proof, a.is_proof_deleted, a.status, a.remark, a.approver_id, a.approved_at, a.created_at, a.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,(to_jsonb(admin)-'password')::jsonb AS approver
FROM achievements a LEFT JOIN public_users u ON u.id=a.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users admin ON admin.id=a.approver_id
WHERE ($1::text IS NULL OR a.status=CAST(CAST($1 AS text) AS integer))
AND ($2::text IS NULL OR u.email=$2::text)
AND ($3::text IS NULL OR p.name ILIKE '%'||$3::text||'%')
AND ($4::text IS NULL OR a.type=CAST(CAST($4 AS text) AS integer))
ORDER BY CASE WHEN $5::boolean AND $6::boolean THEN a.achievement_date END ASC,
CASE WHEN $5::boolean AND NOT $6::boolean THEN a.achievement_date END DESC,
CASE WHEN NOT $5::boolean AND $6::boolean THEN a.created_at END ASC,
CASE WHEN NOT $5::boolean AND NOT $6::boolean THEN a.created_at END DESC
LIMIT $8::bigint OFFSET $7::bigint
`

type ListAchievementsParams struct {
	Status     *string `json:"status"`
	Email      *string `json:"email"`
	Name       *string `json:"name"`
	Kind       *string `json:"kind"`
	DateOrder  bool    `json:"date_order"`
	Ascending  bool    `json:"ascending"`
	PageOffset int64   `json:"page_offset"`
	PageSize   *int64  `json:"page_size"`
}

type ListAchievementsRow struct {
	Achievement Achievement `json:"achievement"`
	PublicUser  []byte      `json:"public_user"`
	Profile     []byte      `json:"profile"`
	Approver    []byte      `json:"approver"`
}

func (q *Queries) ListAchievements(ctx context.Context, arg ListAchievementsParams) ([]ListAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listAchievements,
		arg.Status,
		arg.Email,
		arg.Name,
		arg.Kind,
		arg.DateOrder,
		arg.Ascending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAchievementsRow{}
	for rows.Next() {
		var i ListAchievementsRow
		if err := rows.Scan(
			&i.Achievement.ID,
			&i.Achievement.UserID,
			&i.Achievement.Name,
			&i.Achievement.Description,
			&i.Achievement.AchievementDate,
			&i.Achievement.Type,
			&i.Achievement.Score,
			&i.Achievement.Proof,
			&i.Achievement.IsProofDeleted,
			&i.Achievement.Status,
			&i.Achievement.Remark,
			&i.Achievement.ApproverID,
			&i.Achievement.ApprovedAt,
			&i.Achievement.CreatedAt,
			&i.Achievement.UpdatedAt,
			&i.PublicUser,
			&i.Profile,
			&i.Approver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifetimeLeaderboard = `-- name: ListLifetimeLeaderboard :many
SELECT b.id, b.user_id, b.score_academic, b.score_competition, b.score_organizational, b.score, b.created_at, b.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,row_to_json(university) AS university
FROM lifetime_leaderboards b LEFT JOIN public_users u ON u.id=b.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN universities university ON university.id=p.university_id
WHERE ($1::text IS NULL OR u.email ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
ORDER BY b.score DESC LIMIT $4::bigint OFFSET $3::bigint
`

type ListLifetimeLeaderboardParams struct {
	Email      *string `json:"email"`
	Name       *string `json:"name"`
	PageOffset int64   `json:"page_offset"`
	PageSize   *int64  `json:"page_size"`
}

type ListLifetimeLeaderboardRow struct {
	LifetimeLeaderboard LifetimeLeaderboard `json:"lifetime_leaderboard"`
	PublicUser          []byte              `json:"public_user"`
	Profile             []byte              `json:"profile"`
	University          []byte              `json:"university"`
}

func (q *Queries) ListLifetimeLeaderboard(ctx context.Context, arg ListLifetimeLeaderboardParams) ([]ListLifetimeLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listLifetimeLeaderboard,
		arg.Email,
		arg.Name,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLifetimeLeaderboardRow{}
	for rows.Next() {
		var i ListLifetimeLeaderboardRow
		if err := rows.Scan(
			&i.LifetimeLeaderboard.ID,
			&i.LifetimeLeaderboard.UserID,
			&i.LifetimeLeaderboard.ScoreAcademic,
			&i.LifetimeLeaderboard.ScoreCompetition,
			&i.LifetimeLeaderboard.ScoreOrganizational,
			&i.LifetimeLeaderboard.Score,
			&i.LifetimeLeaderboard.CreatedAt,
			&i.LifetimeLeaderboard.UpdatedAt,
			&i.PublicUser,
			&i.Profile,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyLeaderboard = `-- name: ListMonthlyLeaderboard :many
SELECT b.id, b.user_id, b.month, b.score_academic, b.score_competition, b.score_organizational, b.score, b.created_at, b.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,row_to_json(university) AS university
FROM monthly_leaderboards b LEFT JOIN public_users u ON u.id=b.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN universities university ON university.id=p.university_id
WHERE ($1::text IS NULL OR u.email ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
AND (NOT $3::boolean OR b.month IS NOT DISTINCT FROM CAST(CAST($4 AS text) AS date))
AND (NOT $5::boolean OR b.month BETWEEN CAST(CAST($6 AS text) AS date) AND CAST(CAST($7 AS text) AS date))
ORDER BY b.score DESC LIMIT $9::bigint OFFSET $8::bigint
`

type ListMonthlyLeaderboardParams struct {
	Email       *string `json:"email"`
	Name        *string `json:"name"`
	FilterMonth bool    `json:"filter_month"`
	Month       *string `json:"month"`
	FilterYear  bool    `json:"filter_year"`
	StartDate   *string `json:"start_date"`
	EndDate     *string `json:"end_date"`
	PageOffset  int64   `json:"page_offset"`
	PageSize    *int64  `json:"page_size"`
}

type ListMonthlyLeaderboardRow struct {
	MonthlyLeaderboard MonthlyLeaderboard `json:"monthly_leaderboard"`
	PublicUser         []byte             `json:"public_user"`
	Profile            []byte             `json:"profile"`
	University         []byte             `json:"university"`
}

func (q *Queries) ListMonthlyLeaderboard(ctx context.Context, arg ListMonthlyLeaderboardParams) ([]ListMonthlyLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyLeaderboard,
		arg.Email,
		arg.Name,
		arg.FilterMonth,
		arg.Month,
		arg.FilterYear,
		arg.StartDate,
		arg.EndDate,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyLeaderboardRow{}
	for rows.Next() {
		var i ListMonthlyLeaderboardRow
		if err := rows.Scan(
			&i.MonthlyLeaderboard.ID,
			&i.MonthlyLeaderboard.UserID,
			&i.MonthlyLeaderboard.Month,
			&i.MonthlyLeaderboard.ScoreAcademic,
			&i.MonthlyLeaderboard.ScoreCompetition,
			&i.MonthlyLeaderboard.ScoreOrganizational,
			&i.MonthlyLeaderboard.Score,
			&i.MonthlyLeaderboard.CreatedAt,
			&i.MonthlyLeaderboard.UpdatedAt,
			&i.PublicUser,
			&i.Profile,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAchievement = `-- name: UpdateAchievement :one
UPDATE achievements SET name=$1::text,description=$2::text,type=CAST(CAST($3 AS text) AS integer),score=CAST(CAST($4 AS text) AS integer),proof=$5::text,status=CAST(CAST($6 AS text) AS integer),remark=$7::text,approver_id=CAST(CAST($8 AS text) AS integer),approved_at=$9::date,
updated_at=CASE WHEN $10::boolean OR ROW(name,description,type,score,proof,status,remark,approver_id,approved_at) IS DISTINCT FROM ROW($1::text,$2::text,CAST(CAST($3 AS text) AS integer),CAST(CAST($4 AS text) AS integer),$5::text,CAST(CAST($6 AS text) AS integer),$7::text,CAST(CAST($8 AS text) AS integer),$9::date) THEN now() ELSE updated_at END WHERE id = $11::integer RETURNING id, user_id, name, description, achievement_date, type, score, proof, is_proof_deleted, status, remark, approver_id, approved_at, created_at, updated_at
`

type UpdateAchievementParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Type        *string     `json:"type"`
	Score       *string     `json:"score"`
	Proof       *string     `json:"proof"`
	Status      *string     `json:"status"`
	Remark      *string     `json:"remark"`
	ApproverID  *string     `json:"approver_id"`
	ApprovedAt  pgtype.Date `json:"approved_at"`
	Touch       bool        `json:"touch"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievement,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Score,
		arg.Proof,
		arg.Status,
		arg.Remark,
		arg.ApproverID,
		arg.ApprovedAt,
		arg.Touch,
		arg.ID,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AchievementDate,
		&i.Type,
		&i.Score,
		&i.Proof,
		&i.IsProofDeleted,
		&i.Status,
		&i.Remark,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLifetimeLeaderboard = `-- name: UpdateLifetimeLeaderboard :one
UPDATE lifetime_leaderboards SET score=CAST(CAST($1 AS text) AS integer),score_academic=CAST(CAST($2 AS text) AS integer),score_competition=CAST(CAST($3 AS text) AS integer),score_organizational=CAST(CAST($4 AS text) AS integer),updated_at=CASE WHEN ROW(score,score_academic,score_competition,score_organizational) IS DISTINCT FROM ROW(CAST(CAST($1 AS text) AS integer),CAST(CAST($2 AS text) AS integer),CAST(CAST($3 AS text) AS integer),CAST(CAST($4 AS text) AS integer)) THEN now() ELSE updated_at END WHERE id = $5::integer RETURNING id, user_id, score_academic, score_competition, score_organizational, score, created_at, updated_at
`

type UpdateLifetimeLeaderboardParams struct {
	Score               *string `json:"score"`
	ScoreAcademic       *string `json:"score_academic"`
	ScoreCompetition    *string `json:"score_competition"`
	ScoreOrganizational *string `json:"score_organizational"`
	ID                  int32   `json:"id"`
}

func (q *Queries) UpdateLifetimeLeaderboard(ctx context.Context, arg UpdateLifetimeLeaderboardParams) (LifetimeLeaderboard, error) {
	row := q.db.QueryRow(ctx, updateLifetimeLeaderboard,
		arg.Score,
		arg.ScoreAcademic,
		arg.ScoreCompetition,
		arg.ScoreOrganizational,
		arg.ID,
	)
	var i LifetimeLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonthlyLeaderboard = `-- name: UpdateMonthlyLeaderboard :one
UPDATE monthly_leaderboards SET score=CAST(CAST($1 AS text) AS integer),score_academic=CAST(CAST($2 AS text) AS integer),score_competition=CAST(CAST($3 AS text) AS integer),score_organizational=CAST(CAST($4 AS text) AS integer),updated_at=CASE WHEN ROW(score,score_academic,score_competition,score_organizational) IS DISTINCT FROM ROW(CAST(CAST($1 AS text) AS integer),CAST(CAST($2 AS text) AS integer),CAST(CAST($3 AS text) AS integer),CAST(CAST($4 AS text) AS integer)) THEN now() ELSE updated_at END WHERE id = $5::integer RETURNING id, user_id, month, score_academic, score_competition, score_organizational, score, created_at, updated_at
`

type UpdateMonthlyLeaderboardParams struct {
	Score               *string `json:"score"`
	ScoreAcademic       *string `json:"score_academic"`
	ScoreCompetition    *string `json:"score_competition"`
	ScoreOrganizational *string `json:"score_organizational"`
	ID                  int32   `json:"id"`
}

func (q *Queries) UpdateMonthlyLeaderboard(ctx context.Context, arg UpdateMonthlyLeaderboardParams) (MonthlyLeaderboard, error) {
	row := q.db.QueryRow(ctx, updateMonthlyLeaderboard,
		arg.Score,
		arg.ScoreAcademic,
		arg.ScoreCompetition,
		arg.ScoreOrganizational,
		arg.ID,
	)
	var i MonthlyLeaderboard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.ScoreAcademic,
		&i.ScoreCompetition,
		&i.ScoreOrganizational,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
