// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityDetails = `-- name: ActivityDetails :one
SELECT a.id, a.name, a.slug, a.description, a.badge, a.activity_start, a.activity_end, a.registration_start, a.registration_end, a.selection_start, a.selection_end, a.activity_type, a.activity_category, a.additional_config, a.minimum_level, a.is_published, a.created_at, a.updated_at, a.is_registration_open, a.club_id, a.certificate_template_id,to_jsonb(c) AS club FROM activities a LEFT JOIN clubs c ON c.id=a.club_id WHERE a.id=$1
`

type ActivityDetailsRow struct {
	Activity Activity `json:"activity"`
	Club     []byte   `json:"club"`
}

func (q *Queries) ActivityDetails(ctx context.Context, id int32) (ActivityDetailsRow, error) {
	row := q.db.QueryRow(ctx, activityDetails, id)
	var i ActivityDetailsRow
	err := row.Scan(
		&i.Activity.ID,
		&i.Activity.Name,
		&i.Activity.Slug,
		&i.Activity.Description,
		&i.Activity.Badge,
		&i.Activity.ActivityStart,
		&i.Activity.ActivityEnd,
		&i.Activity.RegistrationStart,
		&i.Activity.RegistrationEnd,
		&i.Activity.SelectionStart,
		&i.Activity.SelectionEnd,
		&i.Activity.ActivityType,
		&i.Activity.ActivityCategory,
		&i.Activity.AdditionalConfig,
		&i.Activity.MinimumLevel,
		&i.Activity.IsPublished,
		&i.Activity.CreatedAt,
		&i.Activity.UpdatedAt,
		&i.Activity.IsRegistrationOpen,
		&i.Activity.ClubID,
		&i.Activity.CertificateTemplateID,
		&i.Club,
	)
	return i, err
}

const activitySlugExists = `-- name: ActivitySlugExists :one
SELECT EXISTS(SELECT 1 FROM activities WHERE slug=$1)
`

func (q *Queries) ActivitySlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, activitySlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const certificateTemplateByID = `-- name: CertificateTemplateByID :one
SELECT id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at FROM certificate_templates WHERE id=$1
`

func (q *Queries) CertificateTemplateByID(ctx context.Context, id int32) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, certificateTemplateByID, id)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countActivitiesFiltered = `-- name: CountActivitiesFiltered :one
SELECT count(*) FROM activities a WHERE a.name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR a.activity_category=CAST(CAST($2 AS text) AS integer))
AND ($3::text IS NULL OR a.minimum_level=CAST(CAST($3 AS text) AS integer))
AND ($4::text IS NULL OR a.activity_type=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR a.is_published=CAST(CAST($5 AS text) AS boolean))
AND ($6::text IS NULL OR a.club_id=CAST(CAST($6 AS text) AS integer))
`

type CountActivitiesFilteredParams struct {
	Search       string  `json:"search"`
	Category     *string `json:"category"`
	MinimumLevel *string `json:"minimum_level"`
	ActivityType *string `json:"activity_type"`
	IsPublished  *string `json:"is_published"`
	ClubID       *string `json:"club_id"`
}

func (q *Queries) CountActivitiesFiltered(ctx context.Context, arg CountActivitiesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitiesFiltered,
		arg.Search,
		arg.Category,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.IsPublished,
		arg.ClubID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities WHERE id=$1
`

func (q *Queries) DeleteActivity(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivitiesFiltered = `-- name: ListActivitiesFiltered :many
SELECT a.id,a.name,a.activity_start,a.activity_end,a.registration_start,a.registration_end,a.selection_start,a.selection_end,a.activity_type,a.activity_category,a.club_id,a.is_published,a.is_registration_open,to_jsonb(c) AS club
FROM activities a LEFT JOIN clubs c ON c.id=a.club_id
WHERE a.name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR a.activity_category=CAST(CAST($2 AS text) AS integer))
AND ($3::text IS NULL OR a.minimum_level=CAST(CAST($3 AS text) AS integer))
AND ($4::text IS NULL OR a.activity_type=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR a.is_published=CAST(CAST($5 AS text) AS boolean))
AND ($6::text IS NULL OR a.club_id=CAST(CAST($6 AS text) AS integer))
ORDER BY a.is_published DESC,a.created_at DESC LIMIT $8::bigint OFFSET $7::bigint
`

type ListActivitiesFilteredParams struct {
	Search       string  `json:"search"`
	Category     *string `json:"category"`
	MinimumLevel *string `json:"minimum_level"`
	ActivityType *string `json:"activity_type"`
	IsPublished  *string `json:"is_published"`
	ClubID       *string `json:"club_id"`
	PageOffset   int64   `json:"page_offset"`
	PageSize     *int64  `json:"page_size"`
}

type ListActivitiesFilteredRow struct {
	ID                 int32       `json:"id"`
	Name               string      `json:"name"`
	ActivityStart      pgtype.Date `json:"activity_start"`
	ActivityEnd        pgtype.Date `json:"activity_end"`
	RegistrationStart  pgtype.Date `json:"registration_start"`
	RegistrationEnd    pgtype.Date `json:"registration_end"`
	SelectionStart     pgtype.Date `json:"selection_start"`
	SelectionEnd       pgtype.Date `json:"selection_end"`
	ActivityType       *int32      `json:"activity_type"`
	ActivityCategory   *int32      `json:"activity_category"`
	ClubID             *int32      `json:"club_id"`
	IsPublished        *bool       `json:"is_published"`
	IsRegistrationOpen bool        `json:"is_registration_open"`
	Club               []byte      `json:"club"`
}

func (q *Queries) ListActivitiesFiltered(ctx context.Context, arg ListActivitiesFilteredParams) ([]ListActivitiesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesFiltered,
		arg.Search,
		arg.Category,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.IsPublished,
		arg.ClubID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesFilteredRow{}
	for rows.Next() {
		var i ListActivitiesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ActivityStart,
			&i.ActivityEnd,
			&i.RegistrationStart,
			&i.RegistrationEnd,
			&i.SelectionStart,
			&i.SelectionEnd,
			&i.ActivityType,
			&i.ActivityCategory,
			&i.ClubID,
			&i.IsPublished,
			&i.IsRegistrationOpen,
			&i.Club,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
