// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activityDetails = `-- name: ActivityDetails :one
SELECT a.id, a.name, a.slug, a.description, a.badge, a.activity_start, a.activity_end, a.registration_start, a.registration_end, a.selection_start, a.selection_end, a.activity_type, a.activity_category, a.additional_config, a.minimum_level, a.is_published, a.created_at, a.updated_at, a.is_registration_open, a.club_id, a.certificate_template_id,to_jsonb(c) AS club FROM activities a LEFT JOIN clubs c ON c.id=a.club_id WHERE a.id=$1
`

type ActivityDetailsRow struct {
	Activity Activity `json:"activity"`
	Club     []byte   `json:"club"`
}

func (q *Queries) ActivityDetails(ctx context.Context, id int32) (ActivityDetailsRow, error) {
	row := q.db.QueryRow(ctx, activityDetails, id)
	var i ActivityDetailsRow
	err := row.Scan(
		&i.Activity.ID,
		&i.Activity.Name,
		&i.Activity.Slug,
		&i.Activity.Description,
		&i.Activity.Badge,
		&i.Activity.ActivityStart,
		&i.Activity.ActivityEnd,
		&i.Activity.RegistrationStart,
		&i.Activity.RegistrationEnd,
		&i.Activity.SelectionStart,
		&i.Activity.SelectionEnd,
		&i.Activity.ActivityType,
		&i.Activity.ActivityCategory,
		&i.Activity.AdditionalConfig,
		&i.Activity.MinimumLevel,
		&i.Activity.IsPublished,
		&i.Activity.CreatedAt,
		&i.Activity.UpdatedAt,
		&i.Activity.IsRegistrationOpen,
		&i.Activity.ClubID,
		&i.Activity.CertificateTemplateID,
		&i.Club,
	)
	return i, err
}

const activitySlugExists = `-- name: ActivitySlugExists :one
SELECT EXISTS(SELECT 1 FROM activities WHERE slug=$1)
`

func (q *Queries) ActivitySlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, activitySlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const certificateTemplateByID = `-- name: CertificateTemplateByID :one
SELECT id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at FROM certificate_templates WHERE id=$1
`

func (q *Queries) CertificateTemplateByID(ctx context.Context, id int32) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, certificateTemplateByID, id)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const certificateTemplateByIdentifier = `-- name: CertificateTemplateByIdentifier :one
SELECT id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at FROM certificate_templates WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CertificateTemplateByIdentifier(ctx context.Context, identifier string) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, certificateTemplateByIdentifier, identifier)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countActivitiesFiltered = `-- name: CountActivitiesFiltered :one
SELECT count(*) FROM activities a WHERE a.name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR a.activity_category=CAST(CAST($2 AS text) AS integer))
AND ($3::text IS NULL OR a.minimum_level=CAST(CAST($3 AS text) AS integer))
AND ($4::text IS NULL OR a.activity_type=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR a.is_published=CAST(CAST($5 AS text) AS boolean))
AND ($6::text IS NULL OR a.club_id=CAST(CAST($6 AS text) AS integer))
`

type CountActivitiesFilteredParams struct {
	Search       string  `json:"search"`
	Category     *string `json:"category"`
	MinimumLevel *string `json:"minimum_level"`
	ActivityType *string `json:"activity_type"`
	IsPublished  *string `json:"is_published"`
	ClubID       *string `json:"club_id"`
}

func (q *Queries) CountActivitiesFiltered(ctx context.Context, arg CountActivitiesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitiesFiltered,
		arg.Search,
		arg.Category,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.IsPublished,
		arg.ClubID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities(name,description,badge,activity_start,activity_end,registration_start,registration_end,selection_start,selection_end,minimum_level,activity_type,activity_category,is_published,is_registration_open,slug,club_id,certificate_template_id,additional_config,created_at,updated_at)
VALUES ($1::text,$2::text,$3::text,CAST(CAST($4 AS text) AS date),CAST(CAST($5 AS text) AS date),CAST(CAST($6 AS text) AS date),CAST(CAST($7 AS text) AS date),CAST(CAST($8 AS text) AS date),CAST(CAST($9 AS text) AS date),COALESCE(CAST(CAST($10 AS text) AS integer),0),CAST(CAST($11 AS text) AS integer),CAST(CAST($12 AS text) AS integer),COALESCE(CAST(CAST($13 AS text) AS boolean),false),COALESCE($14::boolean,true),$15::text,CAST(CAST($16 AS text) AS integer),CAST(CAST($17 AS text) AS integer),COALESCE($18::jsonb,'{"images":[],"mandatory_profile_data":[],"custom_selection_status":[],"additional_questionnaire":[]}'::jsonb),now(),now()) RETURNING id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id
`

type CreateActivityParams struct {
	Name                  *string `json:"name"`
	Description           *string `json:"description"`
	Badge                 *string `json:"badge"`
	ActivityStart         *string `json:"activity_start"`
	ActivityEnd           *string `json:"activity_end"`
	RegistrationStart     *string `json:"registration_start"`
	RegistrationEnd       *string `json:"registration_end"`
	SelectionStart        *string `json:"selection_start"`
	SelectionEnd          *string `json:"selection_end"`
	MinimumLevel          *string `json:"minimum_level"`
	ActivityType          *string `json:"activity_type"`
	ActivityCategory      *string `json:"activity_category"`
	IsPublished           *string `json:"is_published"`
	IsRegistrationOpen    *bool   `json:"is_registration_open"`
	Slug                  string  `json:"slug"`
	ClubID                *string `json:"club_id"`
	CertificateTemplateID *string `json:"certificate_template_id"`
	AdditionalConfig      []byte  `json:"additional_config"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.Name,
		arg.Description,
		arg.Badge,
		arg.ActivityStart,
		arg.ActivityEnd,
		arg.RegistrationStart,
		arg.RegistrationEnd,
		arg.SelectionStart,
		arg.SelectionEnd,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.ActivityCategory,
		arg.IsPublished,
		arg.IsRegistrationOpen,
		arg.Slug,
		arg.ClubID,
		arg.CertificateTemplateID,
		arg.AdditionalConfig,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities WHERE id=$1
`

func (q *Queries) DeleteActivity(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivitiesFiltered = `-- name: ListActivitiesFiltered :many
SELECT a.id,a.name,a.activity_start,a.activity_end,a.registration_start,a.registration_end,a.selection_start,a.selection_end,a.activity_type,a.activity_category,a.club_id,a.is_published,a.is_registration_open,to_jsonb(c) AS club
FROM activities a LEFT JOIN clubs c ON c.id=a.club_id
WHERE a.name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR a.activity_category=CAST(CAST($2 AS text) AS integer))
AND ($3::text IS NULL OR a.minimum_level=CAST(CAST($3 AS text) AS integer))
AND ($4::text IS NULL OR a.activity_type=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR a.is_published=CAST(CAST($5 AS text) AS boolean))
AND ($6::text IS NULL OR a.club_id=CAST(CAST($6 AS text) AS integer))
ORDER BY a.is_published DESC,a.created_at DESC LIMIT $8::bigint OFFSET $7::bigint
`

type ListActivitiesFilteredParams struct {
	Search       string  `json:"search"`
	Category     *string `json:"category"`
	MinimumLevel *string `json:"minimum_level"`
	ActivityType *string `json:"activity_type"`
	IsPublished  *string `json:"is_published"`
	ClubID       *string `json:"club_id"`
	PageOffset   int64   `json:"page_offset"`
	PageSize     *int64  `json:"page_size"`
}

type ListActivitiesFilteredRow struct {
	ID                 int32       `json:"id"`
	Name               string      `json:"name"`
	ActivityStart      pgtype.Date `json:"activity_start"`
	ActivityEnd        pgtype.Date `json:"activity_end"`
	RegistrationStart  pgtype.Date `json:"registration_start"`
	RegistrationEnd    pgtype.Date `json:"registration_end"`
	SelectionStart     pgtype.Date `json:"selection_start"`
	SelectionEnd       pgtype.Date `json:"selection_end"`
	ActivityType       *int32      `json:"activity_type"`
	ActivityCategory   *int32      `json:"activity_category"`
	ClubID             *int32      `json:"club_id"`
	IsPublished        *bool       `json:"is_published"`
	IsRegistrationOpen bool        `json:"is_registration_open"`
	Club               []byte      `json:"club"`
}

func (q *Queries) ListActivitiesFiltered(ctx context.Context, arg ListActivitiesFilteredParams) ([]ListActivitiesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesFiltered,
		arg.Search,
		arg.Category,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.IsPublished,
		arg.ClubID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesFilteredRow{}
	for rows.Next() {
		var i ListActivitiesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ActivityStart,
			&i.ActivityEnd,
			&i.RegistrationStart,
			&i.RegistrationEnd,
			&i.SelectionStart,
			&i.SelectionEnd,
			&i.ActivityType,
			&i.ActivityCategory,
			&i.ClubID,
			&i.IsPublished,
			&i.IsRegistrationOpen,
			&i.Club,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities SET
name = COALESCE($1::text,name),
description = COALESCE($2::text,description),
badge = COALESCE($3::text,badge),
activity_start = COALESCE(CAST(CAST($4 AS text) AS date),activity_start),
activity_end = COALESCE(CAST(CAST($5 AS text) AS date),activity_end),
registration_start = COALESCE(CAST(CAST($6 AS text) AS date),registration_start),
registration_end = COALESCE(CAST(CAST($7 AS text) AS date),registration_end),
selection_start = COALESCE(CAST(CAST($8 AS text) AS date),selection_start),
selection_end = COALESCE(CAST(CAST($9 AS text) AS date),selection_end),
minimum_level = COALESCE(CAST(CAST($10 AS text) AS integer),minimum_level),
activity_type = COALESCE(CAST(CAST($11 AS text) AS integer),activity_type),
activity_category = COALESCE(CAST(CAST($12 AS text) AS integer),activity_category),
is_published = COALESCE(CAST(CAST($13 AS text) AS boolean),is_published),
is_registration_open = COALESCE($14::boolean,is_registration_open),
club_id=CASE WHEN $15::boolean THEN CAST(CAST($16 AS text) AS integer) ELSE club_id END,
certificate_template_id=CASE WHEN $17::boolean THEN CAST(CAST($18 AS text) AS integer) ELSE certificate_template_id END,
additional_config = $19::jsonb,updated_at=now() WHERE id = $20::integer RETURNING id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id
`

type UpdateActivityParams struct {
	Name                  *string `json:"name"`
	Description           *string `json:"description"`
	Badge                 *string `json:"badge"`
	ActivityStart         *string `json:"activity_start"`
	ActivityEnd           *string `json:"activity_end"`
	RegistrationStart     *string `json:"registration_start"`
	RegistrationEnd       *string `json:"registration_end"`
	SelectionStart        *string `json:"selection_start"`
	SelectionEnd          *string `json:"selection_end"`
	MinimumLevel          *string `json:"minimum_level"`
	ActivityType          *string `json:"activity_type"`
	ActivityCategory      *string `json:"activity_category"`
	IsPublished           *string `json:"is_published"`
	IsRegistrationOpen    *bool   `json:"is_registration_open"`
	ClubPresent           bool    `json:"club_present"`
	ClubID                *string `json:"club_id"`
	TemplatePresent       bool    `json:"template_present"`
	CertificateTemplateID *string `json:"certificate_template_id"`
	AdditionalConfig      []byte  `json:"additional_config"`
	ID                    int32   `json:"id"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.Name,
		arg.Description,
		arg.Badge,
		arg.ActivityStart,
		arg.ActivityEnd,
		arg.RegistrationStart,
		arg.RegistrationEnd,
		arg.SelectionStart,
		arg.SelectionEnd,
		arg.MinimumLevel,
		arg.ActivityType,
		arg.ActivityCategory,
		arg.IsPublished,
		arg.IsRegistrationOpen,
		arg.ClubPresent,
		arg.ClubID,
		arg.TemplatePresent,
		arg.CertificateTemplateID,
		arg.AdditionalConfig,
		arg.ID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}
