// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_courses.sql

package dbgen

import (
	"context"
)

const activityCourseOptions = `-- name: ActivityCourseOptions :many
SELECT c.id, c.title, c.status,
 (SELECT count(*)::integer FROM course_lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL) AS lesson_count
FROM courses c WHERE c.title ILIKE '%' || $1::text || '%'
ORDER BY c.title, c.id LIMIT $3 OFFSET $2
`

type ActivityCourseOptionsParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ActivityCourseOptionsRow struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	Status      string `json:"status"`
	LessonCount int32  `json:"lesson_count"`
}

func (q *Queries) ActivityCourseOptions(ctx context.Context, arg ActivityCourseOptionsParams) ([]ActivityCourseOptionsRow, error) {
	rows, err := q.db.Query(ctx, activityCourseOptions, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityCourseOptionsRow{}
	for rows.Next() {
		var i ActivityCourseOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearActivityCourses = `-- name: ClearActivityCourses :exec
DELETE FROM activity_courses WHERE activity_id=$1
`

func (q *Queries) ClearActivityCourses(ctx context.Context, activityID int32) error {
	_, err := q.db.Exec(ctx, clearActivityCourses, activityID)
	return err
}

const countActivityCourseOptions = `-- name: CountActivityCourseOptions :one
SELECT count(*) FROM courses WHERE title ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountActivityCourseOptions(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityCourseOptions, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExistingActivityCourses = `-- name: CountExistingActivityCourses :one
SELECT count(*) FROM courses WHERE id=ANY($1::integer[])
`

func (q *Queries) CountExistingActivityCourses(ctx context.Context, courseIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingActivityCourses, courseIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivityCourses = `-- name: InsertActivityCourses :exec
INSERT INTO activity_courses(activity_id,course_id,position)
SELECT $1, id, ordinality::integer FROM unnest($2::integer[]) WITH ORDINALITY AS selected(id,ordinality)
`

type InsertActivityCoursesParams struct {
	ActivityID int32   `json:"activity_id"`
	CourseIds  []int32 `json:"course_ids"`
}

func (q *Queries) InsertActivityCourses(ctx context.Context, arg InsertActivityCoursesParams) error {
	_, err := q.db.Exec(ctx, insertActivityCourses, arg.ActivityID, arg.CourseIds)
	return err
}

const linkedActivityCourses = `-- name: LinkedActivityCourses :many
SELECT c.id, c.title, c.status,
 (SELECT count(*)::integer FROM course_lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL) AS lesson_count
FROM activity_courses ac JOIN courses c ON c.id=ac.course_id
WHERE ac.activity_id=$1 ORDER BY ac.position, ac.course_id
`

type LinkedActivityCoursesRow struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	Status      string `json:"status"`
	LessonCount int32  `json:"lesson_count"`
}

func (q *Queries) LinkedActivityCourses(ctx context.Context, activityID int32) ([]LinkedActivityCoursesRow, error) {
	rows, err := q.db.Query(ctx, linkedActivityCourses, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedActivityCoursesRow{}
	for rows.Next() {
		var i LinkedActivityCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActivityCourses = `-- name: LockActivityCourses :one
SELECT id FROM activities WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockActivityCourses(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockActivityCourses, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const registrationCourseProgress = `-- name: RegistrationCourseProgress :many
SELECT registration_id, course_id, status::text, total_lessons::integer, completed_lessons::integer
FROM activity_course_progress WHERE activity_id = $1::integer AND registration_id=ANY($2::integer[])
ORDER BY registration_id, position, course_id
`

type RegistrationCourseProgressParams struct {
	ActivityID      int32   `json:"activity_id"`
	RegistrationIds []int32 `json:"registration_ids"`
}

type RegistrationCourseProgressRow struct {
	RegistrationID   int32  `json:"registration_id"`
	CourseID         int32  `json:"course_id"`
	Status           string `json:"status"`
	TotalLessons     int32  `json:"total_lessons"`
	CompletedLessons int32  `json:"completed_lessons"`
}

func (q *Queries) RegistrationCourseProgress(ctx context.Context, arg RegistrationCourseProgressParams) ([]RegistrationCourseProgressRow, error) {
	rows, err := q.db.Query(ctx, registrationCourseProgress, arg.ActivityID, arg.RegistrationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationCourseProgressRow{}
	for rows.Next() {
		var i RegistrationCourseProgressRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.CourseID,
			&i.Status,
			&i.TotalLessons,
			&i.CompletedLessons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
