// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRBACLock = `-- name: AcquireRBACLock :exec
SELECT pg_advisory_xact_lock(7411,1)
`

func (q *Queries) AcquireRBACLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireRBACLock)
	return err
}

const adminIdentities = `-- name: AdminIdentities :many
SELECT provider,email,last_used_at,created_at FROM admin_auth_identities WHERE admin_user_id=$1 ORDER BY id
`

type AdminIdentitiesRow struct {
	Provider   string             `json:"provider"`
	Email      string             `json:"email"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminIdentities(ctx context.Context, adminUserID int32) ([]AdminIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, adminIdentities, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminIdentitiesRow{}
	for rows.Next() {
		var i AdminIdentitiesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Email,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSuperAdmins = `-- name: CountActiveSuperAdmins :one
SELECT count(*) FROM admin_users WHERE is_active=true AND role_code='super_admin'
`

func (q *Queries) CountActiveSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_users WHERE (email ILIKE $1::text OR display_name ILIKE $1::text)
AND ($2::text IS NULL OR COALESCE(role_code,'unassigned')=$2::text)
AND ($3::boolean IS NULL OR is_active=$3::boolean)
`

type CountAdminsParams struct {
	Search       string  `json:"search"`
	RoleFilter   *string `json:"role_filter"`
	ActiveFilter *bool   `json:"active_filter"`
}

func (q *Queries) CountAdmins(ctx context.Context, arg CountAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins, arg.Search, arg.RoleFilter, arg.ActiveFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users(email,normalized_email,password,display_name,is_active,role_code,created_at,updated_at)
VALUES ($1,$1,$2,$3,true,$4,now(),now()) RETURNING id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code
`

type CreateAdminParams struct {
	Email       string  `json:"email"`
	Password    *string `json:"password"`
	DisplayName *string `json:"display_name"`
	RoleCode    *string `json:"role_code"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.Password,
		arg.DisplayName,
		arg.RoleCode,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE (email ILIKE $1::text OR display_name ILIKE $1::text)
AND ($2::text IS NULL OR COALESCE(role_code,'unassigned')=$2::text)
AND ($3::boolean IS NULL OR is_active=$3::boolean)
ORDER BY created_at DESC LIMIT CAST($5::text AS bigint) OFFSET CAST($4::text AS bigint)
`

type ListAdminsParams struct {
	Search       string  `json:"search"`
	RoleFilter   *string `json:"role_filter"`
	ActiveFilter *bool   `json:"active_filter"`
	PageOffset   string  `json:"page_offset"`
	PageSize     *string `json:"page_size"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdmins,
		arg.Search,
		arg.RoleFilter,
		arg.ActiveFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.NormalizedEmail,
			&i.RoleCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdmin = `-- name: LockAdmin :one
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAdmin(ctx context.Context, id int32) (AdminUser, error) {
	row := q.db.QueryRow(ctx, lockAdmin, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const setAdminDisplayName = `-- name: SetAdminDisplayName :one
UPDATE admin_users SET display_name=$2,updated_at=now() WHERE id=$1 RETURNING id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code
`

type SetAdminDisplayNameParams struct {
	ID          int32   `json:"id"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) SetAdminDisplayName(ctx context.Context, arg SetAdminDisplayNameParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, setAdminDisplayName, arg.ID, arg.DisplayName)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const setAdminPassword = `-- name: SetAdminPassword :exec
UPDATE admin_users SET password=$2,updated_at=now() WHERE id=$1
`

type SetAdminPasswordParams struct {
	ID       int32   `json:"id"`
	Password *string `json:"password"`
}

func (q *Queries) SetAdminPassword(ctx context.Context, arg SetAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, setAdminPassword, arg.ID, arg.Password)
	return err
}

const updateAdminAccess = `-- name: UpdateAdminAccess :exec
UPDATE admin_users SET
role_code=CASE WHEN $1::boolean THEN $2::text ELSE role_code END,
is_active=CASE WHEN $3::boolean THEN $4::boolean ELSE is_active END,
updated_at=now() WHERE id = $5
`

type UpdateAdminAccessParams struct {
	RolePresent   bool    `json:"role_present"`
	RoleCode      *string `json:"role_code"`
	ActivePresent bool    `json:"active_present"`
	IsActive      bool    `json:"is_active"`
	ID            int32   `json:"id"`
}

func (q *Queries) UpdateAdminAccess(ctx context.Context, arg UpdateAdminAccessParams) error {
	_, err := q.db.Exec(ctx, updateAdminAccess,
		arg.RolePresent,
		arg.RoleCode,
		arg.ActivePresent,
		arg.IsActive,
		arg.ID,
	)
	return err
}
