// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminNotificationCount = `-- name: AdminNotificationCount :one
SELECT count(*)::integer FROM announcement_recipients r JOIN announcements a ON a.id=r.announcement_id WHERE r.admin_user_id=$1 AND a.state='published' AND r.read_at IS NULL
`

func (q *Queries) AdminNotificationCount(ctx context.Context, adminUserID *int32) (int32, error) {
	row := q.db.QueryRow(ctx, adminNotificationCount, adminUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminNotificationGet = `-- name: AdminNotificationGet :one
SELECT r.id,a.title,a.body,a.link_label,a.link_url,a.published_at,r.read_at FROM announcement_recipients r JOIN announcements a ON a.id=r.announcement_id WHERE r.id=$1 AND r.admin_user_id=$2 AND a.state='published'
`

type AdminNotificationGetParams struct {
	ID          int32  `json:"id"`
	AdminUserID *int32 `json:"admin_user_id"`
}

type AdminNotificationGetRow struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	LinkLabel   *string            `json:"link_label"`
	LinkUrl     *string            `json:"link_url"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) AdminNotificationGet(ctx context.Context, arg AdminNotificationGetParams) (AdminNotificationGetRow, error) {
	row := q.db.QueryRow(ctx, adminNotificationGet, arg.ID, arg.AdminUserID)
	var i AdminNotificationGetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.PublishedAt,
		&i.ReadAt,
	)
	return i, err
}

const adminNotificationList = `-- name: AdminNotificationList :many
SELECT r.id,a.title,a.body,a.link_label,a.link_url,a.published_at,r.read_at FROM announcement_recipients r JOIN announcements a ON a.id=r.announcement_id
WHERE r.admin_user_id=$1 AND a.state='published' AND (NOT $2::boolean OR r.read_at IS NULL)
AND ($3::integer=0 OR (a.published_at,r.id)<($4::timestamptz,$3::integer))
ORDER BY a.published_at DESC,r.id DESC LIMIT 21
`

type AdminNotificationListParams struct {
	AdminUserID *int32             `json:"admin_user_id"`
	Unread      bool               `json:"unread"`
	BeforeID    int32              `json:"before_id"`
	BeforeTime  pgtype.Timestamptz `json:"before_time"`
}

type AdminNotificationListRow struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	LinkLabel   *string            `json:"link_label"`
	LinkUrl     *string            `json:"link_url"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) AdminNotificationList(ctx context.Context, arg AdminNotificationListParams) ([]AdminNotificationListRow, error) {
	rows, err := q.db.Query(ctx, adminNotificationList,
		arg.AdminUserID,
		arg.Unread,
		arg.BeforeID,
		arg.BeforeTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminNotificationListRow{}
	for rows.Next() {
		var i AdminNotificationListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.LinkLabel,
			&i.LinkUrl,
			&i.PublishedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminNotificationRead = `-- name: AdminNotificationRead :execrows
UPDATE announcement_recipients r SET read_at=COALESCE(read_at,clock_timestamp()) FROM announcements a WHERE a.id=r.announcement_id AND a.state='published' AND r.id=$1 AND r.admin_user_id=$2
`

type AdminNotificationReadParams struct {
	ID          int32  `json:"id"`
	AdminUserID *int32 `json:"admin_user_id"`
}

func (q *Queries) AdminNotificationRead(ctx context.Context, arg AdminNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminNotificationRead, arg.ID, arg.AdminUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminNotificationReadAll = `-- name: AdminNotificationReadAll :exec
UPDATE announcement_recipients r SET read_at=clock_timestamp() FROM announcements a WHERE a.id=r.announcement_id AND a.state='published' AND r.admin_user_id=$1 AND r.read_at IS NULL AND a.published_at<=$2::timestamptz
`

type AdminNotificationReadAllParams struct {
	AdminUserID *int32             `json:"admin_user_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
}

func (q *Queries) AdminNotificationReadAll(ctx context.Context, arg AdminNotificationReadAllParams) error {
	_, err := q.db.Exec(ctx, adminNotificationReadAll, arg.AdminUserID, arg.Cutoff)
	return err
}

const announcementClock = `-- name: AnnouncementClock :one
WITH publication_lock AS MATERIALIZED (SELECT pg_advisory_xact_lock(1790045423))
SELECT clock_timestamp()::timestamptz FROM publication_lock
`

func (q *Queries) AnnouncementClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, announcementClock)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const announcementCreate = `-- name: AnnouncementCreate :one
INSERT INTO announcements(title,body,link_label,link_url,audience,author_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count
`

type AnnouncementCreateParams struct {
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	LinkLabel *string `json:"link_label"`
	LinkUrl   *string `json:"link_url"`
	Audience  []byte  `json:"audience"`
	AuthorID  *int32  `json:"author_id"`
}

func (q *Queries) AnnouncementCreate(ctx context.Context, arg AnnouncementCreateParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementCreate,
		arg.Title,
		arg.Body,
		arg.LinkLabel,
		arg.LinkUrl,
		arg.Audience,
		arg.AuthorID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}

const announcementDelete = `-- name: AnnouncementDelete :execrows
DELETE FROM announcements WHERE id=$1 AND state='draft' AND version=$2
`

type AnnouncementDeleteParams struct {
	ID      int32 `json:"id"`
	Version int32 `json:"version"`
}

func (q *Queries) AnnouncementDelete(ctx context.Context, arg AnnouncementDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, announcementDelete, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const announcementGet = `-- name: AnnouncementGet :one
SELECT id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count FROM announcements WHERE id=$1
`

func (q *Queries) AnnouncementGet(ctx context.Context, id int32) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementGet, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}

const announcementInsertAdmins = `-- name: AnnouncementInsertAdmins :exec
INSERT INTO announcement_recipients(announcement_id,admin_user_id) SELECT $1,unnest($2::integer[]) ON CONFLICT DO NOTHING
`

type AnnouncementInsertAdminsParams struct {
	AnnouncementID int32   `json:"announcement_id"`
	Ids            []int32 `json:"ids"`
}

func (q *Queries) AnnouncementInsertAdmins(ctx context.Context, arg AnnouncementInsertAdminsParams) error {
	_, err := q.db.Exec(ctx, announcementInsertAdmins, arg.AnnouncementID, arg.Ids)
	return err
}

const announcementInsertMembers = `-- name: AnnouncementInsertMembers :exec
INSERT INTO announcement_recipients(announcement_id,public_user_id) SELECT $1,unnest($2::integer[]) ON CONFLICT DO NOTHING
`

type AnnouncementInsertMembersParams struct {
	AnnouncementID int32   `json:"announcement_id"`
	Ids            []int32 `json:"ids"`
}

func (q *Queries) AnnouncementInsertMembers(ctx context.Context, arg AnnouncementInsertMembersParams) error {
	_, err := q.db.Exec(ctx, announcementInsertMembers, arg.AnnouncementID, arg.Ids)
	return err
}

const announcementList = `-- name: AnnouncementList :many
SELECT id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count FROM announcements WHERE ($1::integer=0 OR id<$1) ORDER BY id DESC LIMIT 21
`

func (q *Queries) AnnouncementList(ctx context.Context, beforeID int32) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, announcementList, beforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.LinkLabel,
			&i.LinkUrl,
			&i.Audience,
			&i.State,
			&i.Version,
			&i.AuthorID,
			&i.PublisherID,
			&i.PublishedAt,
			&i.WithdrawnAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipientCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const announcementLock = `-- name: AnnouncementLock :one
SELECT id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count FROM announcements WHERE id=$1 FOR UPDATE
`

func (q *Queries) AnnouncementLock(ctx context.Context, id int32) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementLock, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}

const announcementOptions = `-- name: AnnouncementOptions :many
SELECT id, label, kind FROM (
SELECT id,(COALESCE(display_name,email)||' · '||email)::text AS label,'admin'::text AS kind FROM admin_users
UNION ALL SELECT u.id,(COALESCE(p.name,u.email,u.member_id,'Anggota')||' · '||COALESCE(u.member_id,u.email,'#'||u.id))::text,'member'::text FROM public_users u LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=u.id ORDER BY id LIMIT 1) p ON true
UNION ALL SELECT id,name::text,'activity'::text FROM activities
UNION ALL SELECT id,name::text,'club'::text FROM clubs
) choices WHERE kind=$1::text AND (label ILIKE '%'||$2::text||'%' OR id=ANY($3::integer[]))
ORDER BY (id=ANY($3::integer[])) DESC,label,id LIMIT (50+cardinality($3::integer[]))
`

type AnnouncementOptionsParams struct {
	Kind     string  `json:"kind"`
	Search   string  `json:"search"`
	Selected []int32 `json:"selected"`
}

type AnnouncementOptionsRow struct {
	ID    int32  `json:"id"`
	Label string `json:"label"`
	Kind  string `json:"kind"`
}

func (q *Queries) AnnouncementOptions(ctx context.Context, arg AnnouncementOptionsParams) ([]AnnouncementOptionsRow, error) {
	rows, err := q.db.Query(ctx, announcementOptions, arg.Kind, arg.Search, arg.Selected)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementOptionsRow{}
	for rows.Next() {
		var i AnnouncementOptionsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const announcementPublish = `-- name: AnnouncementPublish :one
UPDATE announcements SET state='published',publisher_id=$2,published_at=clock_timestamp(),recipient_count=$3,version=version+1,updated_at=clock_timestamp() WHERE id=$1 RETURNING id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count
`

type AnnouncementPublishParams struct {
	ID             int32  `json:"id"`
	PublisherID    *int32 `json:"publisher_id"`
	RecipientCount int32  `json:"recipient_count"`
}

func (q *Queries) AnnouncementPublish(ctx context.Context, arg AnnouncementPublishParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementPublish, arg.ID, arg.PublisherID, arg.RecipientCount)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}

const announcementRecipients = `-- name: AnnouncementRecipients :many
WITH members AS (
 SELECT u.id, u.account_status='active' AS eligible FROM public_users u
 WHERE $1::boolean OR u.id=ANY($2::integer[])
 OR EXISTS (SELECT 1 FROM activity_registrations r WHERE r.user_id=u.id AND r.activity_id=ANY($3::integer[]) AND (cardinality($4::text[])=0 OR r.status=ANY($4::text[])))
 OR EXISTS (SELECT 1 FROM club_registrations r WHERE r.member_id=u.id AND r.club_id=ANY($5::integer[]) AND r.status=ANY($6::text[]))
), admins AS (
 SELECT u.id, u.is_active AS eligible FROM admin_users u
 WHERE $7::boolean OR u.id=ANY($8::integer[])
 OR u.role_code=ANY($9::text[]) OR u.additional_role_codes && $9::text[]
)
SELECT id,eligible,'member'::text AS kind FROM members UNION ALL SELECT id,eligible,'admin'::text AS kind FROM admins
`

type AnnouncementRecipientsParams struct {
	AllMembers       bool     `json:"all_members"`
	MemberIds        []int32  `json:"member_ids"`
	ActivityIds      []int32  `json:"activity_ids"`
	ActivityStatuses []string `json:"activity_statuses"`
	ClubIds          []int32  `json:"club_ids"`
	ClubStatuses     []string `json:"club_statuses"`
	AllAdmins        bool     `json:"all_admins"`
	AdminIds         []int32  `json:"admin_ids"`
	RoleCodes        []string `json:"role_codes"`
}

type AnnouncementRecipientsRow struct {
	ID       int32  `json:"id"`
	Eligible bool   `json:"eligible"`
	Kind     string `json:"kind"`
}

func (q *Queries) AnnouncementRecipients(ctx context.Context, arg AnnouncementRecipientsParams) ([]AnnouncementRecipientsRow, error) {
	rows, err := q.db.Query(ctx, announcementRecipients,
		arg.AllMembers,
		arg.MemberIds,
		arg.ActivityIds,
		arg.ActivityStatuses,
		arg.ClubIds,
		arg.ClubStatuses,
		arg.AllAdmins,
		arg.AdminIds,
		arg.RoleCodes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementRecipientsRow{}
	for rows.Next() {
		var i AnnouncementRecipientsRow
		if err := rows.Scan(&i.ID, &i.Eligible, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const announcementUpdate = `-- name: AnnouncementUpdate :one
UPDATE announcements SET title=$2,body=$3,link_label=$4,link_url=$5,audience=$6,version=version+1,updated_at=clock_timestamp() WHERE id=$1 AND version=$7 AND state='draft' RETURNING id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count
`

type AnnouncementUpdateParams struct {
	ID        int32   `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	LinkLabel *string `json:"link_label"`
	LinkUrl   *string `json:"link_url"`
	Audience  []byte  `json:"audience"`
	Version   int32   `json:"version"`
}

func (q *Queries) AnnouncementUpdate(ctx context.Context, arg AnnouncementUpdateParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementUpdate,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.LinkLabel,
		arg.LinkUrl,
		arg.Audience,
		arg.Version,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}

const announcementWithdraw = `-- name: AnnouncementWithdraw :one
UPDATE announcements SET state='withdrawn',withdrawn_at=clock_timestamp(),updated_at=clock_timestamp(),version=version+1 WHERE id=$1 AND state='published' RETURNING id, title, body, link_label, link_url, audience, state, version, author_id, publisher_id, published_at, withdrawn_at, created_at, updated_at, recipient_count
`

func (q *Queries) AnnouncementWithdraw(ctx context.Context, id int32) (Announcement, error) {
	row := q.db.QueryRow(ctx, announcementWithdraw, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LinkLabel,
		&i.LinkUrl,
		&i.Audience,
		&i.State,
		&i.Version,
		&i.AuthorID,
		&i.PublisherID,
		&i.PublishedAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipientCount,
	)
	return i, err
}
