// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminIdentityProviders = `-- name: AdminIdentityProviders :many
SELECT provider FROM admin_auth_identities WHERE admin_user_id = $1 ORDER BY id
`

func (q *Queries) AdminIdentityProviders(ctx context.Context, adminUserID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, adminIdentityProviders, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGoogleAdmin = `-- name: CreateGoogleAdmin :one
INSERT INTO admin_users (email, normalized_email, display_name, is_active, created_at, updated_at)
VALUES ($1, $1, $2, true, now(), now()) RETURNING id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code
`

type CreateGoogleAdminParams struct {
	Email       string  `json:"email"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) CreateGoogleAdmin(ctx context.Context, arg CreateGoogleAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createGoogleAdmin, arg.Email, arg.DisplayName)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const createGoogleIdentity = `-- name: CreateGoogleIdentity :exec
INSERT INTO admin_auth_identities (admin_user_id, provider, provider_subject, email, last_used_at, created_at, updated_at)
VALUES ($1, 'google', $2, $3, now(), now(), now())
`

type CreateGoogleIdentityParams struct {
	AdminUserID     int32  `json:"admin_user_id"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
}

func (q *Queries) CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, createGoogleIdentity, arg.AdminUserID, arg.ProviderSubject, arg.Email)
	return err
}

const createRefresh = `-- name: CreateRefresh :one
INSERT INTO admin_refresh_tokens
(family_id, admin_user_id, token_hash, parent_token_id, user_agent, ip_address, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now()) RETURNING id, family_id, admin_user_id, token_hash, parent_token_id, replaced_by_token_id, user_agent, ip_address, expires_at, last_used_at, revoked_at, revocation_reason, created_at
`

type CreateRefreshParams struct {
	FamilyID      pgtype.UUID        `json:"family_id"`
	AdminUserID   int32              `json:"admin_user_id"`
	TokenHash     string             `json:"token_hash"`
	ParentTokenID *int32             `json:"parent_token_id"`
	UserAgent     *string            `json:"user_agent"`
	IpAddress     *string            `json:"ip_address"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefresh(ctx context.Context, arg CreateRefreshParams) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefresh,
		arg.FamilyID,
		arg.AdminUserID,
		arg.TokenHash,
		arg.ParentTokenID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AdminUserID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.ReplacedByTokenID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const findAdminByEmail = `-- name: FindAdminByEmail :one
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE normalized_email = $1
`

func (q *Queries) FindAdminByEmail(ctx context.Context, normalizedEmail string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByEmail, normalizedEmail)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const findAdminByID = `-- name: FindAdminByID :one
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE id = $1
`

func (q *Queries) FindAdminByID(ctx context.Context, id int32) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const findGoogleIdentity = `-- name: FindGoogleIdentity :one
SELECT id, admin_user_id, provider, provider_subject, email, last_used_at, created_at, updated_at FROM admin_auth_identities WHERE provider = 'google' AND provider_subject = $1
`

func (q *Queries) FindGoogleIdentity(ctx context.Context, providerSubject string) (AdminAuthIdentity, error) {
	row := q.db.QueryRow(ctx, findGoogleIdentity, providerSubject)
	var i AdminAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRefreshForUpdate = `-- name: FindRefreshForUpdate :one
SELECT id, family_id, admin_user_id, token_hash, parent_token_id, replaced_by_token_id, user_agent, ip_address, expires_at, last_used_at, revoked_at, revocation_reason, created_at FROM admin_refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) FindRefreshForUpdate(ctx context.Context, tokenHash string) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshForUpdate, tokenHash)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AdminUserID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.ReplacedByTokenID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAdminSessions = `-- name: RevokeAdminSessions :exec
UPDATE admin_refresh_tokens SET revoked_at = now(), revocation_reason = $2
WHERE admin_user_id = $1 AND revoked_at IS NULL
`

type RevokeAdminSessionsParams struct {
	AdminUserID      int32   `json:"admin_user_id"`
	RevocationReason *string `json:"revocation_reason"`
}

func (q *Queries) RevokeAdminSessions(ctx context.Context, arg RevokeAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSessions, arg.AdminUserID, arg.RevocationReason)
	return err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE admin_refresh_tokens SET revoked_at = now(), revocation_reason = 'refresh_token_reuse'
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeFamily, familyID)
	return err
}

const revokeRefresh = `-- name: RevokeRefresh :exec
UPDATE admin_refresh_tokens SET revoked_at = now(), revocation_reason = $2
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeRefreshParams struct {
	TokenHash        string  `json:"token_hash"`
	RevocationReason *string `json:"revocation_reason"`
}

func (q *Queries) RevokeRefresh(ctx context.Context, arg RevokeRefreshParams) error {
	_, err := q.db.Exec(ctx, revokeRefresh, arg.TokenHash, arg.RevocationReason)
	return err
}

const rotateRefresh = `-- name: RotateRefresh :exec
UPDATE admin_refresh_tokens SET last_used_at = now(), revoked_at = now(),
revocation_reason = 'rotated', replaced_by_token_id = $2 WHERE id = $1
`

type RotateRefreshParams struct {
	ID                int32  `json:"id"`
	ReplacedByTokenID *int32 `json:"replaced_by_token_id"`
}

func (q *Queries) RotateRefresh(ctx context.Context, arg RotateRefreshParams) error {
	_, err := q.db.Exec(ctx, rotateRefresh, arg.ID, arg.ReplacedByTokenID)
	return err
}

const touchIdentity = `-- name: TouchIdentity :exec
UPDATE admin_auth_identities SET email = $2, last_used_at = now(), updated_at = now() WHERE id = $1
`

type TouchIdentityParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) TouchIdentity(ctx context.Context, arg TouchIdentityParams) error {
	_, err := q.db.Exec(ctx, touchIdentity, arg.ID, arg.Email)
	return err
}
