// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (title, description, location, starts_at, ends_at, all_day, activity_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type CreateCalendarEventParams struct {
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	AllDay      bool               `json:"all_day"`
	ActivityID  *int32             `json:"activity_id"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.ActivityID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :execrows
DELETE FROM calendar_events WHERE id=$1
`

func (q *Queries) DeleteCalendarEvent(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalendarEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT e.id, e.title, e.description, e.location, e.starts_at, e.ends_at, e.all_day, e.activity_id, e.created_at, e.updated_at, a.name AS activity_name, a.slug AS activity_slug, a.is_published AS activity_published
FROM calendar_events e LEFT JOIN activities a ON a.id = e.activity_id WHERE e.id = $1
`

type GetCalendarEventRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Location          *string            `json:"location"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	AllDay            bool               `json:"all_day"`
	ActivityID        *int32             `json:"activity_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ActivityName      *string            `json:"activity_name"`
	ActivitySlug      *string            `json:"activity_slug"`
	ActivityPublished *bool              `json:"activity_published"`
}

func (q *Queries) GetCalendarEvent(ctx context.Context, id int32) (GetCalendarEventRow, error) {
	row := q.db.QueryRow(ctx, getCalendarEvent, id)
	var i GetCalendarEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.ActivityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivityName,
		&i.ActivitySlug,
		&i.ActivityPublished,
	)
	return i, err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT e.id, e.title, e.description, e.location, e.starts_at, e.ends_at, e.all_day, e.activity_id, e.created_at, e.updated_at, a.name AS activity_name, a.slug AS activity_slug, a.is_published AS activity_published
FROM calendar_events e LEFT JOIN activities a ON a.id = e.activity_id
WHERE e.starts_at < $1::timestamptz AND e.ends_at > $2::timestamptz
ORDER BY e.starts_at, e.id
`

type ListCalendarEventsParams struct {
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
}

type ListCalendarEventsRow struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Location          *string            `json:"location"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	AllDay            bool               `json:"all_day"`
	ActivityID        *int32             `json:"activity_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ActivityName      *string            `json:"activity_name"`
	ActivitySlug      *string            `json:"activity_slug"`
	ActivityPublished *bool              `json:"activity_published"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]ListCalendarEventsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarEventsRow{}
	for rows.Next() {
		var i ListCalendarEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.ActivityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivityName,
			&i.ActivitySlug,
			&i.ActivityPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :execrows
UPDATE calendar_events SET title=$2, description=$3, location=$4, starts_at=$5,
ends_at=$6, all_day=$7, activity_id=$8, updated_at=now() WHERE id=$1
`

type UpdateCalendarEventParams struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	AllDay      bool               `json:"all_day"`
	ActivityID  *int32             `json:"activity_id"`
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCalendarEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.ActivityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
