// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIssuedCertificate = `-- name: InsertIssuedCertificate :one
INSERT INTO issued_certificates (
 certificate_code, registration_id, activity_id, user_id, template_id,
 template_snapshot, participant_snapshot, activity_snapshot, snapshot_version,
 template_version, issued_by, issued_at, created_at, updated_at
) VALUES (
 $1, $2, $3, $4, $5,
 $6, $7, $8, 1,
 $9, $10, $11, $11, $11
) ON CONFLICT (registration_id) DO NOTHING RETURNING id
`

type InsertIssuedCertificateParams struct {
	Code                string             `json:"code"`
	RegistrationID      int32              `json:"registration_id"`
	ActivityID          int32              `json:"activity_id"`
	UserID              *int32             `json:"user_id"`
	TemplateID          int32              `json:"template_id"`
	TemplateSnapshot    []byte             `json:"template_snapshot"`
	ParticipantSnapshot []byte             `json:"participant_snapshot"`
	ActivitySnapshot    []byte             `json:"activity_snapshot"`
	TemplateVersion     int32              `json:"template_version"`
	IssuedBy            *int32             `json:"issued_by"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) InsertIssuedCertificate(ctx context.Context, arg InsertIssuedCertificateParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertIssuedCertificate,
		arg.Code,
		arg.RegistrationID,
		arg.ActivityID,
		arg.UserID,
		arg.TemplateID,
		arg.TemplateSnapshot,
		arg.ParticipantSnapshot,
		arg.ActivitySnapshot,
		arg.TemplateVersion,
		arg.IssuedBy,
		arg.IssuedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const issuedByCode = `-- name: IssuedByCode :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE certificate_code=$1
`

func (q *Queries) IssuedByCode(ctx context.Context, certificateCode string) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, issuedByCode, certificateCode)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const issuedByID = `-- name: IssuedByID :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE id=$1
`

func (q *Queries) IssuedByID(ctx context.Context, id int32) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, issuedByID, id)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const issuedByRegistration = `-- name: IssuedByRegistration :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE registration_id=$1
`

func (q *Queries) IssuedByRegistration(ctx context.Context, registrationID int32) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, issuedByRegistration, registrationID)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const lockIssued = `-- name: LockIssued :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockIssued(ctx context.Context, id int32) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, lockIssued, id)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const revokeIssued = `-- name: RevokeIssued :one
UPDATE issued_certificates SET revoked_at=$2,revoked_reason=$3,revoked_by=$4,updated_at=$2 WHERE id=$1 RETURNING approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by
`

type RevokeIssuedParams struct {
	ID            int32              `json:"id"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason *string            `json:"revoked_reason"`
	RevokedBy     *int32             `json:"revoked_by"`
}

func (q *Queries) RevokeIssued(ctx context.Context, arg RevokeIssuedParams) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, revokeIssued,
		arg.ID,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.RevokedBy,
	)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}
