// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_workflow.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const certificateActivityByIdentifier = `-- name: CertificateActivityByIdentifier :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CertificateActivityByIdentifier(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, certificateActivityByIdentifier, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const certificateBulkRegistrations = `-- name: CertificateBulkRegistrations :many
SELECT id, user_id, activity_id, status, questionnaire_answer, scoring_data, created_at, updated_at, guest_data FROM activity_registrations WHERE activity_id=CAST(CAST($1 AS text) AS integer) AND status= $2::text
`

type CertificateBulkRegistrationsParams struct {
	ActivityID string `json:"activity_id"`
	Status     string `json:"status"`
}

func (q *Queries) CertificateBulkRegistrations(ctx context.Context, arg CertificateBulkRegistrationsParams) ([]ActivityRegistration, error) {
	rows, err := q.db.Query(ctx, certificateBulkRegistrations, arg.ActivityID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityRegistration{}
	for rows.Next() {
		var i ActivityRegistration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityID,
			&i.Status,
			&i.QuestionnaireAnswer,
			&i.ScoringData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certificateGuestUniversity = `-- name: CertificateGuestUniversity :one
SELECT name FROM universities WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CertificateGuestUniversity(ctx context.Context, identifier string) (string, error) {
	row := q.db.QueryRow(ctx, certificateGuestUniversity, identifier)
	var name string
	err := row.Scan(&name)
	return name, err
}

const certificateParticipantMember = `-- name: CertificateParticipantMember :one
SELECT COALESCE(u.email,'')::text AS email,COALESCE(p.name,'')::text AS name,COALESCE(p.gender,'')::text AS gender,COALESCE(v.name,'')::text AS university
FROM public_users u LEFT JOIN LATERAL (SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE user_id=u.id ORDER BY id LIMIT 1) p ON true LEFT JOIN universities v ON v.id=p.university_id WHERE u.id=$1
`

type CertificateParticipantMemberRow struct {
	Email      string `json:"email"`
	Name       string `json:"name"`
	Gender     string `json:"gender"`
	University string `json:"university"`
}

func (q *Queries) CertificateParticipantMember(ctx context.Context, id int32) (CertificateParticipantMemberRow, error) {
	row := q.db.QueryRow(ctx, certificateParticipantMember, id)
	var i CertificateParticipantMemberRow
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Gender,
		&i.University,
	)
	return i, err
}

const certificatePreparationRecipients = `-- name: CertificatePreparationRecipients :many
SELECT r.id AS registration_id,(CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)::text AS state FROM activity_registrations r LEFT JOIN issued_certificates c ON c.registration_id=r.id WHERE r.activity_id=CAST(CAST($1 AS text) AS integer) AND (NOT $2::boolean OR r.id=ANY(CAST(CAST($3 AS text[]) AS integer[]))) ORDER BY r.id
`

type CertificatePreparationRecipientsParams struct {
	ActivityID      string   `json:"activity_id"`
	FilterSelected  bool     `json:"filter_selected"`
	RegistrationIds []string `json:"registration_ids"`
}

type CertificatePreparationRecipientsRow struct {
	RegistrationID int32  `json:"registration_id"`
	State          string `json:"state"`
}

func (q *Queries) CertificatePreparationRecipients(ctx context.Context, arg CertificatePreparationRecipientsParams) ([]CertificatePreparationRecipientsRow, error) {
	rows, err := q.db.Query(ctx, certificatePreparationRecipients, arg.ActivityID, arg.FilterSelected, arg.RegistrationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificatePreparationRecipientsRow{}
	for rows.Next() {
		var i CertificatePreparationRecipientsRow
		if err := rows.Scan(&i.RegistrationID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certificateRecipientCounts = `-- name: CertificateRecipientCounts :many
SELECT (CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)::text AS state,count(*) AS total FROM activity_registrations r LEFT JOIN issued_certificates c ON c.registration_id=r.id WHERE r.activity_id=CAST(CAST($1 AS text) AS integer) GROUP BY (CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)
`

type CertificateRecipientCountsRow struct {
	State string `json:"state"`
	Total int64  `json:"total"`
}

func (q *Queries) CertificateRecipientCounts(ctx context.Context, activityID string) ([]CertificateRecipientCountsRow, error) {
	rows, err := q.db.Query(ctx, certificateRecipientCounts, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateRecipientCountsRow{}
	for rows.Next() {
		var i CertificateRecipientCountsRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certificateRecipientNames = `-- name: CertificateRecipientNames :many
SELECT r.id,(COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta'))::text AS name FROM activity_registrations r WHERE r.id=ANY(CAST(CAST($1 AS text[]) AS integer[]))
`

type CertificateRecipientNamesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CertificateRecipientNames(ctx context.Context, registrationIds []string) ([]CertificateRecipientNamesRow, error) {
	rows, err := q.db.Query(ctx, certificateRecipientNames, registrationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateRecipientNamesRow{}
	for rows.Next() {
		var i CertificateRecipientNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certificateRegistrationByIdentifier = `-- name: CertificateRegistrationByIdentifier :one
SELECT id, user_id, activity_id, status, questionnaire_answer, scoring_data, created_at, updated_at, guest_data FROM activity_registrations WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CertificateRegistrationByIdentifier(ctx context.Context, identifier string) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, certificateRegistrationByIdentifier, identifier)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Status,
		&i.QuestionnaireAnswer,
		&i.ScoringData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestData,
	)
	return i, err
}

const countCertificateRecipients = `-- name: CountCertificateRecipients :one
SELECT count(*) FROM activity_registrations r LEFT JOIN issued_certificates c ON c.registration_id=r.id WHERE r.activity_id=CAST(CAST($1 AS text) AS integer) AND ($2::text IS NULL OR (COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta')) ILIKE '%'||$2::text||'%') AND ($3::text IS NULL OR (CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)=$3::text) AND (NOT $4::boolean OR r.id=ANY(CAST(CAST($5 AS text[]) AS integer[])))
`

type CountCertificateRecipientsParams struct {
	ActivityID      string   `json:"activity_id"`
	Search          *string  `json:"search"`
	State           *string  `json:"state"`
	FilterSelected  bool     `json:"filter_selected"`
	RegistrationIds []string `json:"registration_ids"`
}

func (q *Queries) CountCertificateRecipients(ctx context.Context, arg CountCertificateRecipientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificateRecipients,
		arg.ActivityID,
		arg.Search,
		arg.State,
		arg.FilterSelected,
		arg.RegistrationIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuedCertificateList = `-- name: CountIssuedCertificateList :one
SELECT count(*) FROM issued_certificates c WHERE ($1::text IS NULL OR c.activity_id=CAST(CAST($1 AS text) AS integer)) AND (NOT $2::boolean OR c.registration_id=ANY(CAST(CAST($3 AS text[]) AS integer[])))
`

type CountIssuedCertificateListParams struct {
	ActivityID      *string  `json:"activity_id"`
	FilterSelected  bool     `json:"filter_selected"`
	RegistrationIds []string `json:"registration_ids"`
}

func (q *Queries) CountIssuedCertificateList(ctx context.Context, arg CountIssuedCertificateListParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuedCertificateList, arg.ActivityID, arg.FilterSelected, arg.RegistrationIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const issuedCertificateByIdentifier = `-- name: IssuedCertificateByIdentifier :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) IssuedCertificateByIdentifier(ctx context.Context, identifier string) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, issuedCertificateByIdentifier, identifier)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const issuedCertificateByRegistrationIdentifier = `-- name: IssuedCertificateByRegistrationIdentifier :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE registration_id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) IssuedCertificateByRegistrationIdentifier(ctx context.Context, identifier string) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, issuedCertificateByRegistrationIdentifier, identifier)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}

const listCertificateRecipients = `-- name: ListCertificateRecipients :many
SELECT r.id AS registration_id,r.created_at,r.status,c.id AS certificate_id,c.certificate_code,(COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta'))::text AS name,(CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)::text AS state FROM activity_registrations r LEFT JOIN issued_certificates c ON c.registration_id=r.id WHERE r.activity_id=CAST(CAST($1 AS text) AS integer) AND ($2::text IS NULL OR (COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta')) ILIKE '%'||$2::text||'%') AND ($3::text IS NULL OR (CASE WHEN c.revoked_at IS NOT NULL THEN 'issued_revoked' WHEN c.id IS NOT NULL THEN 'issued_active' WHEN r.status='LULUS KEGIATAN' THEN 'eligible_not_issued' ELSE 'not_eligible' END)=$3::text) AND (NOT $4::boolean OR r.id=ANY(CAST(CAST($5 AS text[]) AS integer[])))
ORDER BY CASE WHEN $6::boolean THEN r.created_at END ASC NULLS LAST,CASE WHEN NOT $6::boolean THEN r.created_at END DESC NULLS LAST,CASE WHEN $6::boolean THEN r.id END ASC,CASE WHEN NOT $6::boolean THEN r.id END DESC LIMIT CAST($8::text AS bigint) OFFSET CAST($7::text AS bigint)
`

type ListCertificateRecipientsParams struct {
	ActivityID      string   `json:"activity_id"`
	Search          *string  `json:"search"`
	State           *string  `json:"state"`
	FilterSelected  bool     `json:"filter_selected"`
	RegistrationIds []string `json:"registration_ids"`
	Ascending       bool     `json:"ascending"`
	PageOffset      string   `json:"page_offset"`
	PageSize        *string  `json:"page_size"`
}

type ListCertificateRecipientsRow struct {
	RegistrationID  int32              `json:"registration_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Status          *string            `json:"status"`
	CertificateID   *int32             `json:"certificate_id"`
	CertificateCode *string            `json:"certificate_code"`
	Name            string             `json:"name"`
	State           string             `json:"state"`
}

func (q *Queries) ListCertificateRecipients(ctx context.Context, arg ListCertificateRecipientsParams) ([]ListCertificateRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateRecipients,
		arg.ActivityID,
		arg.Search,
		arg.State,
		arg.FilterSelected,
		arg.RegistrationIds,
		arg.Ascending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateRecipientsRow{}
	for rows.Next() {
		var i ListCertificateRecipientsRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.CreatedAt,
			&i.Status,
			&i.CertificateID,
			&i.CertificateCode,
			&i.Name,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuedCertificates = `-- name: ListIssuedCertificates :many
SELECT c.id,c.certificate_code,c.registration_id,c.activity_id,c.participant_snapshot,COALESCE(c.template_snapshot->>'name','')::text AS template_name,c.issued_at,c.issued_by,issuer.display_name AS issued_by_name,c.revoked_at,c.revoked_reason,c.revoked_by,revoker.display_name AS revoked_by_name,CASE WHEN c.revoked_at IS NULL THEN 'issued_active' ELSE 'issued_revoked' END::text AS state
FROM issued_certificates c LEFT JOIN admin_users issuer ON issuer.id=c.issued_by LEFT JOIN admin_users revoker ON revoker.id=c.revoked_by WHERE ($1::text IS NULL OR c.activity_id=CAST(CAST($1 AS text) AS integer)) AND (NOT $2::boolean OR c.registration_id=ANY(CAST(CAST($3 AS text[]) AS integer[]))) ORDER BY c.issued_at DESC LIMIT CAST($5::text AS bigint) OFFSET CAST($4::text AS bigint)
`

type ListIssuedCertificatesParams struct {
	ActivityID      *string  `json:"activity_id"`
	FilterSelected  bool     `json:"filter_selected"`
	RegistrationIds []string `json:"registration_ids"`
	PageOffset      string   `json:"page_offset"`
	PageSize        *string  `json:"page_size"`
}

type ListIssuedCertificatesRow struct {
	ID                  int32              `json:"id"`
	CertificateCode     string             `json:"certificate_code"`
	RegistrationID      int32              `json:"registration_id"`
	ActivityID          int32              `json:"activity_id"`
	ParticipantSnapshot []byte             `json:"participant_snapshot"`
	TemplateName        string             `json:"template_name"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	IssuedBy            *int32             `json:"issued_by"`
	IssuedByName        *string            `json:"issued_by_name"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason       *string            `json:"revoked_reason"`
	RevokedBy           *int32             `json:"revoked_by"`
	RevokedByName       *string            `json:"revoked_by_name"`
	State               string             `json:"state"`
}

func (q *Queries) ListIssuedCertificates(ctx context.Context, arg ListIssuedCertificatesParams) ([]ListIssuedCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listIssuedCertificates,
		arg.ActivityID,
		arg.FilterSelected,
		arg.RegistrationIds,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuedCertificatesRow{}
	for rows.Next() {
		var i ListIssuedCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.CertificateCode,
			&i.RegistrationID,
			&i.ActivityID,
			&i.ParticipantSnapshot,
			&i.TemplateName,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.IssuedByName,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.RevokedBy,
			&i.RevokedByName,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCertificateActivityByIdentifier = `-- name: LockCertificateActivityByIdentifier :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockCertificateActivityByIdentifier(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, lockCertificateActivityByIdentifier, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const lockCertificateRegistrationByIdentifier = `-- name: LockCertificateRegistrationByIdentifier :one
SELECT id, user_id, activity_id, status, questionnaire_answer, scoring_data, created_at, updated_at, guest_data FROM activity_registrations WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockCertificateRegistrationByIdentifier(ctx context.Context, identifier string) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, lockCertificateRegistrationByIdentifier, identifier)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Status,
		&i.QuestionnaireAnswer,
		&i.ScoringData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestData,
	)
	return i, err
}

const lockIssuedCertificateByIdentifier = `-- name: LockIssuedCertificateByIdentifier :one
SELECT approval_snapshot, id, certificate_code, registration_id, activity_id, user_id, template_id, template_snapshot, participant_snapshot, issued_by, issued_at, revoked_at, revoked_reason, created_at, updated_at, activity_snapshot, snapshot_version, template_version, revoked_by FROM issued_certificates WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockIssuedCertificateByIdentifier(ctx context.Context, identifier string) (IssuedCertificate, error) {
	row := q.db.QueryRow(ctx, lockIssuedCertificateByIdentifier, identifier)
	var i IssuedCertificate
	err := row.Scan(
		&i.ApprovalSnapshot,
		&i.ID,
		&i.CertificateCode,
		&i.RegistrationID,
		&i.ActivityID,
		&i.UserID,
		&i.TemplateID,
		&i.TemplateSnapshot,
		&i.ParticipantSnapshot,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivitySnapshot,
		&i.SnapshotVersion,
		&i.TemplateVersion,
		&i.RevokedBy,
	)
	return i, err
}
