// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_approvals.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const certificateApprovalByID = `-- name: CertificateApprovalByID :one
SELECT id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, status, decided_by, decided_at, reason, certificate_id, created_at, updated_at FROM certificate_approvals WHERE id=$1
`

func (q *Queries) CertificateApprovalByID(ctx context.Context, id int32) (CertificateApproval, error) {
	row := q.db.QueryRow(ctx, certificateApprovalByID, id)
	var i CertificateApproval
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ActivityID,
		&i.SignerID,
		&i.RequestedBy,
		&i.SignerName,
		&i.SignerTitle,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CertificateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const certificateSigners = `-- name: CertificateSigners :many
SELECT id, display_name, role_code, is_active FROM admin_users
WHERE is_active = true AND display_name IS NOT NULL ORDER BY display_name, id
`

type CertificateSignersRow struct {
	ID          int32   `json:"id"`
	DisplayName *string `json:"display_name"`
	RoleCode    *string `json:"role_code"`
	IsActive    bool    `json:"is_active"`
}

func (q *Queries) CertificateSigners(ctx context.Context) ([]CertificateSignersRow, error) {
	rows, err := q.db.Query(ctx, certificateSigners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateSignersRow{}
	for rows.Next() {
		var i CertificateSignersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.RoleCode,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCertificateApprovals = `-- name: CountCertificateApprovals :one
SELECT count(*) FROM certificate_approvals
WHERE (signer_id=$1 OR requested_by=$1)
  AND ($2::integer IS NULL OR activity_id=$2)
  AND ($3::text IS NULL OR status=$3)
`

type CountCertificateApprovalsParams struct {
	ActorID    int32   `json:"actor_id"`
	ActivityID *int32  `json:"activity_id"`
	Status     *string `json:"status"`
}

func (q *Queries) CountCertificateApprovals(ctx context.Context, arg CountCertificateApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificateApprovals, arg.ActorID, arg.ActivityID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideCertificateApproval = `-- name: DecideCertificateApproval :one
UPDATE certificate_approvals SET status=$2, decided_by=$3, decided_at=$4, reason=$5, certificate_id=$6, updated_at=$4
WHERE id=$1 AND status='pending' RETURNING id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, status, decided_by, decided_at, reason, certificate_id, created_at, updated_at
`

type DecideCertificateApprovalParams struct {
	ID            int32              `json:"id"`
	Status        string             `json:"status"`
	DecidedBy     *int32             `json:"decided_by"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	Reason        *string            `json:"reason"`
	CertificateID *int32             `json:"certificate_id"`
}

func (q *Queries) DecideCertificateApproval(ctx context.Context, arg DecideCertificateApprovalParams) (CertificateApproval, error) {
	row := q.db.QueryRow(ctx, decideCertificateApproval,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Reason,
		arg.CertificateID,
	)
	var i CertificateApproval
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ActivityID,
		&i.SignerID,
		&i.RequestedBy,
		&i.SignerName,
		&i.SignerTitle,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CertificateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCertificateApproval = `-- name: InsertCertificateApproval :one
INSERT INTO certificate_approvals (registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,now(),now()) RETURNING id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, status, decided_by, decided_at, reason, certificate_id, created_at, updated_at
`

type InsertCertificateApprovalParams struct {
	RegistrationID int32  `json:"registration_id"`
	ActivityID     int32  `json:"activity_id"`
	SignerID       int32  `json:"signer_id"`
	RequestedBy    int32  `json:"requested_by"`
	SignerName     string `json:"signer_name"`
	SignerTitle    string `json:"signer_title"`
	Snapshot       []byte `json:"snapshot"`
	ContentHash    string `json:"content_hash"`
}

func (q *Queries) InsertCertificateApproval(ctx context.Context, arg InsertCertificateApprovalParams) (CertificateApproval, error) {
	row := q.db.QueryRow(ctx, insertCertificateApproval,
		arg.RegistrationID,
		arg.ActivityID,
		arg.SignerID,
		arg.RequestedBy,
		arg.SignerName,
		arg.SignerTitle,
		arg.Snapshot,
		arg.ContentHash,
	)
	var i CertificateApproval
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ActivityID,
		&i.SignerID,
		&i.RequestedBy,
		&i.SignerName,
		&i.SignerTitle,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CertificateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificateApprovals = `-- name: ListCertificateApprovals :many
SELECT id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, content_hash, status, decided_at, reason, certificate_id, created_at,
       snapshot->'participant'->>'name' AS participant_name,
       snapshot->'activity'->>'name' AS activity_name
FROM certificate_approvals
WHERE (signer_id=$1 OR requested_by=$1)
  AND ($2::integer IS NULL OR activity_id=$2)
  AND ($3::text IS NULL OR status=$3)
ORDER BY id DESC LIMIT $5::text::bigint OFFSET $4::text::bigint
`

type ListCertificateApprovalsParams struct {
	ActorID    int32   `json:"actor_id"`
	ActivityID *int32  `json:"activity_id"`
	Status     *string `json:"status"`
	PageOffset string  `json:"page_offset"`
	PageSize   *string `json:"page_size"`
}

type ListCertificateApprovalsRow struct {
	ID              int32              `json:"id"`
	RegistrationID  int32              `json:"registration_id"`
	ActivityID      int32              `json:"activity_id"`
	SignerID        int32              `json:"signer_id"`
	RequestedBy     int32              `json:"requested_by"`
	SignerName      string             `json:"signer_name"`
	SignerTitle     string             `json:"signer_title"`
	ContentHash     string             `json:"content_hash"`
	Status          string             `json:"status"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	Reason          *string            `json:"reason"`
	CertificateID   *int32             `json:"certificate_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ParticipantName interface{}        `json:"participant_name"`
	ActivityName    interface{}        `json:"activity_name"`
}

func (q *Queries) ListCertificateApprovals(ctx context.Context, arg ListCertificateApprovalsParams) ([]ListCertificateApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateApprovals,
		arg.ActorID,
		arg.ActivityID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateApprovalsRow{}
	for rows.Next() {
		var i ListCertificateApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.ActivityID,
			&i.SignerID,
			&i.RequestedBy,
			&i.SignerName,
			&i.SignerTitle,
			&i.ContentHash,
			&i.Status,
			&i.DecidedAt,
			&i.Reason,
			&i.CertificateID,
			&i.CreatedAt,
			&i.ParticipantName,
			&i.ActivityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCertificateApproval = `-- name: LockCertificateApproval :one
SELECT id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, status, decided_by, decided_at, reason, certificate_id, created_at, updated_at FROM certificate_approvals WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCertificateApproval(ctx context.Context, id int32) (CertificateApproval, error) {
	row := q.db.QueryRow(ctx, lockCertificateApproval, id)
	var i CertificateApproval
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ActivityID,
		&i.SignerID,
		&i.RequestedBy,
		&i.SignerName,
		&i.SignerTitle,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CertificateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pendingCertificateApproval = `-- name: PendingCertificateApproval :one
SELECT id, registration_id, activity_id, signer_id, requested_by, signer_name, signer_title, snapshot, content_hash, status, decided_by, decided_at, reason, certificate_id, created_at, updated_at FROM certificate_approvals WHERE registration_id=$1 AND status='pending'
`

func (q *Queries) PendingCertificateApproval(ctx context.Context, registrationID int32) (CertificateApproval, error) {
	row := q.db.QueryRow(ctx, pendingCertificateApproval, registrationID)
	var i CertificateApproval
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.ActivityID,
		&i.SignerID,
		&i.RequestedBy,
		&i.SignerName,
		&i.SignerTitle,
		&i.Snapshot,
		&i.ContentHash,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CertificateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCertificateApprovalSnapshot = `-- name: SetCertificateApprovalSnapshot :exec
UPDATE issued_certificates SET approval_snapshot=$2 WHERE id=$1 AND approval_snapshot IS NULL
`

type SetCertificateApprovalSnapshotParams struct {
	ID               int32  `json:"id"`
	ApprovalSnapshot []byte `json:"approval_snapshot"`
}

func (q *Queries) SetCertificateApprovalSnapshot(ctx context.Context, arg SetCertificateApprovalSnapshotParams) error {
	_, err := q.db.Exec(ctx, setCertificateApprovalSnapshot, arg.ID, arg.ApprovalSnapshot)
	return err
}
