// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: club_registrations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvedClubRoleRegistration = `-- name: ApprovedClubRoleRegistration :one
SELECT id, club_id, member_id, status, additional_data, created_at, updated_at FROM club_registrations WHERE id=CAST(CAST($1 AS text) AS integer) AND club_id= $2::integer AND status='APPROVED'
`

type ApprovedClubRoleRegistrationParams struct {
	Identifier string `json:"identifier"`
	ClubID     int32  `json:"club_id"`
}

func (q *Queries) ApprovedClubRoleRegistration(ctx context.Context, arg ApprovedClubRoleRegistrationParams) (ClubRegistration, error) {
	row := q.db.QueryRow(ctx, approvedClubRoleRegistration, arg.Identifier, arg.ClubID)
	var i ClubRegistration
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.Status,
		&i.AdditionalData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearPrimaryClubRoles = `-- name: ClearPrimaryClubRoles :exec
UPDATE club_member_roles SET is_primary=false WHERE club_registration_id= $1::integer AND ($2::integer IS NULL OR id <> $2)
`

type ClearPrimaryClubRolesParams struct {
	RegistrationID int32  `json:"registration_id"`
	ExceptID       *int32 `json:"except_id"`
}

func (q *Queries) ClearPrimaryClubRoles(ctx context.Context, arg ClearPrimaryClubRolesParams) error {
	_, err := q.db.Exec(ctx, clearPrimaryClubRoles, arg.RegistrationID, arg.ExceptID)
	return err
}

const clubRegistrationByIdentifier = `-- name: ClubRegistrationByIdentifier :one
SELECT id, club_id, member_id, status, additional_data, created_at, updated_at FROM club_registrations WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ClubRegistrationByIdentifier(ctx context.Context, identifier string) (ClubRegistration, error) {
	row := q.db.QueryRow(ctx, clubRegistrationByIdentifier, identifier)
	var i ClubRegistration
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.Status,
		&i.AdditionalData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clubRegistrationDetails = `-- name: ClubRegistrationDetails :one
SELECT cr.id, cr.club_id, cr.member_id, cr.status, cr.additional_data, cr.created_at, cr.updated_at,(to_jsonb(u)-'password')::jsonb AS member,row_to_json(p) AS profile,row_to_json(c) AS club,
COALESCE((SELECT jsonb_agg(role ORDER BY role.sort_order ASC,role.is_primary DESC,CASE WHEN $1::boolean THEN role.created_at END ASC) FROM club_member_roles role WHERE role.club_registration_id=cr.id),'[]'::jsonb)::jsonb AS roles
FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN clubs c ON c.id=cr.club_id
WHERE cr.id= $2::integer
`

type ClubRegistrationDetailsParams struct {
	MemberOrder bool  `json:"member_order"`
	ID          int32 `json:"id"`
}

type ClubRegistrationDetailsRow struct {
	ClubRegistration ClubRegistration `json:"club_registration"`
	Member           []byte           `json:"member"`
	Profile          []byte           `json:"profile"`
	Club             []byte           `json:"club"`
	Roles            []byte           `json:"roles"`
}

func (q *Queries) ClubRegistrationDetails(ctx context.Context, arg ClubRegistrationDetailsParams) (ClubRegistrationDetailsRow, error) {
	row := q.db.QueryRow(ctx, clubRegistrationDetails, arg.MemberOrder, arg.ID)
	var i ClubRegistrationDetailsRow
	err := row.Scan(
		&i.ClubRegistration.ID,
		&i.ClubRegistration.ClubID,
		&i.ClubRegistration.MemberID,
		&i.ClubRegistration.Status,
		&i.ClubRegistration.AdditionalData,
		&i.ClubRegistration.CreatedAt,
		&i.ClubRegistration.UpdatedAt,
		&i.Member,
		&i.Profile,
		&i.Club,
		&i.Roles,
	)
	return i, err
}

const clubRegistrationDuplicate = `-- name: ClubRegistrationDuplicate :one
SELECT EXISTS(SELECT 1 FROM club_registrations WHERE club_id= $1::integer AND member_id= $2::integer)
`

type ClubRegistrationDuplicateParams struct {
	ClubID   int32 `json:"club_id"`
	MemberID int32 `json:"member_id"`
}

func (q *Queries) ClubRegistrationDuplicate(ctx context.Context, arg ClubRegistrationDuplicateParams) (bool, error) {
	row := q.db.QueryRow(ctx, clubRegistrationDuplicate, arg.ClubID, arg.MemberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clubRegistrationExport = `-- name: ClubRegistrationExport :many
SELECT cr.id, cr.club_id, cr.member_id, cr.status, cr.additional_data, cr.created_at, cr.updated_at,(to_jsonb(u)-'password')::jsonb AS member,row_to_json(p) AS profile,province.name AS province,university.name AS university
FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN provinces province ON province.id=p.province_id LEFT JOIN universities university ON university.id=p.university_id
WHERE cr.club_id= $1::integer ORDER BY cr.created_at DESC
`

type ClubRegistrationExportRow struct {
	ClubRegistration ClubRegistration `json:"club_registration"`
	Member           []byte           `json:"member"`
	Profile          []byte           `json:"profile"`
	Province         *string          `json:"province"`
	University       *string          `json:"university"`
}

func (q *Queries) ClubRegistrationExport(ctx context.Context, clubID int32) ([]ClubRegistrationExportRow, error) {
	rows, err := q.db.Query(ctx, clubRegistrationExport, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubRegistrationExportRow{}
	for rows.Next() {
		var i ClubRegistrationExportRow
		if err := rows.Scan(
			&i.ClubRegistration.ID,
			&i.ClubRegistration.ClubID,
			&i.ClubRegistration.MemberID,
			&i.ClubRegistration.Status,
			&i.ClubRegistration.AdditionalData,
			&i.ClubRegistration.CreatedAt,
			&i.ClubRegistration.UpdatedAt,
			&i.Member,
			&i.Profile,
			&i.Province,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubRegistrationUser = `-- name: ClubRegistrationUser :one
SELECT id, email, password, created_at, updated_at, member_id, account_status FROM public_users WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ClubRegistrationUser(ctx context.Context, identifier string) (PublicUser, error) {
	row := q.db.QueryRow(ctx, clubRegistrationUser, identifier)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const clubRoleByIdentifier = `-- name: ClubRoleByIdentifier :one
SELECT id, club_registration_id, role_name, start_date, end_date, is_primary, sort_order, created_at, updated_at FROM club_member_roles WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ClubRoleByIdentifier(ctx context.Context, identifier string) (ClubMemberRole, error) {
	row := q.db.QueryRow(ctx, clubRoleByIdentifier, identifier)
	var i ClubMemberRole
	err := row.Scan(
		&i.ID,
		&i.ClubRegistrationID,
		&i.RoleName,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clubRoleList = `-- name: ClubRoleList :many
SELECT role.id, role.club_registration_id, role.role_name, role.start_date, role.end_date, role.is_primary, role.sort_order, role.created_at, role.updated_at,cr.id, cr.club_id, cr.member_id, cr.status, cr.additional_data, cr.created_at, cr.updated_at,(to_jsonb(u)-'password')::jsonb AS member,row_to_json(p) AS profile FROM club_member_roles role JOIN club_registrations cr ON cr.id=role.club_registration_id LEFT JOIN public_users u ON u.id=cr.member_id LEFT JOIN profiles p ON p.user_id=u.id WHERE cr.club_id= $1::integer AND cr.status='APPROVED' ORDER BY role.sort_order ASC,role.is_primary DESC,role.created_at ASC
`

type ClubRoleListRow struct {
	ClubMemberRole   ClubMemberRole   `json:"club_member_role"`
	ClubRegistration ClubRegistration `json:"club_registration"`
	Member           []byte           `json:"member"`
	Profile          []byte           `json:"profile"`
}

func (q *Queries) ClubRoleList(ctx context.Context, clubID int32) ([]ClubRoleListRow, error) {
	rows, err := q.db.Query(ctx, clubRoleList, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubRoleListRow{}
	for rows.Next() {
		var i ClubRoleListRow
		if err := rows.Scan(
			&i.ClubMemberRole.ID,
			&i.ClubMemberRole.ClubRegistrationID,
			&i.ClubMemberRole.RoleName,
			&i.ClubMemberRole.StartDate,
			&i.ClubMemberRole.EndDate,
			&i.ClubMemberRole.IsPrimary,
			&i.ClubMemberRole.SortOrder,
			&i.ClubMemberRole.CreatedAt,
			&i.ClubMemberRole.UpdatedAt,
			&i.ClubRegistration.ID,
			&i.ClubRegistration.ClubID,
			&i.ClubRegistration.MemberID,
			&i.ClubRegistration.Status,
			&i.ClubRegistration.AdditionalData,
			&i.ClubRegistration.CreatedAt,
			&i.ClubRegistration.UpdatedAt,
			&i.Member,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubRoleSuggestions = `-- name: ClubRoleSuggestions :many
SELECT DISTINCT role_name FROM club_member_roles role JOIN club_registrations cr ON cr.id=role.club_registration_id WHERE cr.club_id= $1::integer ORDER BY role_name ASC
`

func (q *Queries) ClubRoleSuggestions(ctx context.Context, clubID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, clubRoleSuggestions, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countClubRegistrations = `-- name: CountClubRegistrations :one
SELECT count(*) FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id LEFT JOIN profiles p ON p.user_id=u.id
WHERE cr.club_id= $1::integer AND ($2::text IS NULL OR cr.status=$2)
AND ($3::text IS NULL OR u.email ILIKE '%'||$3::text||'%' OR p.name ILIKE '%'||$3::text||'%')
`

type CountClubRegistrationsParams struct {
	ClubID int32   `json:"club_id"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountClubRegistrations(ctx context.Context, arg CountClubRegistrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClubRegistrations, arg.ClubID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClubRegistration = `-- name: CreateClubRegistration :one
INSERT INTO club_registrations(club_id,member_id,status,additional_data,created_at,updated_at)
VALUES($1::integer,$2::integer,'PENDING',$3::jsonb,now(),now()) RETURNING id, club_id, member_id, status, additional_data, created_at, updated_at
`

type CreateClubRegistrationParams struct {
	ClubID         int32  `json:"club_id"`
	MemberID       int32  `json:"member_id"`
	AdditionalData []byte `json:"additional_data"`
}

func (q *Queries) CreateClubRegistration(ctx context.Context, arg CreateClubRegistrationParams) (ClubRegistration, error) {
	row := q.db.QueryRow(ctx, createClubRegistration, arg.ClubID, arg.MemberID, arg.AdditionalData)
	var i ClubRegistration
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.Status,
		&i.AdditionalData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClubRole = `-- name: CreateClubRole :one
INSERT INTO club_member_roles(club_registration_id,role_name,start_date,end_date,is_primary,sort_order,created_at,updated_at)
VALUES($1::integer,$2::text,$3::date,$4::date,$5::boolean,CAST(CAST($6 AS text) AS integer),now(),now()) RETURNING id, club_registration_id, role_name, start_date, end_date, is_primary, sort_order, created_at, updated_at
`

type CreateClubRoleParams struct {
	RegistrationID int32       `json:"registration_id"`
	RoleName       string      `json:"role_name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsPrimary      bool        `json:"is_primary"`
	SortOrder      string      `json:"sort_order"`
}

func (q *Queries) CreateClubRole(ctx context.Context, arg CreateClubRoleParams) (ClubMemberRole, error) {
	row := q.db.QueryRow(ctx, createClubRole,
		arg.RegistrationID,
		arg.RoleName,
		arg.StartDate,
		arg.EndDate,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i ClubMemberRole
	err := row.Scan(
		&i.ID,
		&i.ClubRegistrationID,
		&i.RoleName,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClubRegistration = `-- name: DeleteClubRegistration :exec
DELETE FROM club_registrations WHERE id=$1
`

func (q *Queries) DeleteClubRegistration(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteClubRegistration, id)
	return err
}

const deleteClubRole = `-- name: DeleteClubRole :exec
DELETE FROM club_member_roles WHERE id=$1
`

func (q *Queries) DeleteClubRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteClubRole, id)
	return err
}

const listClubRegistrations = `-- name: ListClubRegistrations :many
SELECT cr.id, cr.club_id, cr.member_id, cr.status, cr.additional_data, cr.created_at, cr.updated_at,(to_jsonb(u)-'password')::jsonb AS member,row_to_json(p) AS profile,row_to_json(c) AS club,
COALESCE((SELECT jsonb_agg(role ORDER BY role.sort_order ASC,role.is_primary DESC,CASE WHEN $1::boolean THEN role.created_at END ASC) FROM club_member_roles role WHERE role.club_registration_id=cr.id),'[]'::jsonb)::jsonb AS roles
FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN clubs c ON c.id=cr.club_id
WHERE cr.club_id= $2::integer AND ($3::text IS NULL OR cr.status=$3)
AND ($4::text IS NULL OR u.email ILIKE '%'||$4::text||'%' OR p.name ILIKE '%'||$4::text||'%')
ORDER BY CASE WHEN $5::boolean THEN cr.created_at END ASC NULLS LAST,CASE WHEN $5::boolean THEN cr.id END ASC,
CASE WHEN NOT $5::boolean THEN cr.created_at END DESC NULLS LAST,CASE WHEN NOT $5::boolean THEN cr.id END DESC
LIMIT CAST($7::text AS bigint) OFFSET CAST($6::text AS bigint)
`

type ListClubRegistrationsParams struct {
	MemberOrder bool    `json:"member_order"`
	ClubID      int32   `json:"club_id"`
	Status      *string `json:"status"`
	Search      *string `json:"search"`
	Ascending   bool    `json:"ascending"`
	PageOffset  string  `json:"page_offset"`
	PageSize    *string `json:"page_size"`
}

type ListClubRegistrationsRow struct {
	ClubRegistration ClubRegistration `json:"club_registration"`
	Member           []byte           `json:"member"`
	Profile          []byte           `json:"profile"`
	Club             []byte           `json:"club"`
	Roles            []byte           `json:"roles"`
}

func (q *Queries) ListClubRegistrations(ctx context.Context, arg ListClubRegistrationsParams) ([]ListClubRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listClubRegistrations,
		arg.MemberOrder,
		arg.ClubID,
		arg.Status,
		arg.Search,
		arg.Ascending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubRegistrationsRow{}
	for rows.Next() {
		var i ListClubRegistrationsRow
		if err := rows.Scan(
			&i.ClubRegistration.ID,
			&i.ClubRegistration.ClubID,
			&i.ClubRegistration.MemberID,
			&i.ClubRegistration.Status,
			&i.ClubRegistration.AdditionalData,
			&i.ClubRegistration.CreatedAt,
			&i.ClubRegistration.UpdatedAt,
			&i.Member,
			&i.Profile,
			&i.Club,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClubRegistrations = `-- name: LockClubRegistrations :many
SELECT id, club_id, member_id, status, additional_data, created_at, updated_at FROM club_registrations WHERE id=ANY(CAST($1::text[] AS integer[])) FOR UPDATE
`

func (q *Queries) LockClubRegistrations(ctx context.Context, identifiers []string) ([]ClubRegistration, error) {
	rows, err := q.db.Query(ctx, lockClubRegistrations, identifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubRegistration{}
	for rows.Next() {
		var i ClubRegistration
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.MemberID,
			&i.Status,
			&i.AdditionalData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClubRegistration = `-- name: UpdateClubRegistration :one
UPDATE club_registrations SET status= $1::text,additional_data= $2::jsonb,
updated_at=CASE WHEN ROW(status,additional_data) IS DISTINCT FROM ROW($1::text,$2::jsonb) THEN now() ELSE updated_at END WHERE id= $3::integer RETURNING id, club_id, member_id, status, additional_data, created_at, updated_at
`

type UpdateClubRegistrationParams struct {
	Status         string `json:"status"`
	AdditionalData []byte `json:"additional_data"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdateClubRegistration(ctx context.Context, arg UpdateClubRegistrationParams) (ClubRegistration, error) {
	row := q.db.QueryRow(ctx, updateClubRegistration, arg.Status, arg.AdditionalData, arg.ID)
	var i ClubRegistration
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.Status,
		&i.AdditionalData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClubRole = `-- name: UpdateClubRole :one
UPDATE club_member_roles SET role_name= $1::text,start_date=$2::date,end_date=$3::date,is_primary= $4::boolean,sort_order=CAST(CAST($5 AS text) AS integer),
updated_at=CASE WHEN ROW(role_name,start_date,end_date,is_primary,sort_order) IS DISTINCT FROM ROW($1::text,$2::date,$3::date,$4::boolean,CAST(CAST($5 AS text) AS integer)) THEN now() ELSE updated_at END WHERE id= $6::integer RETURNING id, club_registration_id, role_name, start_date, end_date, is_primary, sort_order, created_at, updated_at
`

type UpdateClubRoleParams struct {
	RoleName  string      `json:"role_name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsPrimary bool        `json:"is_primary"`
	SortOrder string      `json:"sort_order"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateClubRole(ctx context.Context, arg UpdateClubRoleParams) (ClubMemberRole, error) {
	row := q.db.QueryRow(ctx, updateClubRole,
		arg.RoleName,
		arg.StartDate,
		arg.EndDate,
		arg.IsPrimary,
		arg.SortOrder,
		arg.ID,
	)
	var i ClubMemberRole
	err := row.Scan(
		&i.ID,
		&i.ClubRegistrationID,
		&i.RoleName,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
