// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clubs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clubByIdentifier = `-- name: ClubByIdentifier :one
SELECT id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type FROM clubs WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ClubByIdentifier(ctx context.Context, identifier string) (Club, error) {
	row := q.db.QueryRow(ctx, clubByIdentifier, identifier)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const clubHasActiveForm = `-- name: ClubHasActiveForm :one
SELECT EXISTS(SELECT 1 FROM custom_forms WHERE feature_type='club_registration' AND feature_id=$1 AND is_active=true)
`

func (q *Queries) ClubHasActiveForm(ctx context.Context, featureID *int32) (bool, error) {
	row := q.db.QueryRow(ctx, clubHasActiveForm, featureID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countClubsFiltered = `-- name: CountClubsFiltered :one
SELECT count(*) FROM clubs WHERE name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR club_type=$2)
AND ($3::boolean IS NULL OR is_show=$3)
AND ($4::boolean IS NULL OR is_registration_open=$4)
`

type CountClubsFilteredParams struct {
	Search             string  `json:"search"`
	ClubType           *string `json:"club_type"`
	IsShow             *bool   `json:"is_show"`
	IsRegistrationOpen *bool   `json:"is_registration_open"`
}

func (q *Queries) CountClubsFiltered(ctx context.Context, arg CountClubsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClubsFiltered,
		arg.Search,
		arg.ClubType,
		arg.IsShow,
		arg.IsRegistrationOpen,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClub = `-- name: CreateClub :one
INSERT INTO clubs(name,club_type,description,short_description,media,start_period,end_period,is_show,is_registration_open,registration_end_date,created_at,updated_at)
VALUES ($1::text,$2::text,$3::text,$4::text,$5::jsonb,$6::date,$7::date,false,false,$8::date,now(),now()) RETURNING id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type
`

type CreateClubParams struct {
	Name                string      `json:"name"`
	ClubType            string      `json:"club_type"`
	Description         *string     `json:"description"`
	ShortDescription    *string     `json:"short_description"`
	Media               []byte      `json:"media"`
	StartPeriod         pgtype.Date `json:"start_period"`
	EndPeriod           pgtype.Date `json:"end_period"`
	RegistrationEndDate pgtype.Date `json:"registration_end_date"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub,
		arg.Name,
		arg.ClubType,
		arg.Description,
		arg.ShortDescription,
		arg.Media,
		arg.StartPeriod,
		arg.EndPeriod,
		arg.RegistrationEndDate,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const latestClubForm = `-- name: LatestClubForm :one
SELECT id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info FROM custom_forms WHERE feature_type='club_registration' AND feature_id=$1 ORDER BY updated_at DESC,id DESC LIMIT 1
`

func (q *Queries) LatestClubForm(ctx context.Context, featureID *int32) (CustomForm, error) {
	row := q.db.QueryRow(ctx, latestClubForm, featureID)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const listClubsFiltered = `-- name: ListClubsFiltered :many
SELECT id,name,club_type,description,short_description,logo,created_at,updated_at,start_period,end_period,is_show,is_registration_open,registration_end_date FROM clubs
WHERE name ILIKE '%' || $1::text || '%'
AND ($2::text IS NULL OR club_type=$2)
AND ($3::boolean IS NULL OR is_show=$3)
AND ($4::boolean IS NULL OR is_registration_open=$4)
ORDER BY is_show DESC,created_at DESC LIMIT $6::bigint OFFSET $5::bigint
`

type ListClubsFilteredParams struct {
	Search             string  `json:"search"`
	ClubType           *string `json:"club_type"`
	IsShow             *bool   `json:"is_show"`
	IsRegistrationOpen *bool   `json:"is_registration_open"`
	PageOffset         int64   `json:"page_offset"`
	PageSize           *int64  `json:"page_size"`
}

type ListClubsFilteredRow struct {
	ID                  int32              `json:"id"`
	Name                string             `json:"name"`
	ClubType            string             `json:"club_type"`
	Description         *string            `json:"description"`
	ShortDescription    *string            `json:"short_description"`
	Logo                *string            `json:"logo"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	StartPeriod         pgtype.Date        `json:"start_period"`
	EndPeriod           pgtype.Date        `json:"end_period"`
	IsShow              *bool              `json:"is_show"`
	IsRegistrationOpen  *bool              `json:"is_registration_open"`
	RegistrationEndDate pgtype.Date        `json:"registration_end_date"`
}

func (q *Queries) ListClubsFiltered(ctx context.Context, arg ListClubsFilteredParams) ([]ListClubsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listClubsFiltered,
		arg.Search,
		arg.ClubType,
		arg.IsShow,
		arg.IsRegistrationOpen,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClubsFilteredRow{}
	for rows.Next() {
		var i ListClubsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClubType,
			&i.Description,
			&i.ShortDescription,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartPeriod,
			&i.EndPeriod,
			&i.IsShow,
			&i.IsRegistrationOpen,
			&i.RegistrationEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClubByIdentifier = `-- name: LockClubByIdentifier :one
SELECT id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type FROM clubs WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockClubByIdentifier(ctx context.Context, identifier string) (Club, error) {
	row := q.db.QueryRow(ctx, lockClubByIdentifier, identifier)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const updateClub = `-- name: UpdateClub :one
UPDATE clubs SET name= $1::text,club_type= $2::text,description=$3::text,short_description=$4::text,media=$5::jsonb,start_period=$6::date,end_period=$7::date,is_show=$8::boolean,is_registration_open=$9::boolean,registration_end_date=$10::date,
updated_at=CASE WHEN ROW(name,club_type,description,short_description,media,start_period,end_period,is_show,is_registration_open,registration_end_date) IS DISTINCT FROM ROW($1::text,$2::text,$3::text,$4::text,$5::jsonb,$6::date,$7::date,$8::boolean,$9::boolean,$10::date) THEN now() ELSE updated_at END
WHERE id= $11::integer RETURNING id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type
`

type UpdateClubParams struct {
	Name                string      `json:"name"`
	ClubType            string      `json:"club_type"`
	Description         *string     `json:"description"`
	ShortDescription    *string     `json:"short_description"`
	Media               []byte      `json:"media"`
	StartPeriod         pgtype.Date `json:"start_period"`
	EndPeriod           pgtype.Date `json:"end_period"`
	IsShow              *bool       `json:"is_show"`
	IsRegistrationOpen  *bool       `json:"is_registration_open"`
	RegistrationEndDate pgtype.Date `json:"registration_end_date"`
	ID                  int32       `json:"id"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClub,
		arg.Name,
		arg.ClubType,
		arg.Description,
		arg.ShortDescription,
		arg.Media,
		arg.StartPeriod,
		arg.EndPeriod,
		arg.IsShow,
		arg.IsRegistrationOpen,
		arg.RegistrationEndDate,
		arg.ID,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const updateClubLogo = `-- name: UpdateClubLogo :one
UPDATE clubs SET logo= $1::text,updated_at=CASE WHEN logo IS DISTINCT FROM $1::text THEN now() ELSE updated_at END WHERE id= $2::integer RETURNING id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type
`

type UpdateClubLogoParams struct {
	Logo string `json:"logo"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateClubLogo(ctx context.Context, arg UpdateClubLogoParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClubLogo, arg.Logo, arg.ID)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const updateClubMedia = `-- name: UpdateClubMedia :one
UPDATE clubs SET media= $1::jsonb,updated_at=CASE WHEN media IS DISTINCT FROM $1::jsonb THEN now() ELSE updated_at END WHERE id= $2::integer RETURNING id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type
`

type UpdateClubMediaParams struct {
	Media []byte `json:"media"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateClubMedia(ctx context.Context, arg UpdateClubMediaParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClubMedia, arg.Media, arg.ID)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}

const updateClubRegistrationInfo = `-- name: UpdateClubRegistrationInfo :one
UPDATE clubs SET registration_info= $1::jsonb,updated_at=CASE WHEN registration_info IS DISTINCT FROM $1::jsonb THEN now() ELSE updated_at END WHERE id= $2::integer RETURNING id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type
`

type UpdateClubRegistrationInfoParams struct {
	RegistrationInfo []byte `json:"registration_info"`
	ID               int32  `json:"id"`
}

func (q *Queries) UpdateClubRegistrationInfo(ctx context.Context, arg UpdateClubRegistrationInfoParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClubRegistrationInfo, arg.RegistrationInfo, arg.ID)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Logo,
		&i.Media,
		&i.StartPeriod,
		&i.EndPeriod,
		&i.IsShow,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationInfo,
		&i.IsRegistrationOpen,
		&i.RegistrationEndDate,
		&i.ClubType,
	)
	return i, err
}
