// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counseling.sql

package dbgen

import (
	"context"
)

const counselingByIdentifier = `-- name: CounselingByIdentifier :one
SELECT id, user_id, problem_ownership, owner_name, problem_category, problem_description, handling_technic, counselor_gender, counselor_id, status, additional_notes, created_at, updated_at FROM ruang_curhats WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CounselingByIdentifier(ctx context.Context, identifier string) (RuangCurhat, error) {
	row := q.db.QueryRow(ctx, counselingByIdentifier, identifier)
	var i RuangCurhat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemOwnership,
		&i.OwnerName,
		&i.ProblemCategory,
		&i.ProblemDescription,
		&i.HandlingTechnic,
		&i.CounselorGender,
		&i.CounselorID,
		&i.Status,
		&i.AdditionalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const counselingDetails = `-- name: CounselingDetails :one
SELECT rc.id, rc.user_id, rc.problem_ownership, rc.owner_name, rc.problem_category, rc.problem_description, rc.handling_technic, rc.counselor_gender, rc.counselor_id, rc.status, rc.additional_notes, rc.created_at, rc.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,(to_jsonb(a)-'password')::jsonb AS admin_user
FROM ruang_curhats rc LEFT JOIN public_users u ON u.id=rc.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users a ON a.id=rc.counselor_id WHERE rc.id = $1::integer
`

type CounselingDetailsRow struct {
	RuangCurhat RuangCurhat `json:"ruang_curhat"`
	PublicUser  []byte      `json:"public_user"`
	Profile     []byte      `json:"profile"`
	AdminUser   []byte      `json:"admin_user"`
}

func (q *Queries) CounselingDetails(ctx context.Context, id int32) (CounselingDetailsRow, error) {
	row := q.db.QueryRow(ctx, counselingDetails, id)
	var i CounselingDetailsRow
	err := row.Scan(
		&i.RuangCurhat.ID,
		&i.RuangCurhat.UserID,
		&i.RuangCurhat.ProblemOwnership,
		&i.RuangCurhat.OwnerName,
		&i.RuangCurhat.ProblemCategory,
		&i.RuangCurhat.ProblemDescription,
		&i.RuangCurhat.HandlingTechnic,
		&i.RuangCurhat.CounselorGender,
		&i.RuangCurhat.CounselorID,
		&i.RuangCurhat.Status,
		&i.RuangCurhat.AdditionalNotes,
		&i.RuangCurhat.CreatedAt,
		&i.RuangCurhat.UpdatedAt,
		&i.PublicUser,
		&i.Profile,
		&i.AdminUser,
	)
	return i, err
}

const countCounseling = `-- name: CountCounseling :one
SELECT count(*) FROM ruang_curhats rc LEFT JOIN public_users u ON u.id=rc.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users a ON a.id=rc.counselor_id
WHERE ($1::text IS NULL OR rc.status=CAST(CAST($1 AS text) AS integer))
AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
AND ($3::text IS NULL OR p.gender=$3::text)
AND ($4::text IS NULL OR a.display_name ILIKE '%'||$4::text||'%')
`

type CountCounselingParams struct {
	Status    *string `json:"status"`
	Name      *string `json:"name"`
	Gender    *string `json:"gender"`
	AdminName *string `json:"admin_name"`
}

func (q *Queries) CountCounseling(ctx context.Context, arg CountCounselingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCounseling,
		arg.Status,
		arg.Name,
		arg.Gender,
		arg.AdminName,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCounseling = `-- name: ListCounseling :many
SELECT rc.id, rc.user_id, rc.problem_ownership, rc.owner_name, rc.problem_category, rc.problem_description, rc.handling_technic, rc.counselor_gender, rc.counselor_id, rc.status, rc.additional_notes, rc.created_at, rc.updated_at,(to_jsonb(u)-'password')::jsonb AS public_user,row_to_json(p) AS profile,(to_jsonb(a)-'password')::jsonb AS admin_user
FROM ruang_curhats rc LEFT JOIN public_users u ON u.id=rc.user_id LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN admin_users a ON a.id=rc.counselor_id
WHERE ($1::text IS NULL OR rc.status=CAST(CAST($1 AS text) AS integer))
AND ($2::text IS NULL OR p.name ILIKE '%'||$2::text||'%')
AND ($3::text IS NULL OR p.gender=$3::text)
AND ($4::text IS NULL OR a.display_name ILIKE '%'||$4::text||'%')
ORDER BY rc.created_at DESC LIMIT $6::bigint OFFSET $5::bigint
`

type ListCounselingParams struct {
	Status     *string `json:"status"`
	Name       *string `json:"name"`
	Gender     *string `json:"gender"`
	AdminName  *string `json:"admin_name"`
	PageOffset int64   `json:"page_offset"`
	PageSize   *int64  `json:"page_size"`
}

type ListCounselingRow struct {
	RuangCurhat RuangCurhat `json:"ruang_curhat"`
	PublicUser  []byte      `json:"public_user"`
	Profile     []byte      `json:"profile"`
	AdminUser   []byte      `json:"admin_user"`
}

func (q *Queries) ListCounseling(ctx context.Context, arg ListCounselingParams) ([]ListCounselingRow, error) {
	rows, err := q.db.Query(ctx, listCounseling,
		arg.Status,
		arg.Name,
		arg.Gender,
		arg.AdminName,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounselingRow{}
	for rows.Next() {
		var i ListCounselingRow
		if err := rows.Scan(
			&i.RuangCurhat.ID,
			&i.RuangCurhat.UserID,
			&i.RuangCurhat.ProblemOwnership,
			&i.RuangCurhat.OwnerName,
			&i.RuangCurhat.ProblemCategory,
			&i.RuangCurhat.ProblemDescription,
			&i.RuangCurhat.HandlingTechnic,
			&i.RuangCurhat.CounselorGender,
			&i.RuangCurhat.CounselorID,
			&i.RuangCurhat.Status,
			&i.RuangCurhat.AdditionalNotes,
			&i.RuangCurhat.CreatedAt,
			&i.RuangCurhat.UpdatedAt,
			&i.PublicUser,
			&i.Profile,
			&i.AdminUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounseling = `-- name: UpdateCounseling :one
UPDATE ruang_curhats SET counselor_id=CAST(CAST($1 AS text) AS integer),status=CAST(CAST($2 AS text) AS integer),additional_notes=$3::text,
updated_at=CASE WHEN ROW(counselor_id,status,additional_notes) IS DISTINCT FROM ROW(CAST(CAST($1 AS text) AS integer),CAST(CAST($2 AS text) AS integer),$3::text) THEN now() ELSE updated_at END WHERE id = $4::integer RETURNING id, user_id, problem_ownership, owner_name, problem_category, problem_description, handling_technic, counselor_gender, counselor_id, status, additional_notes, created_at, updated_at
`

type UpdateCounselingParams struct {
	CounselorID     *string `json:"counselor_id"`
	Status          *string `json:"status"`
	AdditionalNotes *string `json:"additional_notes"`
	ID              int32   `json:"id"`
}

func (q *Queries) UpdateCounseling(ctx context.Context, arg UpdateCounselingParams) (RuangCurhat, error) {
	row := q.db.QueryRow(ctx, updateCounseling,
		arg.CounselorID,
		arg.Status,
		arg.AdditionalNotes,
		arg.ID,
	)
	var i RuangCurhat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemOwnership,
		&i.OwnerName,
		&i.ProblemCategory,
		&i.ProblemDescription,
		&i.HandlingTechnic,
		&i.CounselorGender,
		&i.CounselorID,
		&i.Status,
		&i.AdditionalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
