// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourseLearners = `-- name: CountCourseLearners :one
SELECT count(DISTINCT p.user_id) FROM course_lesson_progress p JOIN course_lessons l ON l.id=p.lesson_id
JOIN public_users u ON u.id=p.user_id
LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=p.user_id ORDER BY id LIMIT 1) pr ON true
WHERE l.course_id = $1 AND ($2::text='' OR pr.name ILIKE '%' || $2 || '%' OR u.member_id ILIKE '%' || $2 || '%')
`

type CountCourseLearnersParams struct {
	CourseID int32  `json:"course_id"`
	Search   string `json:"search"`
}

func (q *Queries) CountCourseLearners(ctx context.Context, arg CountCourseLearnersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseLearners, arg.CourseID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCourses = `-- name: CountCourses :one
SELECT count(*) FROM courses c WHERE ($1::text='' OR c.title ILIKE '%' || $1 || '%') AND ($2::text='' OR c.status = $2)
`

type CountCoursesParams struct {
	Search string `json:"search"`
	Status string `json:"status"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courseByID = `-- name: CourseByID :one
SELECT id, title, summary, description, minimum_level, status, created_at, updated_at FROM courses WHERE id=$1
`

func (q *Queries) CourseByID(ctx context.Context, id int32) (Course, error) {
	row := q.db.QueryRow(ctx, courseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.MinimumLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseDocumentByID = `-- name: CourseDocumentByID :one
SELECT d.id, d.lesson_id, d.storage_key, d.filename, d.size_bytes, d.deleted_at, d.created_at FROM course_documents d JOIN course_lessons l ON l.id=d.lesson_id
WHERE l.course_id=$1 AND l.id=$2 AND d.id=$3 AND l.deleted_at IS NULL AND d.deleted_at IS NULL
`

type CourseDocumentByIDParams struct {
	CourseID int32 `json:"course_id"`
	ID       int32 `json:"id"`
	ID_2     int32 `json:"id_2"`
}

func (q *Queries) CourseDocumentByID(ctx context.Context, arg CourseDocumentByIDParams) (CourseDocument, error) {
	row := q.db.QueryRow(ctx, courseDocumentByID, arg.CourseID, arg.ID, arg.ID_2)
	var i CourseDocument
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.StorageKey,
		&i.Filename,
		&i.SizeBytes,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const courseDocuments = `-- name: CourseDocuments :many
SELECT d.id, d.lesson_id, d.storage_key, d.filename, d.size_bytes, d.deleted_at, d.created_at FROM course_documents d JOIN course_lessons l ON l.id=d.lesson_id
WHERE l.course_id=$1 AND l.deleted_at IS NULL AND d.deleted_at IS NULL ORDER BY d.id
`

func (q *Queries) CourseDocuments(ctx context.Context, courseID int32) ([]CourseDocument, error) {
	rows, err := q.db.Query(ctx, courseDocuments, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseDocument{}
	for rows.Next() {
		var i CourseDocument
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.StorageKey,
			&i.Filename,
			&i.SizeBytes,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseLearners = `-- name: CourseLearners :many
SELECT p.user_id, COALESCE(pr.name,'')::text AS name, u.member_id,
count(*) FILTER (WHERE p.completed_at IS NOT NULL AND l.deleted_at IS NULL)::integer AS completed_lessons,
(SELECT count(*) FROM course_lessons cl WHERE cl.course_id = $1 AND cl.deleted_at IS NULL)::integer AS total_lessons,
min(p.first_visited_at)::timestamptz AS started_at, max(p.last_visited_at)::timestamptz AS last_activity_at
FROM course_lesson_progress p JOIN course_lessons l ON l.id=p.lesson_id
JOIN public_users u ON u.id=p.user_id
LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=p.user_id ORDER BY id LIMIT 1) pr ON true
WHERE l.course_id = $1 AND ($2::text='' OR pr.name ILIKE '%' || $2 || '%' OR u.member_id ILIKE '%' || $2 || '%')
GROUP BY p.user_id,pr.name,u.member_id ORDER BY max(p.last_visited_at) DESC,p.user_id
LIMIT $4 OFFSET $3
`

type CourseLearnersParams struct {
	CourseID   int32  `json:"course_id"`
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type CourseLearnersRow struct {
	UserID           int32              `json:"user_id"`
	Name             string             `json:"name"`
	MemberID         *string            `json:"member_id"`
	CompletedLessons int32              `json:"completed_lessons"`
	TotalLessons     int32              `json:"total_lessons"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
}

func (q *Queries) CourseLearners(ctx context.Context, arg CourseLearnersParams) ([]CourseLearnersRow, error) {
	rows, err := q.db.Query(ctx, courseLearners,
		arg.CourseID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseLearnersRow{}
	for rows.Next() {
		var i CourseLearnersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.MemberID,
			&i.CompletedLessons,
			&i.TotalLessons,
			&i.StartedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseLessonByID = `-- name: CourseLessonByID :one
SELECT id, course_id, title, description, youtube_video_id, position, deleted_at, created_at, updated_at FROM course_lessons WHERE course_id=$1 AND id=$2 AND deleted_at IS NULL
`

type CourseLessonByIDParams struct {
	CourseID int32 `json:"course_id"`
	ID       int32 `json:"id"`
}

func (q *Queries) CourseLessonByID(ctx context.Context, arg CourseLessonByIDParams) (CourseLesson, error) {
	row := q.db.QueryRow(ctx, courseLessonByID, arg.CourseID, arg.ID)
	var i CourseLesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.YoutubeVideoID,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseLessons = `-- name: CourseLessons :many
SELECT id, course_id, title, description, youtube_video_id, position, deleted_at, created_at, updated_at FROM course_lessons WHERE course_id=$1 AND deleted_at IS NULL ORDER BY position,id
`

func (q *Queries) CourseLessons(ctx context.Context, courseID int32) ([]CourseLesson, error) {
	rows, err := q.db.Query(ctx, courseLessons, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseLesson{}
	for rows.Next() {
		var i CourseLesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.YoutubeVideoID,
			&i.Position,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses(title,summary,description,minimum_level) VALUES($1,$2,$3,$4) RETURNING id, title, summary, description, minimum_level, status, created_at, updated_at
`

type CreateCourseParams struct {
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Description  string `json:"description"`
	MinimumLevel int32  `json:"minimum_level"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.MinimumLevel,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.MinimumLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourseDocument = `-- name: CreateCourseDocument :one
INSERT INTO course_documents(lesson_id,storage_key,filename,size_bytes) VALUES($1,$2,$3,$4) RETURNING id, lesson_id, storage_key, filename, size_bytes, deleted_at, created_at
`

type CreateCourseDocumentParams struct {
	LessonID   int32  `json:"lesson_id"`
	StorageKey string `json:"storage_key"`
	Filename   string `json:"filename"`
	SizeBytes  int32  `json:"size_bytes"`
}

func (q *Queries) CreateCourseDocument(ctx context.Context, arg CreateCourseDocumentParams) (CourseDocument, error) {
	row := q.db.QueryRow(ctx, createCourseDocument,
		arg.LessonID,
		arg.StorageKey,
		arg.Filename,
		arg.SizeBytes,
	)
	var i CourseDocument
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.StorageKey,
		&i.Filename,
		&i.SizeBytes,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCourseLesson = `-- name: CreateCourseLesson :one
INSERT INTO course_lessons(course_id,title,description,youtube_video_id,position)
VALUES($1,$2,$3,$4,(SELECT COALESCE(max(position),0)+1 FROM course_lessons WHERE course_id = $1)) RETURNING id, course_id, title, description, youtube_video_id, position, deleted_at, created_at, updated_at
`

type CreateCourseLessonParams struct {
	CourseID       int32  `json:"course_id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	YoutubeVideoID string `json:"youtube_video_id"`
}

func (q *Queries) CreateCourseLesson(ctx context.Context, arg CreateCourseLessonParams) (CourseLesson, error) {
	row := q.db.QueryRow(ctx, createCourseLesson,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.YoutubeVideoID,
	)
	var i CourseLesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.YoutubeVideoID,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT c.id, c.title, c.summary, c.description, c.minimum_level, c.status, c.created_at, c.updated_at, (SELECT count(*) FROM course_lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL)::integer AS lesson_count
FROM courses c
WHERE ($1::text='' OR c.title ILIKE '%' || $1 || '%')
AND ($2::text='' OR c.status = $2)
ORDER BY c.id DESC LIMIT $4 OFFSET $3
`

type ListCoursesParams struct {
	Search     string `json:"search"`
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListCoursesRow struct {
	ID           int32              `json:"id"`
	Title        string             `json:"title"`
	Summary      string             `json:"summary"`
	Description  string             `json:"description"`
	MinimumLevel int32              `json:"minimum_level"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LessonCount  int32              `json:"lesson_count"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Description,
			&i.MinimumLevel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCourse = `-- name: LockCourse :one
SELECT id, title, summary, description, minimum_level, status, created_at, updated_at FROM courses WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCourse(ctx context.Context, id int32) (Course, error) {
	row := q.db.QueryRow(ctx, lockCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.MinimumLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeCourseDocument = `-- name: RemoveCourseDocument :exec
UPDATE course_documents SET deleted_at=now() WHERE id=$1
`

func (q *Queries) RemoveCourseDocument(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeCourseDocument, id)
	return err
}

const removeCourseLesson = `-- name: RemoveCourseLesson :exec
UPDATE course_lessons SET deleted_at=now(),updated_at=now() WHERE course_id=$1 AND id=$2 AND deleted_at IS NULL
`

type RemoveCourseLessonParams struct {
	CourseID int32 `json:"course_id"`
	ID       int32 `json:"id"`
}

func (q *Queries) RemoveCourseLesson(ctx context.Context, arg RemoveCourseLessonParams) error {
	_, err := q.db.Exec(ctx, removeCourseLesson, arg.CourseID, arg.ID)
	return err
}

const reorderCourseLesson = `-- name: ReorderCourseLesson :exec
UPDATE course_lessons SET position=$3,updated_at=now() WHERE course_id=$1 AND id=$2 AND deleted_at IS NULL
`

type ReorderCourseLessonParams struct {
	CourseID int32 `json:"course_id"`
	ID       int32 `json:"id"`
	Position int32 `json:"position"`
}

func (q *Queries) ReorderCourseLesson(ctx context.Context, arg ReorderCourseLessonParams) error {
	_, err := q.db.Exec(ctx, reorderCourseLesson, arg.CourseID, arg.ID, arg.Position)
	return err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses SET title=$2,summary=$3,description=$4,minimum_level=$5,status=$6,updated_at=now() WHERE id=$1 RETURNING id, title, summary, description, minimum_level, status, created_at, updated_at
`

type UpdateCourseParams struct {
	ID           int32  `json:"id"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
	Description  string `json:"description"`
	MinimumLevel int32  `json:"minimum_level"`
	Status       string `json:"status"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.MinimumLevel,
		arg.Status,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.MinimumLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseLesson = `-- name: UpdateCourseLesson :one
UPDATE course_lessons SET title=$3,description=$4,youtube_video_id=$5,updated_at=now()
WHERE course_id=$1 AND id=$2 AND deleted_at IS NULL RETURNING id, course_id, title, description, youtube_video_id, position, deleted_at, created_at, updated_at
`

type UpdateCourseLessonParams struct {
	CourseID       int32  `json:"course_id"`
	ID             int32  `json:"id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	YoutubeVideoID string `json:"youtube_video_id"`
}

func (q *Queries) UpdateCourseLesson(ctx context.Context, arg UpdateCourseLessonParams) (CourseLesson, error) {
	row := q.db.QueryRow(ctx, updateCourseLesson,
		arg.CourseID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.YoutubeVideoID,
	)
	var i CourseLesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.YoutubeVideoID,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
