// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_responses.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormResponses = `-- name: CountFormResponses :one
SELECT count(*) FROM custom_form_responses WHERE form_id=$1
`

func (q *Queries) CountFormResponses(ctx context.Context, formID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFormResponses, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredFormAttachment = `-- name: DeleteExpiredFormAttachment :exec
DELETE FROM custom_form_attachments WHERE id=$1 AND claimed_at IS NULL
`

func (q *Queries) DeleteExpiredFormAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredFormAttachment, id)
	return err
}

const expiredFormAttachments = `-- name: ExpiredFormAttachments :many
SELECT a.id, a.session_id, a.field_key, a.storage_key, a.original_name, a.download_name, a.mime_type, a.size_bytes, a.source_size_bytes, a.width, a.height, a.claimed_at, a.created_at FROM custom_form_attachments a JOIN custom_form_sessions s ON s.id=a.session_id
WHERE a.claimed_at IS NULL AND s.expires_at < now() ORDER BY a.created_at LIMIT 100
`

func (q *Queries) ExpiredFormAttachments(ctx context.Context) ([]CustomFormAttachment, error) {
	rows, err := q.db.Query(ctx, expiredFormAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFormAttachment{}
	for rows.Next() {
		var i CustomFormAttachment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FieldKey,
			&i.StorageKey,
			&i.OriginalName,
			&i.DownloadName,
			&i.MimeType,
			&i.SizeBytes,
			&i.SourceSizeBytes,
			&i.Width,
			&i.Height,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const formAttachmentByID = `-- name: FormAttachmentByID :one
SELECT a.id, a.session_id, a.field_key, a.storage_key, a.original_name, a.download_name, a.mime_type, a.size_bytes, a.source_size_bytes, a.width, a.height, a.claimed_at, a.created_at FROM custom_form_attachments a JOIN custom_form_sessions s ON s.id=a.session_id
WHERE a.id=$2::uuid AND s.form_id=$1 AND a.claimed_at IS NOT NULL
`

type FormAttachmentByIDParams struct {
	FormID       int32       `json:"form_id"`
	AttachmentID pgtype.UUID `json:"attachment_id"`
}

func (q *Queries) FormAttachmentByID(ctx context.Context, arg FormAttachmentByIDParams) (CustomFormAttachment, error) {
	row := q.db.QueryRow(ctx, formAttachmentByID, arg.FormID, arg.AttachmentID)
	var i CustomFormAttachment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FieldKey,
		&i.StorageKey,
		&i.OriginalName,
		&i.DownloadName,
		&i.MimeType,
		&i.SizeBytes,
		&i.SourceSizeBytes,
		&i.Width,
		&i.Height,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const formHasAttachments = `-- name: FormHasAttachments :one
SELECT EXISTS(SELECT 1 FROM custom_form_attachments a JOIN custom_form_sessions s ON s.id=a.session_id WHERE s.form_id=$1)
`

func (q *Queries) FormHasAttachments(ctx context.Context, formID int32) (bool, error) {
	row := q.db.QueryRow(ctx, formHasAttachments, formID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const formHasResponses = `-- name: FormHasResponses :one
SELECT EXISTS(SELECT 1 FROM custom_form_responses WHERE form_id=$1)
`

func (q *Queries) FormHasResponses(ctx context.Context, formID int32) (bool, error) {
	row := q.db.QueryRow(ctx, formHasResponses, formID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const formResponseByID = `-- name: FormResponseByID :one
SELECT id, form_id, session_id, user_id, form_snapshot, answers, created_at FROM custom_form_responses WHERE form_id=$1 AND id=$2::uuid
`

type FormResponseByIDParams struct {
	FormID     int32       `json:"form_id"`
	ResponseID pgtype.UUID `json:"response_id"`
}

func (q *Queries) FormResponseByID(ctx context.Context, arg FormResponseByIDParams) (CustomFormResponse, error) {
	row := q.db.QueryRow(ctx, formResponseByID, arg.FormID, arg.ResponseID)
	var i CustomFormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SessionID,
		&i.UserID,
		&i.FormSnapshot,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const listFormResponses = `-- name: ListFormResponses :many
SELECT id, form_id, session_id, user_id, form_snapshot, answers, created_at FROM custom_form_responses WHERE form_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3
`

type ListFormResponsesParams struct {
	FormID int32 `json:"form_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFormResponses(ctx context.Context, arg ListFormResponsesParams) ([]CustomFormResponse, error) {
	rows, err := q.db.Query(ctx, listFormResponses, arg.FormID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFormResponse{}
	for rows.Next() {
		var i CustomFormResponse
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SessionID,
			&i.UserID,
			&i.FormSnapshot,
			&i.Answers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const responseAttachments = `-- name: ResponseAttachments :many
SELECT id, session_id, field_key, storage_key, original_name, download_name, mime_type, size_bytes, source_size_bytes, width, height, claimed_at, created_at FROM custom_form_attachments WHERE session_id=$1 AND claimed_at IS NOT NULL ORDER BY created_at,id
`

func (q *Queries) ResponseAttachments(ctx context.Context, sessionID pgtype.UUID) ([]CustomFormAttachment, error) {
	rows, err := q.db.Query(ctx, responseAttachments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFormAttachment{}
	for rows.Next() {
		var i CustomFormAttachment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FieldKey,
			&i.StorageKey,
			&i.OriginalName,
			&i.DownloadName,
			&i.MimeType,
			&i.SizeBytes,
			&i.SourceSizeBytes,
			&i.Width,
			&i.Height,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
