// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package dbgen

import (
	"context"
)

const activeFormByFeature = `-- name: ActiveFormByFeature :one
SELECT id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info FROM custom_forms WHERE feature_type = $1::text AND feature_id=CAST(CAST($2 AS text) AS integer) AND is_active=true ORDER BY updated_at DESC,id DESC LIMIT 1
`

type ActiveFormByFeatureParams struct {
	FeatureType string `json:"feature_type"`
	Identifier  string `json:"identifier"`
}

func (q *Queries) ActiveFormByFeature(ctx context.Context, arg ActiveFormByFeatureParams) (CustomForm, error) {
	row := q.db.QueryRow(ctx, activeFormByFeature, arg.FeatureType, arg.Identifier)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const attachFormToActivity = `-- name: AttachFormToActivity :one
UPDATE custom_forms SET feature_type='activity_registration',feature_id=CAST(CAST($1 AS text) AS integer),updated_at=CASE WHEN feature_type IS DISTINCT FROM 'activity_registration' OR feature_id IS DISTINCT FROM CAST(CAST($1 AS text) AS integer) THEN now() ELSE updated_at END WHERE id = $2::integer RETURNING id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info
`

type AttachFormToActivityParams struct {
	Identifier string `json:"identifier"`
	ID         int32  `json:"id"`
}

func (q *Queries) AttachFormToActivity(ctx context.Context, arg AttachFormToActivityParams) (CustomForm, error) {
	row := q.db.QueryRow(ctx, attachFormToActivity, arg.Identifier, arg.ID)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const countFormsFiltered = `-- name: CountFormsFiltered :one
SELECT count(*) FROM custom_forms WHERE (NOT $1::boolean OR feature_id IS NULL)
AND ($2::text IS NULL OR form_name ILIKE '%' || $2::text || '%')
AND ($3::text IS NULL OR feature_type=$3)
AND ($4::text IS NULL OR feature_id=CAST(CAST($4 AS text) AS integer))
AND ($5::boolean IS NULL OR is_active=$5)
`

type CountFormsFilteredParams struct {
	Unattached  bool    `json:"unattached"`
	Search      *string `json:"search"`
	FeatureType *string `json:"feature_type"`
	FeatureID   *string `json:"feature_id"`
	IsActive    *bool   `json:"is_active"`
}

func (q *Queries) CountFormsFiltered(ctx context.Context, arg CountFormsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsFiltered,
		arg.Unattached,
		arg.Search,
		arg.FeatureType,
		arg.FeatureID,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO custom_forms(form_name,form_description,post_submission_info,feature_type,feature_id,form_schema,is_active,created_at,updated_at)
VALUES ($1::text,$2::text,$3::text,$4::text,CAST(CAST($5 AS text) AS integer),COALESCE($6::jsonb,'{}'::jsonb),COALESCE($7::boolean,true),now(),now()) RETURNING id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info
`

type CreateFormParams struct {
	FormName           string  `json:"form_name"`
	FormDescription    *string `json:"form_description"`
	PostSubmissionInfo *string `json:"post_submission_info"`
	FeatureType        *string `json:"feature_type"`
	FeatureID          *string `json:"feature_id"`
	FormSchema         []byte  `json:"form_schema"`
	IsActive           *bool   `json:"is_active"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (CustomForm, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.FormName,
		arg.FormDescription,
		arg.PostSubmissionInfo,
		arg.FeatureType,
		arg.FeatureID,
		arg.FormSchema,
		arg.IsActive,
	)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM custom_forms WHERE id=$1
`

func (q *Queries) DeleteForm(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteForm, id)
	return err
}

const detachDeletedFeatureForms = `-- name: DetachDeletedFeatureForms :exec
UPDATE custom_forms SET feature_id=null,is_active=false,updated_at=now()
WHERE feature_type = $1::text AND feature_id = $2::integer
`

type DetachDeletedFeatureFormsParams struct {
	FeatureType string `json:"feature_type"`
	FeatureID   int32  `json:"feature_id"`
}

func (q *Queries) DetachDeletedFeatureForms(ctx context.Context, arg DetachDeletedFeatureFormsParams) error {
	_, err := q.db.Exec(ctx, detachDeletedFeatureForms, arg.FeatureType, arg.FeatureID)
	return err
}

const detachFormFromActivity = `-- name: DetachFormFromActivity :one
UPDATE custom_forms SET feature_id=null,updated_at=now() WHERE id=$1 RETURNING id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info
`

func (q *Queries) DetachFormFromActivity(ctx context.Context, id int32) (CustomForm, error) {
	row := q.db.QueryRow(ctx, detachFormFromActivity, id)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const formAvailableActivities = `-- name: FormAvailableActivities :many
SELECT id,name FROM activities WHERE id NOT IN (SELECT feature_id FROM custom_forms WHERE feature_type='activity_registration' AND feature_id IS NOT NULL AND ($1::text IS NULL OR id<>CAST(CAST($1 AS text) AS integer))) ORDER BY name ASC
`

type FormAvailableActivitiesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) FormAvailableActivities(ctx context.Context, currentFormID *string) ([]FormAvailableActivitiesRow, error) {
	rows, err := q.db.Query(ctx, formAvailableActivities, currentFormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormAvailableActivitiesRow{}
	for rows.Next() {
		var i FormAvailableActivitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const formAvailableClubs = `-- name: FormAvailableClubs :many
SELECT id,name FROM clubs WHERE id NOT IN (SELECT feature_id FROM custom_forms WHERE feature_type='club_registration' AND feature_id IS NOT NULL AND ($1::text IS NULL OR id<>CAST(CAST($1 AS text) AS integer))) ORDER BY name ASC
`

type FormAvailableClubsRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) FormAvailableClubs(ctx context.Context, currentFormID *string) ([]FormAvailableClubsRow, error) {
	rows, err := q.db.Query(ctx, formAvailableClubs, currentFormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormAvailableClubsRow{}
	for rows.Next() {
		var i FormAvailableClubsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const formByIdentifier = `-- name: FormByIdentifier :one
SELECT id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info FROM custom_forms WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) FormByIdentifier(ctx context.Context, identifier string) (CustomForm, error) {
	row := q.db.QueryRow(ctx, formByIdentifier, identifier)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const listFormsFiltered = `-- name: ListFormsFiltered :many
SELECT id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info FROM custom_forms WHERE (NOT $1::boolean OR feature_id IS NULL)
AND ($2::text IS NULL OR form_name ILIKE '%' || $2::text || '%')
AND ($3::text IS NULL OR feature_type=$3)
AND ($4::text IS NULL OR feature_id=CAST(CAST($4 AS text) AS integer))
AND ($5::boolean IS NULL OR is_active=$5)
ORDER BY created_at DESC LIMIT CAST($7::text AS bigint) OFFSET CAST($6::text AS bigint)
`

type ListFormsFilteredParams struct {
	Unattached  bool    `json:"unattached"`
	Search      *string `json:"search"`
	FeatureType *string `json:"feature_type"`
	FeatureID   *string `json:"feature_id"`
	IsActive    *bool   `json:"is_active"`
	PageOffset  string  `json:"page_offset"`
	PageSize    *string `json:"page_size"`
}

func (q *Queries) ListFormsFiltered(ctx context.Context, arg ListFormsFilteredParams) ([]CustomForm, error) {
	rows, err := q.db.Query(ctx, listFormsFiltered,
		arg.Unattached,
		arg.Search,
		arg.FeatureType,
		arg.FeatureID,
		arg.IsActive,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomForm{}
	for rows.Next() {
		var i CustomForm
		if err := rows.Scan(
			&i.ID,
			&i.FormName,
			&i.FormDescription,
			&i.FeatureID,
			&i.FormSchema,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureType,
			&i.PostSubmissionInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFormByIdentifier = `-- name: LockFormByIdentifier :one
SELECT id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info FROM custom_forms WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockFormByIdentifier(ctx context.Context, identifier string) (CustomForm, error) {
	row := q.db.QueryRow(ctx, lockFormByIdentifier, identifier)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const lockFormClubs = `-- name: LockFormClubs :many
SELECT id, name, description, short_description, logo, media, start_period, end_period, is_show, created_at, updated_at, registration_info, is_registration_open, registration_end_date, club_type FROM clubs WHERE id=ANY(CAST($1::text[] AS integer[])) ORDER BY id ASC FOR UPDATE
`

func (q *Queries) LockFormClubs(ctx context.Context, identifiers []string) ([]Club, error) {
	rows, err := q.db.Query(ctx, lockFormClubs, identifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Club{}
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ShortDescription,
			&i.Logo,
			&i.Media,
			&i.StartPeriod,
			&i.EndPeriod,
			&i.IsShow,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegistrationInfo,
			&i.IsRegistrationOpen,
			&i.RegistrationEndDate,
			&i.ClubType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otherActivityFormExists = `-- name: OtherActivityFormExists :one
SELECT EXISTS(SELECT 1 FROM custom_forms WHERE feature_type='activity_registration' AND feature_id=CAST(CAST($1 AS text) AS integer) AND id <> $2::integer)
`

type OtherActivityFormExistsParams struct {
	Identifier string `json:"identifier"`
	FormID     int32  `json:"form_id"`
}

func (q *Queries) OtherActivityFormExists(ctx context.Context, arg OtherActivityFormExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, otherActivityFormExists, arg.Identifier, arg.FormID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const otherClubFormExists = `-- name: OtherClubFormExists :one
SELECT EXISTS(SELECT 1 FROM custom_forms WHERE feature_type='club_registration' AND feature_id=CAST(CAST($1 AS text) AS integer) AND id <> $2::integer)
`

type OtherClubFormExistsParams struct {
	Identifier string `json:"identifier"`
	FormID     int32  `json:"form_id"`
}

func (q *Queries) OtherClubFormExists(ctx context.Context, arg OtherClubFormExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, otherClubFormExists, arg.Identifier, arg.FormID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const toggleFormActive = `-- name: ToggleFormActive :one
UPDATE custom_forms SET is_active = $1::boolean,updated_at=now() WHERE id = $2::integer RETURNING id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info
`

type ToggleFormActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int32 `json:"id"`
}

func (q *Queries) ToggleFormActive(ctx context.Context, arg ToggleFormActiveParams) (CustomForm, error) {
	row := q.db.QueryRow(ctx, toggleFormActive, arg.IsActive, arg.ID)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}

const updateForm = `-- name: UpdateForm :one
UPDATE custom_forms SET form_name = $1::text,form_description=$2::text,post_submission_info=$3::text,feature_type=$4::text,feature_id=CAST(CAST($5 AS text) AS integer),form_schema=$6::jsonb,is_active=$7::boolean,
updated_at=CASE WHEN ROW(form_name,form_description,post_submission_info,feature_type,feature_id,form_schema,is_active) IS DISTINCT FROM ROW($1::text,$2::text,$3::text,$4::text,CAST(CAST($5 AS text) AS integer),$6::jsonb,$7::boolean) THEN now() ELSE updated_at END WHERE id = $8::integer RETURNING id, form_name, form_description, feature_id, form_schema, is_active, created_at, updated_at, feature_type, post_submission_info
`

type UpdateFormParams struct {
	FormName           string  `json:"form_name"`
	FormDescription    *string `json:"form_description"`
	PostSubmissionInfo *string `json:"post_submission_info"`
	FeatureType        *string `json:"feature_type"`
	FeatureID          *string `json:"feature_id"`
	FormSchema         []byte  `json:"form_schema"`
	IsActive           *bool   `json:"is_active"`
	ID                 int32   `json:"id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (CustomForm, error) {
	row := q.db.QueryRow(ctx, updateForm,
		arg.FormName,
		arg.FormDescription,
		arg.PostSubmissionInfo,
		arg.FeatureType,
		arg.FeatureID,
		arg.FormSchema,
		arg.IsActive,
		arg.ID,
	)
	var i CustomForm
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.FormDescription,
		&i.FeatureID,
		&i.FormSchema,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureType,
		&i.PostSubmissionInfo,
	)
	return i, err
}
