// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identifiers.sql

package dbgen

import (
	"context"
)

const activityByIdentifier = `-- name: ActivityByIdentifier :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ActivityByIdentifier(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, activityByIdentifier, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const activityDetailsByIdentifier = `-- name: ActivityDetailsByIdentifier :one
SELECT a.id, a.name, a.slug, a.description, a.badge, a.activity_start, a.activity_end, a.registration_start, a.registration_end, a.selection_start, a.selection_end, a.activity_type, a.activity_category, a.additional_config, a.minimum_level, a.is_published, a.created_at, a.updated_at, a.is_registration_open, a.club_id, a.certificate_template_id,to_jsonb(c) AS club FROM activities a LEFT JOIN clubs c ON c.id=a.club_id WHERE a.id=CAST(CAST($1 AS text) AS integer)
`

type ActivityDetailsByIdentifierRow struct {
	Activity Activity `json:"activity"`
	Club     []byte   `json:"club"`
}

func (q *Queries) ActivityDetailsByIdentifier(ctx context.Context, identifier string) (ActivityDetailsByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, activityDetailsByIdentifier, identifier)
	var i ActivityDetailsByIdentifierRow
	err := row.Scan(
		&i.Activity.ID,
		&i.Activity.Name,
		&i.Activity.Slug,
		&i.Activity.Description,
		&i.Activity.Badge,
		&i.Activity.ActivityStart,
		&i.Activity.ActivityEnd,
		&i.Activity.RegistrationStart,
		&i.Activity.RegistrationEnd,
		&i.Activity.SelectionStart,
		&i.Activity.SelectionEnd,
		&i.Activity.ActivityType,
		&i.Activity.ActivityCategory,
		&i.Activity.AdditionalConfig,
		&i.Activity.MinimumLevel,
		&i.Activity.IsPublished,
		&i.Activity.CreatedAt,
		&i.Activity.UpdatedAt,
		&i.Activity.IsRegistrationOpen,
		&i.Activity.ClubID,
		&i.Activity.CertificateTemplateID,
		&i.Club,
	)
	return i, err
}

const citiesByProvinceIdentifier = `-- name: CitiesByProvinceIdentifier :many
SELECT id, province_id, name, is_active FROM cities WHERE province_id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CitiesByProvinceIdentifier(ctx context.Context, identifier string) ([]City, error) {
	rows, err := q.db.Query(ctx, citiesByProvinceIdentifier, identifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.Name,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cityByIdentifier = `-- name: CityByIdentifier :one
SELECT id, province_id, name, is_active FROM cities WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) CityByIdentifier(ctx context.Context, identifier string) (City, error) {
	row := q.db.QueryRow(ctx, cityByIdentifier, identifier)
	var i City
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const deleteActivityByIdentifier = `-- name: DeleteActivityByIdentifier :execrows
DELETE FROM activities WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) DeleteActivityByIdentifier(ctx context.Context, identifier string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityByIdentifier, identifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCityByIdentifier = `-- name: DeleteCityByIdentifier :execrows
DELETE FROM cities WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) DeleteCityByIdentifier(ctx context.Context, identifier string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCityByIdentifier, identifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileByIdentifier = `-- name: DeleteProfileByIdentifier :execrows
DELETE FROM profiles WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) DeleteProfileByIdentifier(ctx context.Context, identifier string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileByIdentifier, identifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvinceByIdentifier = `-- name: DeleteProvinceByIdentifier :execrows
DELETE FROM provinces WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) DeleteProvinceByIdentifier(ctx context.Context, identifier string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvinceByIdentifier, identifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUniversityByIdentifier = `-- name: DeleteUniversityByIdentifier :execrows
DELETE FROM universities WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) DeleteUniversityByIdentifier(ctx context.Context, identifier string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUniversityByIdentifier, identifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAdminByIdentifier = `-- name: FindAdminByIdentifier :one
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) FindAdminByIdentifier(ctx context.Context, identifier string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByIdentifier, identifier)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const lockActivityByIdentifier = `-- name: LockActivityByIdentifier :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id = CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockActivityByIdentifier(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, lockActivityByIdentifier, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const lockAdminByIdentifier = `-- name: LockAdminByIdentifier :one
SELECT id, email, password, display_name, created_at, updated_at, is_active, normalized_email, role_code FROM admin_users WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockAdminByIdentifier(ctx context.Context, identifier string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, lockAdminByIdentifier, identifier)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.NormalizedEmail,
		&i.RoleCode,
	)
	return i, err
}

const lockTicketByIdentifier = `-- name: LockTicketByIdentifier :one
SELECT id, number, status, resolution, requester_admin_user_id, requested_role_code, reason, rejection_reason, resolved_by_admin_user_id, resolved_at, cancelled_at, created_at, updated_at FROM tickets WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockTicketByIdentifier(ctx context.Context, identifier string) (Ticket, error) {
	row := q.db.QueryRow(ctx, lockTicketByIdentifier, identifier)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Resolution,
		&i.RequesterAdminUserID,
		&i.RequestedRoleCode,
		&i.Reason,
		&i.RejectionReason,
		&i.ResolvedByAdminUserID,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const profileByIdentifier = `-- name: ProfileByIdentifier :one
SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ProfileByIdentifier(ctx context.Context, identifier string) (Profile, error) {
	row := q.db.QueryRow(ctx, profileByIdentifier, identifier)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.PersonalID,
		&i.Picture,
		&i.Whatsapp,
		&i.Line,
		&i.Instagram,
		&i.Tiktok,
		&i.Linkedin,
		&i.ProvinceID,
		&i.CityID,
		&i.UniversityID,
		&i.Major,
		&i.IntakeYear,
		&i.Level,
		&i.Badges,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.OriginProvinceID,
		&i.OriginCityID,
		&i.Country,
		&i.EducationHistory,
		&i.WorkHistory,
		&i.ExtraData,
	)
	return i, err
}

const profileDetailsByIdentifier = `-- name: ProfileDetailsByIdentifier :many
SELECT p.id, p.user_id, p.name, p.gender, p.personal_id, p.picture, p.whatsapp, p.line, p.instagram, p.tiktok, p.linkedin, p.province_id, p.city_id, p.university_id, p.major, p.intake_year, p.level, p.badges, p.created_at, p.updated_at, p.birth_date, p.origin_province_id, p.origin_city_id, p.country, p.education_history, p.work_history, p.extra_data, (to_jsonb(u)-'password')::jsonb AS public_user,
to_jsonb(province) AS province,to_jsonb(city) AS city,to_jsonb(university) AS university
FROM profiles p LEFT JOIN public_users u ON u.id=p.user_id
LEFT JOIN provinces province ON province.id=p.province_id
LEFT JOIN cities city ON city.id=p.city_id
LEFT JOIN universities university ON university.id=p.university_id
WHERE CASE WHEN $1::boolean THEN p.user_id = CAST(CAST($2 AS text) AS integer) ELSE p.id = CAST(CAST($2 AS text) AS integer) END
`

type ProfileDetailsByIdentifierParams struct {
	ByUser bool   `json:"by_user"`
	ID     string `json:"id"`
}

type ProfileDetailsByIdentifierRow struct {
	Profile    Profile `json:"profile"`
	PublicUser []byte  `json:"public_user"`
	Province   []byte  `json:"province"`
	City       []byte  `json:"city"`
	University []byte  `json:"university"`
}

func (q *Queries) ProfileDetailsByIdentifier(ctx context.Context, arg ProfileDetailsByIdentifierParams) ([]ProfileDetailsByIdentifierRow, error) {
	rows, err := q.db.Query(ctx, profileDetailsByIdentifier, arg.ByUser, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileDetailsByIdentifierRow{}
	for rows.Next() {
		var i ProfileDetailsByIdentifierRow
		if err := rows.Scan(
			&i.Profile.ID,
			&i.Profile.UserID,
			&i.Profile.Name,
			&i.Profile.Gender,
			&i.Profile.PersonalID,
			&i.Profile.Picture,
			&i.Profile.Whatsapp,
			&i.Profile.Line,
			&i.Profile.Instagram,
			&i.Profile.Tiktok,
			&i.Profile.Linkedin,
			&i.Profile.ProvinceID,
			&i.Profile.CityID,
			&i.Profile.UniversityID,
			&i.Profile.Major,
			&i.Profile.IntakeYear,
			&i.Profile.Level,
			&i.Profile.Badges,
			&i.Profile.CreatedAt,
			&i.Profile.UpdatedAt,
			&i.Profile.BirthDate,
			&i.Profile.OriginProvinceID,
			&i.Profile.OriginCityID,
			&i.Profile.Country,
			&i.Profile.EducationHistory,
			&i.Profile.WorkHistory,
			&i.Profile.ExtraData,
			&i.PublicUser,
			&i.Province,
			&i.City,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provinceByIdentifier = `-- name: ProvinceByIdentifier :one
SELECT id, name, is_active FROM provinces WHERE id = CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ProvinceByIdentifier(ctx context.Context, identifier string) (Province, error) {
	row := q.db.QueryRow(ctx, provinceByIdentifier, identifier)
	var i Province
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const publicUserByIdentifier = `-- name: PublicUserByIdentifier :one
SELECT id, email, password, created_at, updated_at, member_id, account_status FROM public_users WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) PublicUserByIdentifier(ctx context.Context, identifier string) (PublicUser, error) {
	row := q.db.QueryRow(ctx, publicUserByIdentifier, identifier)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const ticketByIdentifier = `-- name: TicketByIdentifier :one
SELECT id, number, status, resolution, requester_admin_user_id, requested_role_code, reason, rejection_reason, resolved_by_admin_user_id, resolved_at, cancelled_at, created_at, updated_at FROM tickets WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) TicketByIdentifier(ctx context.Context, identifier string) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketByIdentifier, identifier)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Resolution,
		&i.RequesterAdminUserID,
		&i.RequestedRoleCode,
		&i.Reason,
		&i.RejectionReason,
		&i.ResolvedByAdminUserID,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ticketDetailsByIdentifier = `-- name: TicketDetailsByIdentifier :one
SELECT t.id, t.number, t.status, t.resolution, t.requester_admin_user_id, t.requested_role_code, t.reason, t.rejection_reason, t.resolved_by_admin_user_id, t.resolved_at, t.cancelled_at, t.created_at, t.updated_at, requester.display_name AS requester_name,requester.email AS requester_email,reviewer.display_name AS reviewer_name
FROM tickets t JOIN admin_users requester ON requester.id=t.requester_admin_user_id
LEFT JOIN admin_users reviewer ON reviewer.id=t.resolved_by_admin_user_id WHERE t.id=CAST(CAST($1 AS text) AS integer)
`

type TicketDetailsByIdentifierRow struct {
	Ticket         Ticket  `json:"ticket"`
	RequesterName  *string `json:"requester_name"`
	RequesterEmail string  `json:"requester_email"`
	ReviewerName   *string `json:"reviewer_name"`
}

func (q *Queries) TicketDetailsByIdentifier(ctx context.Context, identifier string) (TicketDetailsByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, ticketDetailsByIdentifier, identifier)
	var i TicketDetailsByIdentifierRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.Number,
		&i.Ticket.Status,
		&i.Ticket.Resolution,
		&i.Ticket.RequesterAdminUserID,
		&i.Ticket.RequestedRoleCode,
		&i.Ticket.Reason,
		&i.Ticket.RejectionReason,
		&i.Ticket.ResolvedByAdminUserID,
		&i.Ticket.ResolvedAt,
		&i.Ticket.CancelledAt,
		&i.Ticket.CreatedAt,
		&i.Ticket.UpdatedAt,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.ReviewerName,
	)
	return i, err
}

const universityByIdentifier = `-- name: UniversityByIdentifier :one
SELECT u.id, u.name, u.province_id, u.is_active, p.id AS parent_id, p.name AS parent_name, p.is_active AS parent_active
FROM universities u LEFT JOIN provinces p ON p.id = u.province_id WHERE u.id = CAST(CAST($1 AS text) AS integer)
`

type UniversityByIdentifierRow struct {
	University   University `json:"university"`
	ParentID     *int32     `json:"parent_id"`
	ParentName   *string    `json:"parent_name"`
	ParentActive *bool      `json:"parent_active"`
}

func (q *Queries) UniversityByIdentifier(ctx context.Context, identifier string) (UniversityByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, universityByIdentifier, identifier)
	var i UniversityByIdentifierRow
	err := row.Scan(
		&i.University.ID,
		&i.University.Name,
		&i.University.ProvinceID,
		&i.University.IsActive,
		&i.ParentID,
		&i.ParentName,
		&i.ParentActive,
	)
	return i, err
}
