// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeActivityRegistration = `-- name: CloseActivityRegistration :many
UPDATE activities SET is_published=false
WHERE is_published=true AND registration_end < $1::date
RETURNING id,slug
`

type CloseActivityRegistrationRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CloseActivityRegistration(ctx context.Context, dollar_1 pgtype.Date) ([]CloseActivityRegistrationRow, error) {
	rows, err := q.db.Query(ctx, closeActivityRegistration, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CloseActivityRegistrationRow{}
	for rows.Next() {
		var i CloseActivityRegistrationRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeClubRegistration = `-- name: CloseClubRegistration :many
UPDATE clubs SET is_registration_open=false
WHERE is_registration_open=true AND registration_end_date IS NOT NULL AND registration_end_date < $1::date
RETURNING id,name,registration_end_date
`

type CloseClubRegistrationRow struct {
	ID                  int32       `json:"id"`
	Name                string      `json:"name"`
	RegistrationEndDate pgtype.Date `json:"registration_end_date"`
}

func (q *Queries) CloseClubRegistration(ctx context.Context, dollar_1 pgtype.Date) ([]CloseClubRegistrationRow, error) {
	rows, err := q.db.Query(ctx, closeClubRegistration, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CloseClubRegistrationRow{}
	for rows.Next() {
		var i CloseClubRegistrationRow
		if err := rows.Scan(&i.ID, &i.Name, &i.RegistrationEndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClubVisibility = `-- name: UpdateClubVisibility :many
UPDATE clubs SET is_show=false
WHERE is_show=true AND end_period IS NOT NULL AND end_period < $1::date
RETURNING id,name,end_period
`

type UpdateClubVisibilityRow struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	EndPeriod pgtype.Date `json:"end_period"`
}

func (q *Queries) UpdateClubVisibility(ctx context.Context, dollar_1 pgtype.Date) ([]UpdateClubVisibilityRow, error) {
	rows, err := q.db.Query(ctx, updateClubVisibility, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateClubVisibilityRow{}
	for rows.Next() {
		var i UpdateClubVisibilityRow
		if err := rows.Scan(&i.ID, &i.Name, &i.EndPeriod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
