// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linked_courses.sql

package dbgen

import (
	"context"
)

const clearClubCourses = `-- name: ClearClubCourses :exec
DELETE FROM club_courses WHERE club_id=$1
`

func (q *Queries) ClearClubCourses(ctx context.Context, clubID int32) error {
	_, err := q.db.Exec(ctx, clearClubCourses, clubID)
	return err
}

const countExistingClubCourses = `-- name: CountExistingClubCourses :one
SELECT count(*) FROM courses WHERE id=ANY($1::integer[])
`

func (q *Queries) CountExistingClubCourses(ctx context.Context, courseIds []int32) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingClubCourses, courseIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLinkedCoursePeople = `-- name: CountLinkedCoursePeople :one
WITH people AS (
 SELECT ar.id, ar.activity_id AS owner_id, 'activity'::text AS kind, ar.user_id,
   COALESCE(p.name, ar.guest_data->>'name', '')::text AS name,
   COALESCE(u.email, ar.guest_data->>'email', '')::text AS email,
   COALESCE(ar.status, '')::text AS registration_status
 FROM activity_registrations ar LEFT JOIN public_users u ON u.id=ar.user_id
 LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=ar.user_id ORDER BY id LIMIT 1) p ON true
 UNION ALL
 SELECT cr.id, cr.club_id, 'club'::text, cr.member_id,
   COALESCE(p.name, '')::text, COALESCE(u.email, '')::text, COALESCE(cr.status, '')::text
 FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id
 LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=cr.member_id ORDER BY id LIMIT 1) p ON true
), progress AS (
 SELECT 'activity'::text AS kind, activity_id AS owner_id, registration_id, course_id, status FROM activity_course_progress
 UNION ALL SELECT 'club'::text, club_id, registration_id, course_id, status FROM club_course_progress
)
SELECT count(*) FROM people
WHERE people.kind = $1::text AND people.owner_id = $2::integer
 AND (people.name ILIKE '%' || $3::text || '%' OR people.email ILIKE '%' || $3::text || '%')
 AND ($4::text = '' OR people.registration_status = $4)
 AND ($5::text = '' OR people.id IN (
 SELECT registration_id FROM progress
 WHERE kind = $1 AND owner_id = $2 AND ($6::integer = 0 OR course_id = $6)
 GROUP BY registration_id
 HAVING ($5 = 'completed' AND bool_and(status = 'completed'))
 OR ($5 = 'incomplete' AND bool_and(status <> 'unverifiable') AND bool_or(status <> 'completed'))
 OR ($5 = 'unverifiable' AND bool_or(status = 'unverifiable'))
 ))
`

type CountLinkedCoursePeopleParams struct {
	Kind               string `json:"kind"`
	OwnerID            int32  `json:"owner_id"`
	Search             string `json:"search"`
	RegistrationStatus string `json:"registration_status"`
	Completion         string `json:"completion"`
	CourseID           int32  `json:"course_id"`
}

func (q *Queries) CountLinkedCoursePeople(ctx context.Context, arg CountLinkedCoursePeopleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkedCoursePeople,
		arg.Kind,
		arg.OwnerID,
		arg.Search,
		arg.RegistrationStatus,
		arg.Completion,
		arg.CourseID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertClubCourses = `-- name: InsertClubCourses :exec
INSERT INTO club_courses(club_id,course_id,position)
SELECT $1, id, ordinality::integer FROM unnest($2::integer[]) WITH ORDINALITY AS selected(id,ordinality)
`

type InsertClubCoursesParams struct {
	ClubID    int32   `json:"club_id"`
	CourseIds []int32 `json:"course_ids"`
}

func (q *Queries) InsertClubCourses(ctx context.Context, arg InsertClubCoursesParams) error {
	_, err := q.db.Exec(ctx, insertClubCourses, arg.ClubID, arg.CourseIds)
	return err
}

const linkedClubCourses = `-- name: LinkedClubCourses :many
SELECT c.id, c.title, c.status, c.summary, c.minimum_level,
 (SELECT count(*)::integer FROM course_lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL) AS lesson_count
FROM club_courses ac JOIN courses c ON c.id=ac.course_id
WHERE ac.club_id=$1 ORDER BY ac.position, ac.course_id
`

type LinkedClubCoursesRow struct {
	ID           int32  `json:"id"`
	Title        string `json:"title"`
	Status       string `json:"status"`
	Summary      string `json:"summary"`
	MinimumLevel int32  `json:"minimum_level"`
	LessonCount  int32  `json:"lesson_count"`
}

func (q *Queries) LinkedClubCourses(ctx context.Context, clubID int32) ([]LinkedClubCoursesRow, error) {
	rows, err := q.db.Query(ctx, linkedClubCourses, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedClubCoursesRow{}
	for rows.Next() {
		var i LinkedClubCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Summary,
			&i.MinimumLevel,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkedCoursePeopleProgress = `-- name: LinkedCoursePeopleProgress :many
SELECT registration_id, course_id, status::text, total_lessons::integer, completed_lessons::integer
FROM (
 SELECT 'activity'::text AS kind, activity_id AS owner_id, registration_id, course_id, position, status, total_lessons, completed_lessons FROM activity_course_progress
 UNION ALL SELECT 'club'::text, club_id, registration_id, course_id, position, status, total_lessons, completed_lessons FROM club_course_progress
) p WHERE kind = $1::text AND owner_id = $2::integer AND registration_id=ANY($3::integer[])
ORDER BY registration_id, position, course_id
`

type LinkedCoursePeopleProgressParams struct {
	Kind            string  `json:"kind"`
	OwnerID         int32   `json:"owner_id"`
	RegistrationIds []int32 `json:"registration_ids"`
}

type LinkedCoursePeopleProgressRow struct {
	RegistrationID   int32  `json:"registration_id"`
	CourseID         int32  `json:"course_id"`
	Status           string `json:"status"`
	TotalLessons     int32  `json:"total_lessons"`
	CompletedLessons int32  `json:"completed_lessons"`
}

func (q *Queries) LinkedCoursePeopleProgress(ctx context.Context, arg LinkedCoursePeopleProgressParams) ([]LinkedCoursePeopleProgressRow, error) {
	rows, err := q.db.Query(ctx, linkedCoursePeopleProgress, arg.Kind, arg.OwnerID, arg.RegistrationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedCoursePeopleProgressRow{}
	for rows.Next() {
		var i LinkedCoursePeopleProgressRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.CourseID,
			&i.Status,
			&i.TotalLessons,
			&i.CompletedLessons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedCoursePeople = `-- name: ListLinkedCoursePeople :many
WITH people AS (
 SELECT ar.id, ar.activity_id AS owner_id, 'activity'::text AS kind, ar.user_id,
   COALESCE(p.name, ar.guest_data->>'name', '')::text AS name,
   COALESCE(u.email, ar.guest_data->>'email', '')::text AS email,
   COALESCE(ar.status, '')::text AS registration_status
 FROM activity_registrations ar LEFT JOIN public_users u ON u.id=ar.user_id
 LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=ar.user_id ORDER BY id LIMIT 1) p ON true
 UNION ALL
 SELECT cr.id, cr.club_id, 'club'::text, cr.member_id,
   COALESCE(p.name, '')::text, COALESCE(u.email, '')::text, COALESCE(cr.status, '')::text
 FROM club_registrations cr LEFT JOIN public_users u ON u.id=cr.member_id
 LEFT JOIN LATERAL (SELECT name FROM profiles WHERE user_id=cr.member_id ORDER BY id LIMIT 1) p ON true
), progress AS (
 SELECT 'activity'::text AS kind, activity_id AS owner_id, registration_id, course_id, status FROM activity_course_progress
 UNION ALL SELECT 'club'::text, club_id, registration_id, course_id, status FROM club_course_progress
)
SELECT id, name, email, registration_status FROM people
WHERE people.kind = $1::text AND people.owner_id = $2::integer
 AND (people.name ILIKE '%' || $3::text || '%' OR people.email ILIKE '%' || $3::text || '%')
 AND ($4::text = '' OR people.registration_status = $4)
 AND ($5::text = '' OR people.id IN (
 SELECT registration_id FROM progress
 WHERE kind = $1 AND owner_id = $2 AND ($6::integer = 0 OR course_id = $6)
 GROUP BY registration_id
 HAVING ($5 = 'completed' AND bool_and(status = 'completed'))
 OR ($5 = 'incomplete' AND bool_and(status <> 'unverifiable') AND bool_or(status <> 'completed'))
 OR ($5 = 'unverifiable' AND bool_or(status = 'unverifiable'))
 ))
ORDER BY name, id LIMIT $8::integer OFFSET $7::integer
`

type ListLinkedCoursePeopleParams struct {
	Kind               string `json:"kind"`
	OwnerID            int32  `json:"owner_id"`
	Search             string `json:"search"`
	RegistrationStatus string `json:"registration_status"`
	Completion         string `json:"completion"`
	CourseID           int32  `json:"course_id"`
	PageOffset         int32  `json:"page_offset"`
	PageLimit          int32  `json:"page_limit"`
}

type ListLinkedCoursePeopleRow struct {
	ID                 int32  `json:"id"`
	Name               string `json:"name"`
	Email              string `json:"email"`
	RegistrationStatus string `json:"registration_status"`
}

func (q *Queries) ListLinkedCoursePeople(ctx context.Context, arg ListLinkedCoursePeopleParams) ([]ListLinkedCoursePeopleRow, error) {
	rows, err := q.db.Query(ctx, listLinkedCoursePeople,
		arg.Kind,
		arg.OwnerID,
		arg.Search,
		arg.RegistrationStatus,
		arg.Completion,
		arg.CourseID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedCoursePeopleRow{}
	for rows.Next() {
		var i ListLinkedCoursePeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegistrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClubCourses = `-- name: LockClubCourses :one
SELECT id FROM clubs WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockClubCourses(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockClubCourses, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}
