// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"
)

const activityByID = `-- name: ActivityByID :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id = $1
`

func (q *Queries) ActivityByID(ctx context.Context, id int32) (Activity, error) {
	row := q.db.QueryRow(ctx, activityByID, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const lockActivity = `-- name: LockActivity :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockActivity(ctx context.Context, id int32) (Activity, error) {
	row := q.db.QueryRow(ctx, lockActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const setActivityConfig = `-- name: SetActivityConfig :exec
UPDATE activities SET additional_config = $2, updated_at = now() WHERE id = $1
`

type SetActivityConfigParams struct {
	ID               int32  `json:"id"`
	AdditionalConfig []byte `json:"additional_config"`
}

func (q *Queries) SetActivityConfig(ctx context.Context, arg SetActivityConfigParams) error {
	_, err := q.db.Exec(ctx, setActivityConfig, arg.ID, arg.AdditionalConfig)
	return err
}

const updateActivityConfig = `-- name: UpdateActivityConfig :one
UPDATE activities SET additional_config=$2,updated_at=now()
WHERE id=$1 AND additional_config IS DISTINCT FROM $2 RETURNING id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id
`

type UpdateActivityConfigParams struct {
	ID               int32  `json:"id"`
	AdditionalConfig []byte `json:"additional_config"`
}

func (q *Queries) UpdateActivityConfig(ctx context.Context, arg UpdateActivityConfigParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivityConfig, arg.ID, arg.AdditionalConfig)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}
