// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateMemberAccount = `-- name: ActivateMemberAccount :exec
UPDATE public_users SET email=$2,password=$3,account_status='active',updated_at=now() WHERE id=$1
`

type ActivateMemberAccountParams struct {
	ID       int32   `json:"id"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}

func (q *Queries) ActivateMemberAccount(ctx context.Context, arg ActivateMemberAccountParams) error {
	_, err := q.db.Exec(ctx, activateMemberAccount, arg.ID, arg.Email, arg.Password)
	return err
}

const createMemberProfile = `-- name: CreateMemberProfile :one
INSERT INTO profiles(user_id,name,gender,personal_id,whatsapp,instagram,tiktok,linkedin,line,birth_date,province_id,city_id,country,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,
CAST(CAST($10 AS text) AS date),CAST(CAST($11 AS text) AS integer),CAST(CAST($12 AS text) AS integer),$13,now(),now())
RETURNING id,user_id,name,gender,personal_id,whatsapp,instagram,tiktok,linkedin,line,birth_date,province_id,city_id,country,created_at,updated_at
`

type CreateMemberProfileParams struct {
	UserID     *int32  `json:"user_id"`
	Name       string  `json:"name"`
	Gender     *string `json:"gender"`
	PersonalID *string `json:"personal_id"`
	Whatsapp   *string `json:"whatsapp"`
	Instagram  *string `json:"instagram"`
	Tiktok     *string `json:"tiktok"`
	Linkedin   *string `json:"linkedin"`
	Line       *string `json:"line"`
	BirthDate  *string `json:"birth_date"`
	ProvinceID *string `json:"province_id"`
	CityID     *string `json:"city_id"`
	Country    *string `json:"country"`
}

type CreateMemberProfileRow struct {
	ID         int32              `json:"id"`
	UserID     *int32             `json:"user_id"`
	Name       string             `json:"name"`
	Gender     *string            `json:"gender"`
	PersonalID *string            `json:"personal_id"`
	Whatsapp   *string            `json:"whatsapp"`
	Instagram  *string            `json:"instagram"`
	Tiktok     *string            `json:"tiktok"`
	Linkedin   *string            `json:"linkedin"`
	Line       *string            `json:"line"`
	BirthDate  pgtype.Date        `json:"birth_date"`
	ProvinceID *int32             `json:"province_id"`
	CityID     *int32             `json:"city_id"`
	Country    *string            `json:"country"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (CreateMemberProfileRow, error) {
	row := q.db.QueryRow(ctx, createMemberProfile,
		arg.UserID,
		arg.Name,
		arg.Gender,
		arg.PersonalID,
		arg.Whatsapp,
		arg.Instagram,
		arg.Tiktok,
		arg.Linkedin,
		arg.Line,
		arg.BirthDate,
		arg.ProvinceID,
		arg.CityID,
		arg.Country,
	)
	var i CreateMemberProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.PersonalID,
		&i.Whatsapp,
		&i.Instagram,
		&i.Tiktok,
		&i.Linkedin,
		&i.Line,
		&i.BirthDate,
		&i.ProvinceID,
		&i.CityID,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMemberUser = `-- name: CreateMemberUser :one
INSERT INTO public_users(email,password,account_status,created_at,updated_at)
VALUES ($1,$2,$3,now(),now()) RETURNING id, email, password, created_at, updated_at, member_id, account_status
`

type CreateMemberUserParams struct {
	Email         *string `json:"email"`
	Password      *string `json:"password"`
	AccountStatus string  `json:"account_status"`
}

func (q *Queries) CreateMemberUser(ctx context.Context, arg CreateMemberUserParams) (PublicUser, error) {
	row := q.db.QueryRow(ctx, createMemberUser, arg.Email, arg.Password, arg.AccountStatus)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const otherPublicUserByEmail = `-- name: OtherPublicUserByEmail :one
SELECT id FROM public_users WHERE email=$1 AND id<>$2
`

type OtherPublicUserByEmailParams struct {
	Email *string `json:"email"`
	ID    int32   `json:"id"`
}

func (q *Queries) OtherPublicUserByEmail(ctx context.Context, arg OtherPublicUserByEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, otherPublicUserByEmail, arg.Email, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const publicUserByEmail = `-- name: PublicUserByEmail :one
SELECT id FROM public_users WHERE email=$1
`

func (q *Queries) PublicUserByEmail(ctx context.Context, email *string) (int32, error) {
	row := q.db.QueryRow(ctx, publicUserByEmail, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const publicUserByID = `-- name: PublicUserByID :one
SELECT id, email, password, created_at, updated_at, member_id, account_status FROM public_users WHERE id=$1
`

func (q *Queries) PublicUserByID(ctx context.Context, id int32) (PublicUser, error) {
	row := q.db.QueryRow(ctx, publicUserByID, id)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const publicUserByMemberNumber = `-- name: PublicUserByMemberNumber :one
SELECT id FROM public_users WHERE member_id=$1
`

func (q *Queries) PublicUserByMemberNumber(ctx context.Context, memberID *string) (int32, error) {
	row := q.db.QueryRow(ctx, publicUserByMemberNumber, memberID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const setMemberNumber = `-- name: SetMemberNumber :one
UPDATE public_users SET member_id=$2,updated_at=now() WHERE id=$1 RETURNING id, email, password, created_at, updated_at, member_id, account_status
`

type SetMemberNumberParams struct {
	ID       int32   `json:"id"`
	MemberID *string `json:"member_id"`
}

func (q *Queries) SetMemberNumber(ctx context.Context, arg SetMemberNumberParams) (PublicUser, error) {
	row := q.db.QueryRow(ctx, setMemberNumber, arg.ID, arg.MemberID)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const updateMemberCredentials = `-- name: UpdateMemberCredentials :one
UPDATE public_users SET email=COALESCE($1::text,email),password=COALESCE($2::text,password),updated_at=now()
WHERE id = $3::integer AND (email IS DISTINCT FROM COALESCE($1::text,email) OR password IS DISTINCT FROM COALESCE($2::text,password)) RETURNING id, email, password, created_at, updated_at, member_id, account_status
`

type UpdateMemberCredentialsParams struct {
	Email    *string `json:"email"`
	Password *string `json:"password"`
	ID       int32   `json:"id"`
}

func (q *Queries) UpdateMemberCredentials(ctx context.Context, arg UpdateMemberCredentialsParams) (PublicUser, error) {
	row := q.db.QueryRow(ctx, updateMemberCredentials, arg.Email, arg.Password, arg.ID)
	var i PublicUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.AccountStatus,
	)
	return i, err
}

const updateMemberPassword = `-- name: UpdateMemberPassword :exec
UPDATE public_users SET password=$2,updated_at=now() WHERE id=$1
`

type UpdateMemberPasswordParams struct {
	ID       int32   `json:"id"`
	Password *string `json:"password"`
}

func (q *Queries) UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error {
	_, err := q.db.Exec(ctx, updateMemberPassword, arg.ID, arg.Password)
	return err
}
