// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID              int32              `json:"id"`
	UserID          *int32             `json:"user_id"`
	Name            *string            `json:"name"`
	Description     *string            `json:"description"`
	AchievementDate pgtype.Date        `json:"achievement_date"`
	Type            *int32             `json:"type"`
	Score           *int32             `json:"score"`
	Proof           *string            `json:"proof"`
	IsProofDeleted  *bool              `json:"is_proof_deleted"`
	Status          *int32             `json:"status"`
	Remark          *string            `json:"remark"`
	ApproverID      *int32             `json:"approver_id"`
	ApprovedAt      pgtype.Date        `json:"approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Activity struct {
	ID                    int32              `json:"id"`
	Name                  string             `json:"name"`
	Slug                  string             `json:"slug"`
	Description           *string            `json:"description"`
	Badge                 *string            `json:"badge"`
	ActivityStart         pgtype.Date        `json:"activity_start"`
	ActivityEnd           pgtype.Date        `json:"activity_end"`
	RegistrationStart     pgtype.Date        `json:"registration_start"`
	RegistrationEnd       pgtype.Date        `json:"registration_end"`
	SelectionStart        pgtype.Date        `json:"selection_start"`
	SelectionEnd          pgtype.Date        `json:"selection_end"`
	ActivityType          *int32             `json:"activity_type"`
	ActivityCategory      *int32             `json:"activity_category"`
	AdditionalConfig      []byte             `json:"additional_config"`
	MinimumLevel          *int32             `json:"minimum_level"`
	IsPublished           *bool              `json:"is_published"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	IsRegistrationOpen    bool               `json:"is_registration_open"`
	ClubID                *int32             `json:"club_id"`
	CertificateTemplateID *int32             `json:"certificate_template_id"`
}

type ActivityRegistration struct {
	ID                  int32              `json:"id"`
	UserID              *int32             `json:"user_id"`
	ActivityID          *int32             `json:"activity_id"`
	Status              *string            `json:"status"`
	QuestionnaireAnswer []byte             `json:"questionnaire_answer"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	GuestData           []byte             `json:"guest_data"`
}

type AdminAuthIdentity struct {
	ID              int32              `json:"id"`
	AdminUserID     int32              `json:"admin_user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Email           string             `json:"email"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AdminRefreshToken struct {
	ID                int32              `json:"id"`
	FamilyID          pgtype.UUID        `json:"family_id"`
	AdminUserID       int32              `json:"admin_user_id"`
	TokenHash         string             `json:"token_hash"`
	ParentTokenID     *int32             `json:"parent_token_id"`
	ReplacedByTokenID *int32             `json:"replaced_by_token_id"`
	UserAgent         *string            `json:"user_agent"`
	IpAddress         *string            `json:"ip_address"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason  *string            `json:"revocation_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID              int32              `json:"id"`
	Email           string             `json:"email"`
	Password        *string            `json:"password"`
	DisplayName     *string            `json:"display_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsActive        bool               `json:"is_active"`
	NormalizedEmail string             `json:"normalized_email"`
	RoleCode        *string            `json:"role_code"`
}

type AdonisSchema struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Batch         int32              `json:"batch"`
	MigrationTime pgtype.Timestamptz `json:"migration_time"`
}

type AdonisSchemaVersion struct {
	Version int32 `json:"version"`
}

type CertificateApproval struct {
	ID             int32              `json:"id"`
	RegistrationID int32              `json:"registration_id"`
	ActivityID     int32              `json:"activity_id"`
	SignerID       int32              `json:"signer_id"`
	RequestedBy    int32              `json:"requested_by"`
	SignerName     string             `json:"signer_name"`
	SignerTitle    string             `json:"signer_title"`
	Snapshot       []byte             `json:"snapshot"`
	ContentHash    string             `json:"content_hash"`
	Status         string             `json:"status"`
	DecidedBy      *int32             `json:"decided_by"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	Reason         *string            `json:"reason"`
	CertificateID  *int32             `json:"certificate_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CertificateTemplate struct {
	ID                     int32              `json:"id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	BackgroundImage        *string            `json:"background_image"`
	TemplateData           []byte             `json:"template_data"`
	IsActive               *bool              `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LifecycleStatus        string             `json:"lifecycle_status"`
	Version                int32              `json:"version"`
	BackgroundAssetVersion int32              `json:"background_asset_version"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
}

type City struct {
	ID         int32   `json:"id"`
	ProvinceID int32   `json:"province_id"`
	Name       *string `json:"name"`
	IsActive   *bool   `json:"is_active"`
}

type Club struct {
	ID                  int32              `json:"id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description"`
	ShortDescription    *string            `json:"short_description"`
	Logo                *string            `json:"logo"`
	Media               []byte             `json:"media"`
	StartPeriod         pgtype.Date        `json:"start_period"`
	EndPeriod           pgtype.Date        `json:"end_period"`
	IsShow              *bool              `json:"is_show"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RegistrationInfo    []byte             `json:"registration_info"`
	IsRegistrationOpen  *bool              `json:"is_registration_open"`
	RegistrationEndDate pgtype.Date        `json:"registration_end_date"`
	ClubType            string             `json:"club_type"`
}

type ClubMemberRole struct {
	ID                 int32              `json:"id"`
	ClubRegistrationID int32              `json:"club_registration_id"`
	RoleName           string             `json:"role_name"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	IsPrimary          bool               `json:"is_primary"`
	SortOrder          int32              `json:"sort_order"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ClubRegistration struct {
	ID             int32              `json:"id"`
	ClubID         *int32             `json:"club_id"`
	MemberID       *int32             `json:"member_id"`
	Status         *string            `json:"status"`
	AdditionalData []byte             `json:"additional_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Country struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

type CustomForm struct {
	ID                 int32              `json:"id"`
	FormName           string             `json:"form_name"`
	FormDescription    *string            `json:"form_description"`
	FeatureID          *int32             `json:"feature_id"`
	FormSchema         []byte             `json:"form_schema"`
	IsActive           *bool              `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FeatureType        *string            `json:"feature_type"`
	PostSubmissionInfo *string            `json:"post_submission_info"`
}

type IssuedCertificate struct {
	ApprovalSnapshot    []byte             `json:"approval_snapshot"`
	ID                  int32              `json:"id"`
	CertificateCode     string             `json:"certificate_code"`
	RegistrationID      int32              `json:"registration_id"`
	ActivityID          int32              `json:"activity_id"`
	UserID              *int32             `json:"user_id"`
	TemplateID          int32              `json:"template_id"`
	TemplateSnapshot    []byte             `json:"template_snapshot"`
	ParticipantSnapshot []byte             `json:"participant_snapshot"`
	IssuedBy            *int32             `json:"issued_by"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason       *string            `json:"revoked_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ActivitySnapshot    []byte             `json:"activity_snapshot"`
	SnapshotVersion     int32              `json:"snapshot_version"`
	TemplateVersion     int32              `json:"template_version"`
	RevokedBy           *int32             `json:"revoked_by"`
}

type LegacyMember struct {
	ID         int32    `json:"id"`
	Name       *string  `json:"name"`
	Gender     *string  `json:"gender"`
	Email      *string  `json:"email"`
	Phone      *string  `json:"phone"`
	LineID     *string  `json:"line_id"`
	IntakeYear *string  `json:"intake_year"`
	Password   *string  `json:"password"`
	Ssc        *float32 `json:"ssc"`
	Lmd        *float32 `json:"lmd"`
	Spectra    *float32 `json:"spectra"`
}

type LifetimeLeaderboard struct {
	ID                  int32              `json:"id"`
	UserID              *int32             `json:"user_id"`
	ScoreAcademic       *int32             `json:"score_academic"`
	ScoreCompetition    *int32             `json:"score_competition"`
	ScoreOrganizational *int32             `json:"score_organizational"`
	Score               *int32             `json:"score"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MonthlyLeaderboard struct {
	ID                  int32              `json:"id"`
	UserID              *int32             `json:"user_id"`
	Month               pgtype.Date        `json:"month"`
	ScoreAcademic       *int32             `json:"score_academic"`
	ScoreCompetition    *int32             `json:"score_competition"`
	ScoreOrganizational *int32             `json:"score_organizational"`
	Score               *int32             `json:"score"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID               int32              `json:"id"`
	UserID           *int32             `json:"user_id"`
	Name             string             `json:"name"`
	Gender           *string            `json:"gender"`
	PersonalID       *string            `json:"personal_id"`
	Picture          *string            `json:"picture"`
	Whatsapp         *string            `json:"whatsapp"`
	Line             *string            `json:"line"`
	Instagram        *string            `json:"instagram"`
	Tiktok           *string            `json:"tiktok"`
	Linkedin         *string            `json:"linkedin"`
	ProvinceID       *int32             `json:"province_id"`
	CityID           *int32             `json:"city_id"`
	UniversityID     *int32             `json:"university_id"`
	Major            *string            `json:"major"`
	IntakeYear       *int32             `json:"intake_year"`
	Level            *int32             `json:"level"`
	Badges           []byte             `json:"badges"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BirthDate        pgtype.Date        `json:"birth_date"`
	OriginProvinceID *int32             `json:"origin_province_id"`
	OriginCityID     *int32             `json:"origin_city_id"`
	Country          *string            `json:"country"`
	EducationHistory []byte             `json:"education_history"`
	WorkHistory      []byte             `json:"work_history"`
	ExtraData        []byte             `json:"extra_data"`
}

type Province struct {
	ID       int32   `json:"id"`
	Name     *string `json:"name"`
	IsActive *bool   `json:"is_active"`
}

type PublicUser struct {
	ID            int32              `json:"id"`
	Email         *string            `json:"email"`
	Password      *string            `json:"password"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MemberID      *string            `json:"member_id"`
	AccountStatus string             `json:"account_status"`
}

type RuangCurhat struct {
	ID                 int32              `json:"id"`
	UserID             *int32             `json:"user_id"`
	ProblemOwnership   *int32             `json:"problem_ownership"`
	OwnerName          *string            `json:"owner_name"`
	ProblemCategory    *string            `json:"problem_category"`
	ProblemDescription *string            `json:"problem_description"`
	HandlingTechnic    *string            `json:"handling_technic"`
	CounselorGender    *string            `json:"counselor_gender"`
	CounselorID        *int32             `json:"counselor_id"`
	Status             *int32             `json:"status"`
	AdditionalNotes    *string            `json:"additional_notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Ticket struct {
	ID                    int32              `json:"id"`
	Number                string             `json:"number"`
	Status                string             `json:"status"`
	Resolution            *string            `json:"resolution"`
	RequesterAdminUserID  int32              `json:"requester_admin_user_id"`
	RequestedRoleCode     string             `json:"requested_role_code"`
	Reason                string             `json:"reason"`
	RejectionReason       *string            `json:"rejection_reason"`
	ResolvedByAdminUserID *int32             `json:"resolved_by_admin_user_id"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	CancelledAt           pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type University struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	ProvinceID *int32 `json:"province_id"`
	IsActive   *bool  `json:"is_active"`
}
