// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package dbgen

import (
	"context"
)

const countProfilesFiltered = `-- name: CountProfilesFiltered :one
SELECT count(*) FROM profiles p LEFT JOIN public_users u ON u.id=p.user_id
WHERE (($1::text <> '' AND p.name ILIKE '%' || $1::text || '%')
OR (($1::text = '' OR u.email ILIKE '%' || $1::text || '%' OR u.member_id ILIKE '%' || $1::text || '%')
AND ($2::text = '' OR u.member_id = $2::text)
AND ($3::text = '' OR EXISTS(SELECT 1 FROM jsonb_array_elements(CASE WHEN jsonb_typeof(p.education_history)='array' THEN p.education_history ELSE '[]'::jsonb END) edu WHERE edu->>'institution' ILIKE '%' || $3::text || '%'))))
AND ($4::text = '' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(CASE WHEN jsonb_typeof(p.badges)='array' THEN p.badges WHEN jsonb_typeof(p.badges)='string' THEN jsonb_build_array(p.badges #>> '{}') ELSE '[]'::jsonb END) badge WHERE badge ILIKE '%' || $4::text || '%'))
`

type CountProfilesFilteredParams struct {
	Search       string `json:"search"`
	MemberNumber string `json:"member_number"`
	Institution  string `json:"institution"`
	Badge        string `json:"badge"`
}

func (q *Queries) CountProfilesFiltered(ctx context.Context, arg CountProfilesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProfilesFiltered,
		arg.Search,
		arg.MemberNumber,
		arg.Institution,
		arg.Badge,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM profiles WHERE id=$1
`

func (q *Queries) DeleteProfile(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProfilesFiltered = `-- name: ListProfilesFiltered :many
SELECT p.id, p.user_id, p.name, p.gender, p.personal_id, p.picture, p.whatsapp, p.line, p.instagram, p.tiktok, p.linkedin, p.province_id, p.city_id, p.university_id, p.major, p.intake_year, p.level, p.badges, p.created_at, p.updated_at, p.birth_date, p.origin_province_id, p.origin_city_id, p.country, p.education_history, p.work_history, p.extra_data, (to_jsonb(u)-'password')::jsonb AS public_user FROM profiles p LEFT JOIN public_users u ON u.id=p.user_id
WHERE (($1::text <> '' AND p.name ILIKE '%' || $1::text || '%')
OR (($1::text = '' OR u.email ILIKE '%' || $1::text || '%' OR u.member_id ILIKE '%' || $1::text || '%')
AND ($2::text = '' OR u.member_id = $2::text)
AND ($3::text = '' OR EXISTS(SELECT 1 FROM jsonb_array_elements(CASE WHEN jsonb_typeof(p.education_history)='array' THEN p.education_history ELSE '[]'::jsonb END) edu WHERE edu->>'institution' ILIKE '%' || $3::text || '%'))))
AND ($4::text = '' OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(CASE WHEN jsonb_typeof(p.badges)='array' THEN p.badges WHEN jsonb_typeof(p.badges)='string' THEN jsonb_build_array(p.badges #>> '{}') ELSE '[]'::jsonb END) badge WHERE badge ILIKE '%' || $4::text || '%'))
ORDER BY p.name ASC LIMIT $6::bigint OFFSET $5::bigint
`

type ListProfilesFilteredParams struct {
	Search       string `json:"search"`
	MemberNumber string `json:"member_number"`
	Institution  string `json:"institution"`
	Badge        string `json:"badge"`
	PageOffset   int64  `json:"page_offset"`
	PageSize     *int64 `json:"page_size"`
}

type ListProfilesFilteredRow struct {
	Profile    Profile `json:"profile"`
	PublicUser []byte  `json:"public_user"`
}

func (q *Queries) ListProfilesFiltered(ctx context.Context, arg ListProfilesFilteredParams) ([]ListProfilesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listProfilesFiltered,
		arg.Search,
		arg.MemberNumber,
		arg.Institution,
		arg.Badge,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesFilteredRow{}
	for rows.Next() {
		var i ListProfilesFilteredRow
		if err := rows.Scan(
			&i.Profile.ID,
			&i.Profile.UserID,
			&i.Profile.Name,
			&i.Profile.Gender,
			&i.Profile.PersonalID,
			&i.Profile.Picture,
			&i.Profile.Whatsapp,
			&i.Profile.Line,
			&i.Profile.Instagram,
			&i.Profile.Tiktok,
			&i.Profile.Linkedin,
			&i.Profile.ProvinceID,
			&i.Profile.CityID,
			&i.Profile.UniversityID,
			&i.Profile.Major,
			&i.Profile.IntakeYear,
			&i.Profile.Level,
			&i.Profile.Badges,
			&i.Profile.CreatedAt,
			&i.Profile.UpdatedAt,
			&i.Profile.BirthDate,
			&i.Profile.OriginProvinceID,
			&i.Profile.OriginCityID,
			&i.Profile.Country,
			&i.Profile.EducationHistory,
			&i.Profile.WorkHistory,
			&i.Profile.ExtraData,
			&i.PublicUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileByID = `-- name: ProfileByID :one
SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE id=$1
`

func (q *Queries) ProfileByID(ctx context.Context, id int32) (Profile, error) {
	row := q.db.QueryRow(ctx, profileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.PersonalID,
		&i.Picture,
		&i.Whatsapp,
		&i.Line,
		&i.Instagram,
		&i.Tiktok,
		&i.Linkedin,
		&i.ProvinceID,
		&i.CityID,
		&i.UniversityID,
		&i.Major,
		&i.IntakeYear,
		&i.Level,
		&i.Badges,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.OriginProvinceID,
		&i.OriginCityID,
		&i.Country,
		&i.EducationHistory,
		&i.WorkHistory,
		&i.ExtraData,
	)
	return i, err
}

const profileDetails = `-- name: ProfileDetails :many
SELECT p.id, p.user_id, p.name, p.gender, p.personal_id, p.picture, p.whatsapp, p.line, p.instagram, p.tiktok, p.linkedin, p.province_id, p.city_id, p.university_id, p.major, p.intake_year, p.level, p.badges, p.created_at, p.updated_at, p.birth_date, p.origin_province_id, p.origin_city_id, p.country, p.education_history, p.work_history, p.extra_data, (to_jsonb(u)-'password')::jsonb AS public_user,
to_jsonb(province) AS province,to_jsonb(city) AS city,to_jsonb(university) AS university
FROM profiles p LEFT JOIN public_users u ON u.id=p.user_id
LEFT JOIN provinces province ON province.id=p.province_id
LEFT JOIN cities city ON city.id=p.city_id
LEFT JOIN universities university ON university.id=p.university_id
WHERE CASE WHEN $1::boolean THEN p.user_id = $2::integer ELSE p.id = $2::integer END
`

type ProfileDetailsParams struct {
	ByUser bool  `json:"by_user"`
	ID     int32 `json:"id"`
}

type ProfileDetailsRow struct {
	Profile    Profile `json:"profile"`
	PublicUser []byte  `json:"public_user"`
	Province   []byte  `json:"province"`
	City       []byte  `json:"city"`
	University []byte  `json:"university"`
}

func (q *Queries) ProfileDetails(ctx context.Context, arg ProfileDetailsParams) ([]ProfileDetailsRow, error) {
	rows, err := q.db.Query(ctx, profileDetails, arg.ByUser, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileDetailsRow{}
	for rows.Next() {
		var i ProfileDetailsRow
		if err := rows.Scan(
			&i.Profile.ID,
			&i.Profile.UserID,
			&i.Profile.Name,
			&i.Profile.Gender,
			&i.Profile.PersonalID,
			&i.Profile.Picture,
			&i.Profile.Whatsapp,
			&i.Profile.Line,
			&i.Profile.Instagram,
			&i.Profile.Tiktok,
			&i.Profile.Linkedin,
			&i.Profile.ProvinceID,
			&i.Profile.CityID,
			&i.Profile.UniversityID,
			&i.Profile.Major,
			&i.Profile.IntakeYear,
			&i.Profile.Level,
			&i.Profile.Badges,
			&i.Profile.CreatedAt,
			&i.Profile.UpdatedAt,
			&i.Profile.BirthDate,
			&i.Profile.OriginProvinceID,
			&i.Profile.OriginCityID,
			&i.Profile.Country,
			&i.Profile.EducationHistory,
			&i.Profile.WorkHistory,
			&i.Profile.ExtraData,
			&i.PublicUser,
			&i.Province,
			&i.City,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberProfile = `-- name: UpdateMemberProfile :one
UPDATE profiles SET
name = COALESCE($1::text,name),
gender = COALESCE($2::text,gender),
personal_id = COALESCE($3::text,personal_id),
whatsapp = COALESCE($4::text,whatsapp),
line = COALESCE($5::text,line),
instagram = COALESCE($6::text,instagram),
tiktok = COALESCE($7::text,tiktok),
linkedin = COALESCE($8::text,linkedin),
province_id = COALESCE(CAST(CAST($9 AS text) AS integer),province_id),
city_id = COALESCE(CAST(CAST($10 AS text) AS integer),city_id),
level = COALESCE(CAST(CAST($11 AS text) AS integer),level),
birth_date = COALESCE(CAST(CAST($12 AS text) AS date),birth_date),
origin_province_id = COALESCE(CAST(CAST($13 AS text) AS integer),origin_province_id),
origin_city_id = COALESCE(CAST(CAST($14 AS text) AS integer),origin_city_id),
country = COALESCE($15::text,country),
badges = COALESCE($16::jsonb,badges),
education_history = COALESCE($17::jsonb,education_history),
work_history = COALESCE($18::jsonb,work_history),
extra_data = COALESCE($19::jsonb,extra_data),
updated_at=now()
WHERE id = $20::integer AND ($12::text IS NOT NULL OR
ROW(name,gender,personal_id,whatsapp,line,instagram,tiktok,linkedin,province_id,city_id,level,birth_date,origin_province_id,origin_city_id,country,badges,education_history,work_history,extra_data) IS DISTINCT FROM
ROW(COALESCE($1::text,name),COALESCE($2::text,gender),COALESCE($3::text,personal_id),COALESCE($4::text,whatsapp),COALESCE($5::text,line),COALESCE($6::text,instagram),COALESCE($7::text,tiktok),COALESCE($8::text,linkedin),COALESCE(CAST(CAST($9 AS text) AS integer),province_id),COALESCE(CAST(CAST($10 AS text) AS integer),city_id),COALESCE(CAST(CAST($11 AS text) AS integer),level),COALESCE(CAST(CAST($12 AS text) AS date),birth_date),COALESCE(CAST(CAST($13 AS text) AS integer),origin_province_id),COALESCE(CAST(CAST($14 AS text) AS integer),origin_city_id),COALESCE($15::text,country),COALESCE($16::jsonb,badges),COALESCE($17::jsonb,education_history),COALESCE($18::jsonb,work_history),COALESCE($19::jsonb,extra_data))) RETURNING id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data
`

type UpdateMemberProfileParams struct {
	Name             *string `json:"name"`
	Gender           *string `json:"gender"`
	PersonalID       *string `json:"personal_id"`
	Whatsapp         *string `json:"whatsapp"`
	Line             *string `json:"line"`
	Instagram        *string `json:"instagram"`
	Tiktok           *string `json:"tiktok"`
	Linkedin         *string `json:"linkedin"`
	ProvinceID       *string `json:"province_id"`
	CityID           *string `json:"city_id"`
	Level            *string `json:"level"`
	BirthDate        *string `json:"birth_date"`
	OriginProvinceID *string `json:"origin_province_id"`
	OriginCityID     *string `json:"origin_city_id"`
	Country          *string `json:"country"`
	Badges           []byte  `json:"badges"`
	EducationHistory []byte  `json:"education_history"`
	WorkHistory      []byte  `json:"work_history"`
	ExtraData        []byte  `json:"extra_data"`
	ID               int32   `json:"id"`
}

func (q *Queries) UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateMemberProfile,
		arg.Name,
		arg.Gender,
		arg.PersonalID,
		arg.Whatsapp,
		arg.Line,
		arg.Instagram,
		arg.Tiktok,
		arg.Linkedin,
		arg.ProvinceID,
		arg.CityID,
		arg.Level,
		arg.BirthDate,
		arg.OriginProvinceID,
		arg.OriginCityID,
		arg.Country,
		arg.Badges,
		arg.EducationHistory,
		arg.WorkHistory,
		arg.ExtraData,
		arg.ID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.PersonalID,
		&i.Picture,
		&i.Whatsapp,
		&i.Line,
		&i.Instagram,
		&i.Tiktok,
		&i.Linkedin,
		&i.ProvinceID,
		&i.CityID,
		&i.UniversityID,
		&i.Major,
		&i.IntakeYear,
		&i.Level,
		&i.Badges,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.OriginProvinceID,
		&i.OriginCityID,
		&i.Country,
		&i.EducationHistory,
		&i.WorkHistory,
		&i.ExtraData,
	)
	return i, err
}
