// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package dbgen

import (
	"context"
)

const citiesByProvince = `-- name: CitiesByProvince :many
SELECT id, province_id, name, is_active FROM cities WHERE province_id = $1
`

func (q *Queries) CitiesByProvince(ctx context.Context, provinceID int32) ([]City, error) {
	rows, err := q.db.Query(ctx, citiesByProvince, provinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.Name,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cityByID = `-- name: CityByID :one
SELECT id, province_id, name, is_active FROM cities WHERE id = $1
`

func (q *Queries) CityByID(ctx context.Context, id int32) (City, error) {
	row := q.db.QueryRow(ctx, cityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const countProfilesByGender = `-- name: CountProfilesByGender :many
SELECT count(id)::text AS profile_amounts, gender FROM profiles GROUP BY gender
`

type CountProfilesByGenderRow struct {
	ProfileAmounts string  `json:"profile_amounts"`
	Gender         *string `json:"gender"`
}

func (q *Queries) CountProfilesByGender(ctx context.Context) ([]CountProfilesByGenderRow, error) {
	rows, err := q.db.Query(ctx, countProfilesByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProfilesByGenderRow{}
	for rows.Next() {
		var i CountProfilesByGenderRow
		if err := rows.Scan(&i.ProfileAmounts, &i.Gender); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProfilesByLevel = `-- name: CountProfilesByLevel :many
SELECT count(id)::text AS profile_amounts, level FROM profiles GROUP BY level
`

type CountProfilesByLevelRow struct {
	ProfileAmounts string `json:"profile_amounts"`
	Level          *int32 `json:"level"`
}

func (q *Queries) CountProfilesByLevel(ctx context.Context) ([]CountProfilesByLevelRow, error) {
	rows, err := q.db.Query(ctx, countProfilesByLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProfilesByLevelRow{}
	for rows.Next() {
		var i CountProfilesByLevelRow
		if err := rows.Scan(&i.ProfileAmounts, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUniversities = `-- name: CountUniversities :one
SELECT count(*) FROM universities WHERE name ILIKE $1::text
`

func (q *Queries) CountUniversities(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUniversities, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities(name, province_id) VALUES ($1, CAST(CAST($2 AS text) AS integer))
RETURNING id, name, province_id
`

type CreateCityParams struct {
	Name       *string `json:"name"`
	ProvinceID *string `json:"province_id"`
}

type CreateCityRow struct {
	ID         int32   `json:"id"`
	Name       *string `json:"name"`
	ProvinceID int32   `json:"province_id"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (CreateCityRow, error) {
	row := q.db.QueryRow(ctx, createCity, arg.Name, arg.ProvinceID)
	var i CreateCityRow
	err := row.Scan(&i.ID, &i.Name, &i.ProvinceID)
	return i, err
}

const createProvince = `-- name: CreateProvince :one
INSERT INTO provinces(name) VALUES ($1) RETURNING id, name
`

type CreateProvinceRow struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

func (q *Queries) CreateProvince(ctx context.Context, name *string) (CreateProvinceRow, error) {
	row := q.db.QueryRow(ctx, createProvince, name)
	var i CreateProvinceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createUniversity = `-- name: CreateUniversity :one
INSERT INTO universities(name, province_id) VALUES ($1, CAST(CAST($2 AS text) AS integer))
RETURNING id, name, province_id
`

type CreateUniversityParams struct {
	Name       string `json:"name"`
	ProvinceID string `json:"province_id"`
}

type CreateUniversityRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	ProvinceID *int32 `json:"province_id"`
}

func (q *Queries) CreateUniversity(ctx context.Context, arg CreateUniversityParams) (CreateUniversityRow, error) {
	row := q.db.QueryRow(ctx, createUniversity, arg.Name, arg.ProvinceID)
	var i CreateUniversityRow
	err := row.Scan(&i.ID, &i.Name, &i.ProvinceID)
	return i, err
}

const dashboardStats = `-- name: DashboardStats :one
SELECT (SELECT count(*) FROM profiles) AS "totalProfiles", (SELECT count(*) FROM activities) AS "totalActivities",
(SELECT count(*) FROM clubs) AS "totalClubs", (SELECT count(*) FROM ruang_curhats) AS "totalRuangCurhats"
`

type DashboardStatsRow struct {
	TotalProfiles     int64 `json:"totalProfiles"`
	TotalActivities   int64 `json:"totalActivities"`
	TotalClubs        int64 `json:"totalClubs"`
	TotalRuangCurhats int64 `json:"totalRuangCurhats"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.TotalProfiles,
		&i.TotalActivities,
		&i.TotalClubs,
		&i.TotalRuangCurhats,
	)
	return i, err
}

const deleteCity = `-- name: DeleteCity :execrows
DELETE FROM cities WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvince = `-- name: DeleteProvince :execrows
DELETE FROM provinces WHERE id = $1
`

func (q *Queries) DeleteProvince(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvince, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUniversity = `-- name: DeleteUniversity :execrows
DELETE FROM universities WHERE id = $1
`

func (q *Queries) DeleteUniversity(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUniversity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCities = `-- name: ListCities :many
SELECT id, province_id, name, is_active FROM cities
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.Name,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, code FROM countries ORDER BY name ASC
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvinces = `-- name: ListProvinces :many
SELECT id, name, is_active FROM provinces
`

func (q *Queries) ListProvinces(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvinces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.ID, &i.Name, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniversities = `-- name: ListUniversities :many
SELECT u.id, u.name, u.province_id, u.is_active, p.id AS parent_id, p.name AS parent_name, p.is_active AS parent_active
FROM universities u LEFT JOIN provinces p ON p.id = u.province_id
WHERE u.name ILIKE $1::text ORDER BY u.name ASC LIMIT CAST($3::text AS bigint) OFFSET CAST($2::text AS bigint)
`

type ListUniversitiesParams struct {
	Search     string  `json:"search"`
	PageOffset string  `json:"page_offset"`
	PageSize   *string `json:"page_size"`
}

type ListUniversitiesRow struct {
	University   University `json:"university"`
	ParentID     *int32     `json:"parent_id"`
	ParentName   *string    `json:"parent_name"`
	ParentActive *bool      `json:"parent_active"`
}

func (q *Queries) ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]ListUniversitiesRow, error) {
	rows, err := q.db.Query(ctx, listUniversities, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUniversitiesRow{}
	for rows.Next() {
		var i ListUniversitiesRow
		if err := rows.Scan(
			&i.University.ID,
			&i.University.Name,
			&i.University.ProvinceID,
			&i.University.IsActive,
			&i.ParentID,
			&i.ParentName,
			&i.ParentActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provinceByID = `-- name: ProvinceByID :one
SELECT id, name, is_active FROM provinces WHERE id = $1
`

func (q *Queries) ProvinceByID(ctx context.Context, id int32) (Province, error) {
	row := q.db.QueryRow(ctx, provinceByID, id)
	var i Province
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const universityByID = `-- name: UniversityByID :one
SELECT u.id, u.name, u.province_id, u.is_active, p.id AS parent_id, p.name AS parent_name, p.is_active AS parent_active
FROM universities u LEFT JOIN provinces p ON p.id = u.province_id WHERE u.id = $1
`

type UniversityByIDRow struct {
	University   University `json:"university"`
	ParentID     *int32     `json:"parent_id"`
	ParentName   *string    `json:"parent_name"`
	ParentActive *bool      `json:"parent_active"`
}

func (q *Queries) UniversityByID(ctx context.Context, id int32) (UniversityByIDRow, error) {
	row := q.db.QueryRow(ctx, universityByID, id)
	var i UniversityByIDRow
	err := row.Scan(
		&i.University.ID,
		&i.University.Name,
		&i.University.ProvinceID,
		&i.University.IsActive,
		&i.ParentID,
		&i.ParentName,
		&i.ParentActive,
	)
	return i, err
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities SET name = $1,
province_id = CASE WHEN $2::boolean THEN CAST(CAST($3 AS text) AS integer) ELSE province_id END
WHERE id = $4 RETURNING id, province_id, name, is_active
`

type UpdateCityParams struct {
	Name            *string `json:"name"`
	ProvincePresent bool    `json:"province_present"`
	ProvinceID      *string `json:"province_id"`
	ID              int32   `json:"id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity,
		arg.Name,
		arg.ProvincePresent,
		arg.ProvinceID,
		arg.ID,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const updateProvince = `-- name: UpdateProvince :one
UPDATE provinces SET name = $2 WHERE id = $1 RETURNING id, name, is_active
`

type UpdateProvinceParams struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

func (q *Queries) UpdateProvince(ctx context.Context, arg UpdateProvinceParams) (Province, error) {
	row := q.db.QueryRow(ctx, updateProvince, arg.ID, arg.Name)
	var i Province
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const updateUniversity = `-- name: UpdateUniversity :one
UPDATE universities SET name = $1, province_id = CAST(CAST($2 AS text) AS integer) WHERE id = $3 RETURNING id, name, province_id, is_active
`

type UpdateUniversityParams struct {
	Name       string `json:"name"`
	ProvinceID string `json:"province_id"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) (University, error) {
	row := q.db.QueryRow(ctx, updateUniversity, arg.Name, arg.ProvinceID, arg.ID)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProvinceID,
		&i.IsActive,
	)
	return i, err
}
