// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_list.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRegistrationsFiltered = `-- name: CountRegistrationsFiltered :one
SELECT count(*) FROM activity_registrations ar LEFT JOIN public_users u ON u.id=ar.user_id LEFT JOIN profiles p ON p.user_id=ar.user_id
WHERE ar.activity_id = $1::integer
AND ($2::text IS NULL OR p.name ILIKE '%'||$2||'%' OR u.email ILIKE '%'||$2||'%' OR ar.guest_data->>'name' ILIKE '%'||$2||'%' OR ar.guest_data->>'email' ILIKE '%'||$2||'%')
AND ($3::text IS NULL OR ar.status ILIKE '%'||$3||'%')
AND ($4::text IS NULL OR p.university_id=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR p.province_id=CAST(CAST($5 AS text) AS integer))
AND ($6::text IS NULL OR p.intake_year=CAST(CAST($6 AS text) AS integer))
`

type CountRegistrationsFilteredParams struct {
	ActivityID   int32   `json:"activity_id"`
	Search       *string `json:"search"`
	Status       *string `json:"status"`
	UniversityID *string `json:"university_id"`
	ProvinceID   *string `json:"province_id"`
	IntakeYear   *string `json:"intake_year"`
}

func (q *Queries) CountRegistrationsFiltered(ctx context.Context, arg CountRegistrationsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistrationsFiltered,
		arg.ActivityID,
		arg.Search,
		arg.Status,
		arg.UniversityID,
		arg.ProvinceID,
		arg.IntakeYear,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRegistrationsFiltered = `-- name: ListRegistrationsFiltered :many
SELECT ar.id,u.id AS user_id,COALESCE(u.email,ar.guest_data->>'email') AS email,to_jsonb(COALESCE(p.name,ar.guest_data->>'name')) AS name_json,p.level,p.university_id,p.province_id,p.intake_year,p.major,COALESCE(p.gender,ar.guest_data->>'gender') AS gender,COALESCE(p.whatsapp,ar.guest_data->>'whatsapp') AS whatsapp,p.instagram,p.line,p.personal_id,p.education_history,ar.guest_data,ar.status,ar.created_at,to_jsonb(p) AS profile
FROM activity_registrations ar LEFT JOIN public_users u ON u.id=ar.user_id LEFT JOIN profiles p ON p.user_id=ar.user_id
WHERE ar.activity_id = $1::integer
AND ($2::text IS NULL OR p.name ILIKE '%'||$2||'%' OR u.email ILIKE '%'||$2||'%' OR ar.guest_data->>'name' ILIKE '%'||$2||'%' OR ar.guest_data->>'email' ILIKE '%'||$2||'%')
AND ($3::text IS NULL OR ar.status ILIKE '%'||$3||'%')
AND ($4::text IS NULL OR p.university_id=CAST(CAST($4 AS text) AS integer))
AND ($5::text IS NULL OR p.province_id=CAST(CAST($5 AS text) AS integer))
AND ($6::text IS NULL OR p.intake_year=CAST(CAST($6 AS text) AS integer))
ORDER BY CASE WHEN $7::text='created_at' AND $8::boolean=true THEN ar.created_at END ASC NULLS LAST,
CASE WHEN $7::text='name' AND $8::boolean=true THEN p.name END ASC NULLS LAST,
CASE WHEN $7::text='email' AND $8::boolean=true THEN u.email END ASC NULLS LAST,
CASE WHEN $7::text='status' AND $8::boolean=true THEN ar.status END ASC NULLS LAST,
CASE WHEN $7::text='level' AND $8::boolean=true THEN p.level END ASC NULLS LAST,
CASE WHEN $7::text='university_id' AND $8::boolean=true THEN p.university_id END ASC NULLS LAST,
CASE WHEN $7::text='province_id' AND $8::boolean=true THEN p.province_id END ASC NULLS LAST,
CASE WHEN $7::text='intake_year' AND $8::boolean=true THEN p.intake_year END ASC NULLS LAST,
CASE WHEN $7::text='major' AND $8::boolean=true THEN p.major END ASC NULLS LAST,
CASE WHEN $7::text='whatsapp' AND $8::boolean=true THEN p.whatsapp END ASC NULLS LAST,
CASE WHEN $8::boolean=true THEN ar.id END ASC,
CASE WHEN $7::text='created_at' AND $8::boolean=false THEN ar.created_at END DESC NULLS LAST,
CASE WHEN $7::text='name' AND $8::boolean=false THEN p.name END DESC NULLS LAST,
CASE WHEN $7::text='email' AND $8::boolean=false THEN u.email END DESC NULLS LAST,
CASE WHEN $7::text='status' AND $8::boolean=false THEN ar.status END DESC NULLS LAST,
CASE WHEN $7::text='level' AND $8::boolean=false THEN p.level END DESC NULLS LAST,
CASE WHEN $7::text='university_id' AND $8::boolean=false THEN p.university_id END DESC NULLS LAST,
CASE WHEN $7::text='province_id' AND $8::boolean=false THEN p.province_id END DESC NULLS LAST,
CASE WHEN $7::text='intake_year' AND $8::boolean=false THEN p.intake_year END DESC NULLS LAST,
CASE WHEN $7::text='major' AND $8::boolean=false THEN p.major END DESC NULLS LAST,
CASE WHEN $7::text='whatsapp' AND $8::boolean=false THEN p.whatsapp END DESC NULLS LAST,
CASE WHEN $8::boolean=false THEN ar.id END DESC
LIMIT $10::bigint OFFSET $9::bigint
`

type ListRegistrationsFilteredParams struct {
	ActivityID   int32   `json:"activity_id"`
	Search       *string `json:"search"`
	Status       *string `json:"status"`
	UniversityID *string `json:"university_id"`
	ProvinceID   *string `json:"province_id"`
	IntakeYear   *string `json:"intake_year"`
	SortBy       string  `json:"sort_by"`
	Ascending    bool    `json:"ascending"`
	PageOffset   int64   `json:"page_offset"`
	PageSize     *int64  `json:"page_size"`
}

type ListRegistrationsFilteredRow struct {
	ID               int32              `json:"id"`
	UserID           *int32             `json:"user_id"`
	Email            *string            `json:"email"`
	NameJson         []byte             `json:"name_json"`
	Level            *int32             `json:"level"`
	UniversityID     *int32             `json:"university_id"`
	ProvinceID       *int32             `json:"province_id"`
	IntakeYear       *int32             `json:"intake_year"`
	Major            *string            `json:"major"`
	Gender           *string            `json:"gender"`
	Whatsapp         *string            `json:"whatsapp"`
	Instagram        *string            `json:"instagram"`
	Line             *string            `json:"line"`
	PersonalID       *string            `json:"personal_id"`
	EducationHistory []byte             `json:"education_history"`
	GuestData        []byte             `json:"guest_data"`
	Status           *string            `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Profile          []byte             `json:"profile"`
}

func (q *Queries) ListRegistrationsFiltered(ctx context.Context, arg ListRegistrationsFilteredParams) ([]ListRegistrationsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationsFiltered,
		arg.ActivityID,
		arg.Search,
		arg.Status,
		arg.UniversityID,
		arg.ProvinceID,
		arg.IntakeYear,
		arg.SortBy,
		arg.Ascending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistrationsFilteredRow{}
	for rows.Next() {
		var i ListRegistrationsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.NameJson,
			&i.Level,
			&i.UniversityID,
			&i.ProvinceID,
			&i.IntakeYear,
			&i.Major,
			&i.Gender,
			&i.Whatsapp,
			&i.Instagram,
			&i.Line,
			&i.PersonalID,
			&i.EducationHistory,
			&i.GuestData,
			&i.Status,
			&i.CreatedAt,
			&i.Profile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
