// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registrations.sql

package dbgen

import (
	"context"
)

const activityForRegistration = `-- name: ActivityForRegistration :one
SELECT a.id, a.name, a.slug, a.description, a.badge, a.activity_start, a.activity_end, a.registration_start, a.registration_end, a.selection_start, a.selection_end, a.activity_type, a.activity_category, a.additional_config, a.minimum_level, a.is_published, a.created_at, a.updated_at, a.is_registration_open, a.club_id, a.certificate_template_id FROM activities a JOIN activity_registrations ar ON a.id=ar.activity_id WHERE ar.id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ActivityForRegistration(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, activityForRegistration, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const activityRegistrationByID = `-- name: ActivityRegistrationByID :one
SELECT id, user_id, activity_id, status, questionnaire_answer, created_at, updated_at, guest_data FROM activity_registrations WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ActivityRegistrationByID(ctx context.Context, identifier string) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, activityRegistrationByID, identifier)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Status,
		&i.QuestionnaireAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestData,
	)
	return i, err
}

const changeRegistrationStatusBulk = `-- name: ChangeRegistrationStatusBulk :execrows
UPDATE activity_registrations SET status = $1::text WHERE activity_id = CAST(CAST($2 AS text) AS integer) AND ($3::text IS NULL OR status=$3::text)
`

type ChangeRegistrationStatusBulkParams struct {
	NewStatus     string  `json:"new_status"`
	ActivityID    string  `json:"activity_id"`
	CurrentStatus *string `json:"current_status"`
}

func (q *Queries) ChangeRegistrationStatusBulk(ctx context.Context, arg ChangeRegistrationStatusBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeRegistrationStatusBulk, arg.NewStatus, arg.ActivityID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const changeRegistrationStatusByIDs = `-- name: ChangeRegistrationStatusByIDs :execrows
UPDATE activity_registrations SET status = $1::text WHERE id=ANY(CAST(CAST($2 AS text[]) AS integer[]))
`

type ChangeRegistrationStatusByIDsParams struct {
	Status string   `json:"status"`
	Ids    []string `json:"ids"`
}

func (q *Queries) ChangeRegistrationStatusByIDs(ctx context.Context, arg ChangeRegistrationStatusByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeRegistrationStatusByIDs, arg.Status, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const changeRegistrationStatusByUsers = `-- name: ChangeRegistrationStatusByUsers :execrows
UPDATE activity_registrations SET status=$1 WHERE activity_id=$2 AND user_id=ANY($3::integer[])
`

type ChangeRegistrationStatusByUsersParams struct {
	Status     *string `json:"status"`
	ActivityID *int32  `json:"activity_id"`
	Column3    []int32 `json:"column_3"`
}

func (q *Queries) ChangeRegistrationStatusByUsers(ctx context.Context, arg ChangeRegistrationStatusByUsersParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeRegistrationStatusByUsers, arg.Status, arg.ActivityID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMemberRegistrations = `-- name: CountMemberRegistrations :one
SELECT count(*) FROM activity_registrations WHERE user_id IS NOT DISTINCT FROM $1::integer AND activity_id = $2::integer
`

type CountMemberRegistrationsParams struct {
	UserID     *int32 `json:"user_id"`
	ActivityID int32  `json:"activity_id"`
}

func (q *Queries) CountMemberRegistrations(ctx context.Context, arg CountMemberRegistrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberRegistrations, arg.UserID, arg.ActivityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityRegistration = `-- name: CreateActivityRegistration :one
INSERT INTO activity_registrations(user_id,activity_id,status,questionnaire_answer,created_at,updated_at)
VALUES ($1,$2,'TERDAFTAR',$3,now(),now()) RETURNING id, user_id, activity_id, status, questionnaire_answer, created_at, updated_at, guest_data
`

type CreateActivityRegistrationParams struct {
	UserID              *int32 `json:"user_id"`
	ActivityID          *int32 `json:"activity_id"`
	QuestionnaireAnswer []byte `json:"questionnaire_answer"`
}

func (q *Queries) CreateActivityRegistration(ctx context.Context, arg CreateActivityRegistrationParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, createActivityRegistration, arg.UserID, arg.ActivityID, arg.QuestionnaireAnswer)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityID,
		&i.Status,
		&i.QuestionnaireAnswer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestData,
	)
	return i, err
}

const deleteActivityRegistration = `-- name: DeleteActivityRegistration :execrows
DELETE FROM activity_registrations WHERE id=$1
`

func (q *Queries) DeleteActivityRegistration(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const profileForRegistration = `-- name: ProfileForRegistration :one
SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) ProfileForRegistration(ctx context.Context, identifier string) (Profile, error) {
	row := q.db.QueryRow(ctx, profileForRegistration, identifier)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.PersonalID,
		&i.Picture,
		&i.Whatsapp,
		&i.Line,
		&i.Instagram,
		&i.Tiktok,
		&i.Linkedin,
		&i.ProvinceID,
		&i.CityID,
		&i.UniversityID,
		&i.Major,
		&i.IntakeYear,
		&i.Level,
		&i.Badges,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.OriginProvinceID,
		&i.OriginCityID,
		&i.Country,
		&i.EducationHistory,
		&i.WorkHistory,
		&i.ExtraData,
	)
	return i, err
}

const registrationActivityByIdentifier = `-- name: RegistrationActivityByIdentifier :one
SELECT id, name, slug, description, badge, activity_start, activity_end, registration_start, registration_end, selection_start, selection_end, activity_type, activity_category, additional_config, minimum_level, is_published, created_at, updated_at, is_registration_open, club_id, certificate_template_id FROM activities WHERE id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) RegistrationActivityByIdentifier(ctx context.Context, identifier string) (Activity, error) {
	row := q.db.QueryRow(ctx, registrationActivityByIdentifier, identifier)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Badge,
		&i.ActivityStart,
		&i.ActivityEnd,
		&i.RegistrationStart,
		&i.RegistrationEnd,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.ActivityType,
		&i.ActivityCategory,
		&i.AdditionalConfig,
		&i.MinimumLevel,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRegistrationOpen,
		&i.ClubID,
		&i.CertificateTemplateID,
	)
	return i, err
}

const registrationHasCertificate = `-- name: RegistrationHasCertificate :one
SELECT EXISTS(SELECT 1 FROM issued_certificates WHERE registration_id=$1)
`

func (q *Queries) RegistrationHasCertificate(ctx context.Context, registrationID int32) (bool, error) {
	row := q.db.QueryRow(ctx, registrationHasCertificate, registrationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const registrationProfilesByUsers = `-- name: RegistrationProfilesByUsers :many
SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE user_id=ANY($1::integer[])
`

func (q *Queries) RegistrationProfilesByUsers(ctx context.Context, dollar_1 []int32) ([]Profile, error) {
	rows, err := q.db.Query(ctx, registrationProfilesByUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Gender,
			&i.PersonalID,
			&i.Picture,
			&i.Whatsapp,
			&i.Line,
			&i.Instagram,
			&i.Tiktok,
			&i.Linkedin,
			&i.ProvinceID,
			&i.CityID,
			&i.UniversityID,
			&i.Major,
			&i.IntakeYear,
			&i.Level,
			&i.Badges,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BirthDate,
			&i.OriginProvinceID,
			&i.OriginCityID,
			&i.Country,
			&i.EducationHistory,
			&i.WorkHistory,
			&i.ExtraData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationPublicUsersByEmail = `-- name: RegistrationPublicUsersByEmail :many
SELECT id FROM public_users WHERE email=ANY($1::text[])
`

func (q *Queries) RegistrationPublicUsersByEmail(ctx context.Context, dollar_1 []string) ([]int32, error) {
	rows, err := q.db.Query(ctx, registrationPublicUsersByEmail, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationStatusCounts = `-- name: RegistrationStatusCounts :many
SELECT status,count(*) AS count FROM activity_registrations WHERE activity_id=CAST(CAST($1 AS text) AS integer) GROUP BY status
`

type RegistrationStatusCountsRow struct {
	Status *string `json:"status"`
	Count  int64   `json:"count"`
}

func (q *Queries) RegistrationStatusCounts(ctx context.Context, identifier string) ([]RegistrationStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, registrationStatusCounts, identifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationStatusCountsRow{}
	for rows.Next() {
		var i RegistrationStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationTotal = `-- name: RegistrationTotal :one
SELECT count(*) FROM activity_registrations WHERE activity_id=CAST(CAST($1 AS text) AS integer)
`

func (q *Queries) RegistrationTotal(ctx context.Context, identifier string) (int64, error) {
	row := q.db.QueryRow(ctx, registrationTotal, identifier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registrationsByActivityUsers = `-- name: RegistrationsByActivityUsers :many
SELECT id FROM activity_registrations WHERE activity_id=$1 AND user_id=ANY($2::integer[])
`

type RegistrationsByActivityUsersParams struct {
	ActivityID *int32  `json:"activity_id"`
	Column2    []int32 `json:"column_2"`
}

func (q *Queries) RegistrationsByActivityUsers(ctx context.Context, arg RegistrationsByActivityUsersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, registrationsByActivityUsers, arg.ActivityID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationsByUser = `-- name: RegistrationsByUser :many
SELECT ar.id, ar.user_id, ar.activity_id, ar.status, ar.questionnaire_answer, ar.created_at, ar.updated_at, ar.guest_data,to_jsonb(a) AS activity FROM activity_registrations ar LEFT JOIN activities a ON a.id=ar.activity_id WHERE ar.user_id=CAST(CAST($1 AS text) AS integer)
`

type RegistrationsByUserRow struct {
	ActivityRegistration ActivityRegistration `json:"activity_registration"`
	Activity             []byte               `json:"activity"`
}

func (q *Queries) RegistrationsByUser(ctx context.Context, identifier string) ([]RegistrationsByUserRow, error) {
	rows, err := q.db.Query(ctx, registrationsByUser, identifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationsByUserRow{}
	for rows.Next() {
		var i RegistrationsByUserRow
		if err := rows.Scan(
			&i.ActivityRegistration.ID,
			&i.ActivityRegistration.UserID,
			&i.ActivityRegistration.ActivityID,
			&i.ActivityRegistration.Status,
			&i.ActivityRegistration.QuestionnaireAnswer,
			&i.ActivityRegistration.CreatedAt,
			&i.ActivityRegistration.UpdatedAt,
			&i.ActivityRegistration.GuestData,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRegistrationProfileBadges = `-- name: SetRegistrationProfileBadges :exec
UPDATE profiles SET badges=$2,updated_at=now() WHERE id=$1
`

type SetRegistrationProfileBadgesParams struct {
	ID     int32  `json:"id"`
	Badges []byte `json:"badges"`
}

func (q *Queries) SetRegistrationProfileBadges(ctx context.Context, arg SetRegistrationProfileBadgesParams) error {
	_, err := q.db.Exec(ctx, setRegistrationProfileBadges, arg.ID, arg.Badges)
	return err
}

const setRegistrationProfileLevel = `-- name: SetRegistrationProfileLevel :exec
UPDATE profiles SET level=$1 WHERE user_id=ANY($2::integer[])
`

type SetRegistrationProfileLevelParams struct {
	Level   *int32  `json:"level"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) SetRegistrationProfileLevel(ctx context.Context, arg SetRegistrationProfileLevelParams) error {
	_, err := q.db.Exec(ctx, setRegistrationProfileLevel, arg.Level, arg.Column2)
	return err
}

const usersForRegistrationIDs = `-- name: UsersForRegistrationIDs :many
SELECT user_id FROM activity_registrations WHERE id=ANY(CAST(CAST($1 AS text[]) AS integer[]))
`

func (q *Queries) UsersForRegistrationIDs(ctx context.Context, ids []string) ([]*int32, error) {
	rows, err := q.db.Query(ctx, usersForRegistrationIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*int32{}
	for rows.Next() {
		var user_id *int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
