// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_export.sql

package dbgen

import (
	"context"
)

const registrationExportCities = `-- name: RegistrationExportCities :many
SELECT id,name FROM cities WHERE id=ANY(CAST(CAST($1 AS text[]) AS integer[]))
`

type RegistrationExportCitiesRow struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

func (q *Queries) RegistrationExportCities(ctx context.Context, ids []string) ([]RegistrationExportCitiesRow, error) {
	rows, err := q.db.Query(ctx, registrationExportCities, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationExportCitiesRow{}
	for rows.Next() {
		var i RegistrationExportCitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationExportForm = `-- name: RegistrationExportForm :one
SELECT form_schema FROM custom_forms WHERE feature_type='activity_registration' AND feature_id=$1 AND is_active=true LIMIT 1
`

func (q *Queries) RegistrationExportForm(ctx context.Context, featureID *int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, registrationExportForm, featureID)
	var form_schema []byte
	err := row.Scan(&form_schema)
	return form_schema, err
}

const registrationExportProvinces = `-- name: RegistrationExportProvinces :many
SELECT id,name FROM provinces WHERE id=ANY(CAST(CAST($1 AS text[]) AS integer[]))
`

type RegistrationExportProvincesRow struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

func (q *Queries) RegistrationExportProvinces(ctx context.Context, ids []string) ([]RegistrationExportProvincesRow, error) {
	rows, err := q.db.Query(ctx, registrationExportProvinces, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationExportProvincesRow{}
	for rows.Next() {
		var i RegistrationExportProvincesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationExportRelations = `-- name: RegistrationExportRelations :many
SELECT ar.id,u.email,to_jsonb(p) AS profile,jsonb_build_object('province',province.name,'city',city.name,'origin_province',origin_province.name,'origin_city',origin_city.name,'university',university.name) AS locations
FROM activity_registrations ar LEFT JOIN public_users u ON u.id=ar.user_id
LEFT JOIN LATERAL (SELECT id, user_id, name, gender, personal_id, picture, whatsapp, line, instagram, tiktok, linkedin, province_id, city_id, university_id, major, intake_year, level, badges, created_at, updated_at, birth_date, origin_province_id, origin_city_id, country, education_history, work_history, extra_data FROM profiles WHERE user_id=u.id LIMIT 1) p ON true
LEFT JOIN provinces province ON province.id=p.province_id
LEFT JOIN cities city ON city.id=p.city_id
LEFT JOIN provinces origin_province ON origin_province.id=p.origin_province_id
LEFT JOIN cities origin_city ON origin_city.id=p.origin_city_id
LEFT JOIN universities university ON university.id=p.university_id
WHERE ar.id=ANY($1::integer[])
`

type RegistrationExportRelationsRow struct {
	ID        int32   `json:"id"`
	Email     *string `json:"email"`
	Profile   []byte  `json:"profile"`
	Locations []byte  `json:"locations"`
}

func (q *Queries) RegistrationExportRelations(ctx context.Context, dollar_1 []int32) ([]RegistrationExportRelationsRow, error) {
	rows, err := q.db.Query(ctx, registrationExportRelations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationExportRelationsRow{}
	for rows.Next() {
		var i RegistrationExportRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Profile,
			&i.Locations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationExportRows = `-- name: RegistrationExportRows :many
SELECT id, user_id, activity_id, status, questionnaire_answer, scoring_data, created_at, updated_at, guest_data FROM activity_registrations WHERE activity_id=$1
`

func (q *Queries) RegistrationExportRows(ctx context.Context, activityID *int32) ([]ActivityRegistration, error) {
	rows, err := q.db.Query(ctx, registrationExportRows, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityRegistration{}
	for rows.Next() {
		var i ActivityRegistration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityID,
			&i.Status,
			&i.QuestionnaireAnswer,
			&i.ScoringData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuestData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationExportUniversities = `-- name: RegistrationExportUniversities :many
SELECT id,name FROM universities WHERE id=ANY(CAST(CAST($1 AS text[]) AS integer[]))
`

type RegistrationExportUniversitiesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RegistrationExportUniversities(ctx context.Context, ids []string) ([]RegistrationExportUniversitiesRow, error) {
	rows, err := q.db.Query(ctx, registrationExportUniversities, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationExportUniversitiesRow{}
	for rows.Next() {
		var i RegistrationExportUniversitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
