// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addScoringPublication = `-- name: AddScoringPublication :exec
INSERT INTO activity_scoring_publications(activity_id,registration_id,revision,action,snapshot,actor_id,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type AddScoringPublicationParams struct {
	ActivityID     int32              `json:"activity_id"`
	RegistrationID int32              `json:"registration_id"`
	Revision       int32              `json:"revision"`
	Action         string             `json:"action"`
	Snapshot       []byte             `json:"snapshot"`
	ActorID        int32              `json:"actor_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddScoringPublication(ctx context.Context, arg AddScoringPublicationParams) error {
	_, err := q.db.Exec(ctx, addScoringPublication,
		arg.ActivityID,
		arg.RegistrationID,
		arg.Revision,
		arg.Action,
		arg.Snapshot,
		arg.ActorID,
		arg.CreatedAt,
	)
	return err
}

const countScoringRegistrations = `-- name: CountScoringRegistrations :one
SELECT count(*) FROM activity_registrations r WHERE r.activity_id=$1
AND COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta') ILIKE '%' || $2::text || '%'
AND ($3::text='' OR COALESCE(r.scoring_data->>'state','unscored')=$3::text)
`

type CountScoringRegistrationsParams struct {
	ActivityID *int32 `json:"activity_id"`
	Search     string `json:"search"`
	State      string `json:"state"`
}

func (q *Queries) CountScoringRegistrations(ctx context.Context, arg CountScoringRegistrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScoringRegistrations, arg.ActivityID, arg.Search, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasScoringPublications = `-- name: HasScoringPublications :one
SELECT EXISTS(SELECT 1 FROM activity_scoring_publications WHERE activity_id=$1)
`

func (q *Queries) HasScoringPublications(ctx context.Context, activityID int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasScoringPublications, activityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listScoringRegistrations = `-- name: ListScoringRegistrations :many
SELECT r.id,COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta')::text AS name,r.scoring_data,
count(*) OVER() AS total
FROM activity_registrations r WHERE r.activity_id=$1
AND COALESCE((SELECT NULLIF(p.name,'') FROM profiles p WHERE p.user_id=r.user_id ORDER BY p.id LIMIT 1),NULLIF(r.guest_data->>'name',''),'Peserta') ILIKE '%' || $2::text || '%'
AND ($3::text='' OR COALESCE(r.scoring_data->>'state','unscored')=$3::text)
ORDER BY r.id LIMIT $5::integer OFFSET $4::integer
`

type ListScoringRegistrationsParams struct {
	ActivityID *int32 `json:"activity_id"`
	Search     string `json:"search"`
	State      string `json:"state"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

type ListScoringRegistrationsRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	ScoringData []byte `json:"scoring_data"`
	Total       int64  `json:"total"`
}

func (q *Queries) ListScoringRegistrations(ctx context.Context, arg ListScoringRegistrationsParams) ([]ListScoringRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listScoringRegistrations,
		arg.ActivityID,
		arg.Search,
		arg.State,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoringRegistrationsRow{}
	for rows.Next() {
		var i ListScoringRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ScoringData,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockScoringRubric = `-- name: LockScoringRubric :exec
UPDATE activity_scoring_rubrics SET locked_at=COALESCE(locked_at,now()) WHERE activity_id=$1
`

func (q *Queries) LockScoringRubric(ctx context.Context, activityID int32) error {
	_, err := q.db.Exec(ctx, lockScoringRubric, activityID)
	return err
}

const registrationHasScoringPublications = `-- name: RegistrationHasScoringPublications :one
SELECT EXISTS(SELECT 1 FROM activity_scoring_publications WHERE registration_id=$1)
`

func (q *Queries) RegistrationHasScoringPublications(ctx context.Context, registrationID int32) (bool, error) {
	row := q.db.QueryRow(ctx, registrationHasScoringPublications, registrationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveScoringData = `-- name: SaveScoringData :exec
UPDATE activity_registrations SET scoring_data=$2,updated_at=now() WHERE id=$1
`

type SaveScoringDataParams struct {
	ID          int32  `json:"id"`
	ScoringData []byte `json:"scoring_data"`
}

func (q *Queries) SaveScoringData(ctx context.Context, arg SaveScoringDataParams) error {
	_, err := q.db.Exec(ctx, saveScoringData, arg.ID, arg.ScoringData)
	return err
}

const saveScoringRubric = `-- name: SaveScoringRubric :exec
INSERT INTO activity_scoring_rubrics(activity_id,definition,revision,updated_by,updated_at)
VALUES ($1,$2,1,$3,now()) ON CONFLICT(activity_id) DO UPDATE SET definition=EXCLUDED.definition,revision=activity_scoring_rubrics.revision+1,updated_by=EXCLUDED.updated_by,updated_at=now()
`

type SaveScoringRubricParams struct {
	ActivityID int32  `json:"activity_id"`
	Definition []byte `json:"definition"`
	UpdatedBy  int32  `json:"updated_by"`
}

func (q *Queries) SaveScoringRubric(ctx context.Context, arg SaveScoringRubricParams) error {
	_, err := q.db.Exec(ctx, saveScoringRubric, arg.ActivityID, arg.Definition, arg.UpdatedBy)
	return err
}

const scoringRegistration = `-- name: ScoringRegistration :one
SELECT id,scoring_data FROM activity_registrations WHERE id=$1 AND activity_id=$2 FOR UPDATE
`

type ScoringRegistrationParams struct {
	ID         int32  `json:"id"`
	ActivityID *int32 `json:"activity_id"`
}

type ScoringRegistrationRow struct {
	ID          int32  `json:"id"`
	ScoringData []byte `json:"scoring_data"`
}

func (q *Queries) ScoringRegistration(ctx context.Context, arg ScoringRegistrationParams) (ScoringRegistrationRow, error) {
	row := q.db.QueryRow(ctx, scoringRegistration, arg.ID, arg.ActivityID)
	var i ScoringRegistrationRow
	err := row.Scan(&i.ID, &i.ScoringData)
	return i, err
}

const scoringRubric = `-- name: ScoringRubric :one
SELECT id, activity_id, definition, revision, locked_at, updated_by, updated_at FROM activity_scoring_rubrics WHERE activity_id=$1
`

func (q *Queries) ScoringRubric(ctx context.Context, activityID int32) (ActivityScoringRubric, error) {
	row := q.db.QueryRow(ctx, scoringRubric, activityID)
	var i ActivityScoringRubric
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Definition,
		&i.Revision,
		&i.LockedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
