// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_links.sql

package dbgen

import (
	"context"
)

const countShortLinks = `-- name: CountShortLinks :one
SELECT count(*) FROM urls
WHERE strpos(lower(id), lower($1::text)) > 0
   OR strpos(lower(original_url), lower($1::text)) > 0
`

func (q *Queries) CountShortLinks(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countShortLinks, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortLink = `-- name: CreateShortLink :one
INSERT INTO urls (id, original_url) VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING RETURNING id, original_url, created_at, visit_count
`

type CreateShortLinkParams struct {
	ID          string `json:"id"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (Url, error) {
	row := q.db.QueryRow(ctx, createShortLink, arg.ID, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.VisitCount,
	)
	return i, err
}

const deleteShortLink = `-- name: DeleteShortLink :execrows
DELETE FROM urls WHERE id = $1
`

func (q *Queries) DeleteShortLink(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShortLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listShortLinks = `-- name: ListShortLinks :many
SELECT id, original_url, created_at, visit_count FROM urls
WHERE strpos(lower(id), lower($1::text)) > 0
   OR strpos(lower(original_url), lower($1::text)) > 0
ORDER BY created_at DESC, id ASC
LIMIT $3 OFFSET $2
`

type ListShortLinksParams struct {
	Search     string `json:"search"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListShortLinks(ctx context.Context, arg ListShortLinksParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listShortLinks, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.CreatedAt,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShortLink = `-- name: UpdateShortLink :one
UPDATE urls SET original_url = $2 WHERE id = $1 RETURNING id, original_url, created_at, visit_count
`

type UpdateShortLinkParams struct {
	ID          string `json:"id"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) UpdateShortLink(ctx context.Context, arg UpdateShortLinkParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateShortLink, arg.ID, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.VisitCount,
	)
	return i, err
}
