// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talent_assessment.sql

package dbgen

import (
	"context"
)

const createTalentDraft = `-- name: CreateTalentDraft :one
INSERT INTO talent_assessment_drafts(admin_user_id,draft_id,definition_version,answers)
VALUES ($1,$2,$3,$4) RETURNING admin_user_id, draft_id, definition_version, answers, current_question, revision, created_at, updated_at
`

type CreateTalentDraftParams struct {
	AdminUserID       int32  `json:"admin_user_id"`
	DraftID           string `json:"draft_id"`
	DefinitionVersion string `json:"definition_version"`
	Answers           []byte `json:"answers"`
}

func (q *Queries) CreateTalentDraft(ctx context.Context, arg CreateTalentDraftParams) (TalentAssessmentDraft, error) {
	row := q.db.QueryRow(ctx, createTalentDraft,
		arg.AdminUserID,
		arg.DraftID,
		arg.DefinitionVersion,
		arg.Answers,
	)
	var i TalentAssessmentDraft
	err := row.Scan(
		&i.AdminUserID,
		&i.DraftID,
		&i.DefinitionVersion,
		&i.Answers,
		&i.CurrentQuestion,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTalentDraft = `-- name: DeleteTalentDraft :exec
DELETE FROM talent_assessment_drafts WHERE admin_user_id=$1
`

func (q *Queries) DeleteTalentDraft(ctx context.Context, adminUserID int32) error {
	_, err := q.db.Exec(ctx, deleteTalentDraft, adminUserID)
	return err
}

const getTalentDraft = `-- name: GetTalentDraft :one
SELECT admin_user_id, draft_id, definition_version, answers, current_question, revision, created_at, updated_at FROM talent_assessment_drafts WHERE admin_user_id=$1
`

func (q *Queries) GetTalentDraft(ctx context.Context, adminUserID int32) (TalentAssessmentDraft, error) {
	row := q.db.QueryRow(ctx, getTalentDraft, adminUserID)
	var i TalentAssessmentDraft
	err := row.Scan(
		&i.AdminUserID,
		&i.DraftID,
		&i.DefinitionVersion,
		&i.Answers,
		&i.CurrentQuestion,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTalentResult = `-- name: GetTalentResult :one
SELECT admin_user_id, submission_id, definition_version, answers, result, submitted_at FROM talent_assessment_results WHERE admin_user_id=$1
`

func (q *Queries) GetTalentResult(ctx context.Context, adminUserID int32) (TalentAssessmentResult, error) {
	row := q.db.QueryRow(ctx, getTalentResult, adminUserID)
	var i TalentAssessmentResult
	err := row.Scan(
		&i.AdminUserID,
		&i.SubmissionID,
		&i.DefinitionVersion,
		&i.Answers,
		&i.Result,
		&i.SubmittedAt,
	)
	return i, err
}

const replaceTalentResult = `-- name: ReplaceTalentResult :one
INSERT INTO talent_assessment_results(admin_user_id,submission_id,definition_version,answers,result)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT(admin_user_id) DO UPDATE SET submission_id=EXCLUDED.submission_id,
definition_version=EXCLUDED.definition_version,answers=EXCLUDED.answers,result=EXCLUDED.result,submitted_at=now()
RETURNING admin_user_id, submission_id, definition_version, answers, result, submitted_at
`

type ReplaceTalentResultParams struct {
	AdminUserID       int32  `json:"admin_user_id"`
	SubmissionID      string `json:"submission_id"`
	DefinitionVersion string `json:"definition_version"`
	Answers           []byte `json:"answers"`
	Result            []byte `json:"result"`
}

func (q *Queries) ReplaceTalentResult(ctx context.Context, arg ReplaceTalentResultParams) (TalentAssessmentResult, error) {
	row := q.db.QueryRow(ctx, replaceTalentResult,
		arg.AdminUserID,
		arg.SubmissionID,
		arg.DefinitionVersion,
		arg.Answers,
		arg.Result,
	)
	var i TalentAssessmentResult
	err := row.Scan(
		&i.AdminUserID,
		&i.SubmissionID,
		&i.DefinitionVersion,
		&i.Answers,
		&i.Result,
		&i.SubmittedAt,
	)
	return i, err
}

const saveTalentDraft = `-- name: SaveTalentDraft :one
UPDATE talent_assessment_drafts SET answers=$2,current_question=$3,revision=revision+1,updated_at=now()
WHERE admin_user_id=$1 RETURNING admin_user_id, draft_id, definition_version, answers, current_question, revision, created_at, updated_at
`

type SaveTalentDraftParams struct {
	AdminUserID     int32  `json:"admin_user_id"`
	Answers         []byte `json:"answers"`
	CurrentQuestion int32  `json:"current_question"`
}

func (q *Queries) SaveTalentDraft(ctx context.Context, arg SaveTalentDraftParams) (TalentAssessmentDraft, error) {
	row := q.db.QueryRow(ctx, saveTalentDraft, arg.AdminUserID, arg.Answers, arg.CurrentQuestion)
	var i TalentAssessmentDraft
	err := row.Scan(
		&i.AdminUserID,
		&i.DraftID,
		&i.DefinitionVersion,
		&i.Answers,
		&i.CurrentQuestion,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
