// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const certificateTemplateCounts = `-- name: CertificateTemplateCounts :one
SELECT t.id, t.name, t.description, t.background_image, t.template_data, t.is_active, t.created_at, t.updated_at, t.lifecycle_status, t.version, t.background_asset_version, t.published_at, t.archived_at,(SELECT count(*) FROM activities WHERE certificate_template_id=t.id) AS activity_usage_count,(SELECT count(*) FROM issued_certificates WHERE template_id=t.id) AS issued_certificate_count FROM certificate_templates t WHERE t.id=CAST(CAST($1 AS text) AS integer)
`

type CertificateTemplateCountsRow struct {
	CertificateTemplate    CertificateTemplate `json:"certificate_template"`
	ActivityUsageCount     int64               `json:"activity_usage_count"`
	IssuedCertificateCount int64               `json:"issued_certificate_count"`
}

func (q *Queries) CertificateTemplateCounts(ctx context.Context, identifier string) (CertificateTemplateCountsRow, error) {
	row := q.db.QueryRow(ctx, certificateTemplateCounts, identifier)
	var i CertificateTemplateCountsRow
	err := row.Scan(
		&i.CertificateTemplate.ID,
		&i.CertificateTemplate.Name,
		&i.CertificateTemplate.Description,
		&i.CertificateTemplate.BackgroundImage,
		&i.CertificateTemplate.TemplateData,
		&i.CertificateTemplate.IsActive,
		&i.CertificateTemplate.CreatedAt,
		&i.CertificateTemplate.UpdatedAt,
		&i.CertificateTemplate.LifecycleStatus,
		&i.CertificateTemplate.Version,
		&i.CertificateTemplate.BackgroundAssetVersion,
		&i.CertificateTemplate.PublishedAt,
		&i.CertificateTemplate.ArchivedAt,
		&i.ActivityUsageCount,
		&i.IssuedCertificateCount,
	)
	return i, err
}

const completeDuplicatedTemplate = `-- name: CompleteDuplicatedTemplate :one
UPDATE certificate_templates SET background_image=$1::text,template_data= $2::jsonb,updated_at=CASE WHEN ROW(background_image,template_data) IS DISTINCT FROM ROW($1::text,$2::jsonb) THEN now() ELSE updated_at END WHERE id = $3::integer RETURNING id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at
`

type CompleteDuplicatedTemplateParams struct {
	BackgroundImage *string `json:"background_image"`
	TemplateData    []byte  `json:"template_data"`
	ID              int32   `json:"id"`
}

func (q *Queries) CompleteDuplicatedTemplate(ctx context.Context, arg CompleteDuplicatedTemplateParams) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, completeDuplicatedTemplate, arg.BackgroundImage, arg.TemplateData, arg.ID)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countCertificateTemplates = `-- name: CountCertificateTemplates :one
SELECT count(*) FROM certificate_templates WHERE ($1::text IS NULL OR name ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR lifecycle_status=$2::text)
`

type CountCertificateTemplatesParams struct {
	Search *string `json:"search"`
	Status *string `json:"status"`
}

func (q *Queries) CountCertificateTemplates(ctx context.Context, arg CountCertificateTemplatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificateTemplates, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificateTemplate = `-- name: CreateCertificateTemplate :one
INSERT INTO certificate_templates(name,description,background_image,template_data,lifecycle_status,is_active,version,background_asset_version,published_at,archived_at,created_at,updated_at)
VALUES($1::text,$2::text,NULL,$3::jsonb,$4::text,false,1,0,NULL,$5::timestamptz,now(),now()) RETURNING id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at
`

type CreateCertificateTemplateParams struct {
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	TemplateData    []byte             `json:"template_data"`
	LifecycleStatus string             `json:"lifecycle_status"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) CreateCertificateTemplate(ctx context.Context, arg CreateCertificateTemplateParams) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, createCertificateTemplate,
		arg.Name,
		arg.Description,
		arg.TemplateData,
		arg.LifecycleStatus,
		arg.ArchivedAt,
	)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteCertificateTemplate = `-- name: DeleteCertificateTemplate :exec
DELETE FROM certificate_templates WHERE id=$1
`

func (q *Queries) DeleteCertificateTemplate(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCertificateTemplate, id)
	return err
}

const listCertificateTemplates = `-- name: ListCertificateTemplates :many
SELECT t.id, t.name, t.description, t.background_image, t.template_data, t.is_active, t.created_at, t.updated_at, t.lifecycle_status, t.version, t.background_asset_version, t.published_at, t.archived_at,(SELECT count(*) FROM activities WHERE certificate_template_id=t.id) AS activity_usage_count,(SELECT count(*) FROM issued_certificates WHERE template_id=t.id) AS issued_certificate_count FROM certificate_templates t
WHERE ($1::text IS NULL OR t.name ILIKE '%'||$1::text||'%') AND ($2::text IS NULL OR t.lifecycle_status=$2::text)
ORDER BY t.created_at DESC LIMIT $4::bigint OFFSET $3::bigint
`

type ListCertificateTemplatesParams struct {
	Search     *string `json:"search"`
	Status     *string `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageSize   *int64  `json:"page_size"`
}

type ListCertificateTemplatesRow struct {
	CertificateTemplate    CertificateTemplate `json:"certificate_template"`
	ActivityUsageCount     int64               `json:"activity_usage_count"`
	IssuedCertificateCount int64               `json:"issued_certificate_count"`
}

func (q *Queries) ListCertificateTemplates(ctx context.Context, arg ListCertificateTemplatesParams) ([]ListCertificateTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listCertificateTemplates,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateTemplatesRow{}
	for rows.Next() {
		var i ListCertificateTemplatesRow
		if err := rows.Scan(
			&i.CertificateTemplate.ID,
			&i.CertificateTemplate.Name,
			&i.CertificateTemplate.Description,
			&i.CertificateTemplate.BackgroundImage,
			&i.CertificateTemplate.TemplateData,
			&i.CertificateTemplate.IsActive,
			&i.CertificateTemplate.CreatedAt,
			&i.CertificateTemplate.UpdatedAt,
			&i.CertificateTemplate.LifecycleStatus,
			&i.CertificateTemplate.Version,
			&i.CertificateTemplate.BackgroundAssetVersion,
			&i.CertificateTemplate.PublishedAt,
			&i.CertificateTemplate.ArchivedAt,
			&i.ActivityUsageCount,
			&i.IssuedCertificateCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCertificateTemplate = `-- name: LockCertificateTemplate :one
SELECT id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at FROM certificate_templates WHERE id=CAST(CAST($1 AS text) AS integer) FOR UPDATE
`

func (q *Queries) LockCertificateTemplate(ctx context.Context, identifier string) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, lockCertificateTemplate, identifier)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const replaceCertificateBackground = `-- name: ReplaceCertificateBackground :one
UPDATE certificate_templates SET background_image = $1::text,background_asset_version=CAST(CAST($2 AS text) AS integer),version=CAST(CAST($3 AS text) AS integer),updated_at=now() WHERE id = $4::integer RETURNING id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at
`

type ReplaceCertificateBackgroundParams struct {
	BackgroundImage        string `json:"background_image"`
	BackgroundAssetVersion string `json:"background_asset_version"`
	Version                string `json:"version"`
	ID                     int32  `json:"id"`
}

func (q *Queries) ReplaceCertificateBackground(ctx context.Context, arg ReplaceCertificateBackgroundParams) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, replaceCertificateBackground,
		arg.BackgroundImage,
		arg.BackgroundAssetVersion,
		arg.Version,
		arg.ID,
	)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateCertificateTemplate = `-- name: UpdateCertificateTemplate :one
UPDATE certificate_templates SET name = $1::text,description=$2::text,background_image=$3::text,template_data= $4::jsonb,lifecycle_status= $5::text,is_active=$6::boolean,
version=CAST(CAST($7 AS text) AS integer),background_asset_version=CAST(CAST($8 AS text) AS integer),published_at=$9::timestamptz,archived_at=$10::timestamptz,updated_at=now() WHERE id = $11::integer RETURNING id, name, description, background_image, template_data, is_active, created_at, updated_at, lifecycle_status, version, background_asset_version, published_at, archived_at
`

type UpdateCertificateTemplateParams struct {
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	BackgroundImage        *string            `json:"background_image"`
	TemplateData           []byte             `json:"template_data"`
	LifecycleStatus        string             `json:"lifecycle_status"`
	IsActive               *bool              `json:"is_active"`
	Version                string             `json:"version"`
	BackgroundAssetVersion string             `json:"background_asset_version"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	ID                     int32              `json:"id"`
}

func (q *Queries) UpdateCertificateTemplate(ctx context.Context, arg UpdateCertificateTemplateParams) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, updateCertificateTemplate,
		arg.Name,
		arg.Description,
		arg.BackgroundImage,
		arg.TemplateData,
		arg.LifecycleStatus,
		arg.IsActive,
		arg.Version,
		arg.BackgroundAssetVersion,
		arg.PublishedAt,
		arg.ArchivedAt,
		arg.ID,
	)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BackgroundImage,
		&i.TemplateData,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleStatus,
		&i.Version,
		&i.BackgroundAssetVersion,
		&i.PublishedAt,
		&i.ArchivedAt,
	)
	return i, err
}
