// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package dbgen

import (
	"context"
)

const acquireRequestLock = `-- name: AcquireRequestLock :exec
SELECT pg_advisory_xact_lock(7412,$1)
`

func (q *Queries) AcquireRequestLock(ctx context.Context, pgAdvisoryXactLock int32) error {
	_, err := q.db.Exec(ctx, acquireRequestLock, pgAdvisoryXactLock)
	return err
}

const cancelTicket = `-- name: CancelTicket :exec
UPDATE tickets SET status='cancelled',cancelled_at=now(),updated_at=now() WHERE id=$1
`

func (q *Queries) CancelTicket(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelTicket, id)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets(number,status,requester_admin_user_id,requested_role_code,reason,created_at,updated_at)
VALUES ($1,'open',$2,$3,$4,now(),now()) RETURNING id
`

type CreateTicketParams struct {
	Number               string `json:"number"`
	RequesterAdminUserID int32  `json:"requester_admin_user_id"`
	RequestedRoleCode    string `json:"requested_role_code"`
	Reason               string `json:"reason"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Number,
		arg.RequesterAdminUserID,
		arg.RequestedRoleCode,
		arg.Reason,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const lockTicket = `-- name: LockTicket :one
SELECT id, number, status, resolution, requester_admin_user_id, requested_role_code, reason, rejection_reason, resolved_by_admin_user_id, resolved_at, cancelled_at, created_at, updated_at FROM tickets WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTicket(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRow(ctx, lockTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Resolution,
		&i.RequesterAdminUserID,
		&i.RequestedRoleCode,
		&i.Reason,
		&i.RejectionReason,
		&i.ResolvedByAdminUserID,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const openRoleRequest = `-- name: OpenRoleRequest :one
SELECT id FROM tickets WHERE requester_admin_user_id=$1 AND requested_role_code=$2 AND status='open'
`

type OpenRoleRequestParams struct {
	RequesterAdminUserID int32  `json:"requester_admin_user_id"`
	RequestedRoleCode    string `json:"requested_role_code"`
}

func (q *Queries) OpenRoleRequest(ctx context.Context, arg OpenRoleRequestParams) (int32, error) {
	row := q.db.QueryRow(ctx, openRoleRequest, arg.RequesterAdminUserID, arg.RequestedRoleCode)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const ownTickets = `-- name: OwnTickets :many
SELECT id, number, status, resolution, requester_admin_user_id, requested_role_code, reason, rejection_reason, resolved_by_admin_user_id, resolved_at, cancelled_at, created_at, updated_at FROM tickets WHERE requester_admin_user_id=$1 ORDER BY created_at DESC
`

func (q *Queries) OwnTickets(ctx context.Context, requesterAdminUserID int32) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, ownTickets, requesterAdminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.Resolution,
			&i.RequesterAdminUserID,
			&i.RequestedRoleCode,
			&i.Reason,
			&i.RejectionReason,
			&i.ResolvedByAdminUserID,
			&i.ResolvedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTicket = `-- name: ResolveTicket :exec
UPDATE tickets SET status='resolved',resolution=$2,rejection_reason=$3,resolved_by_admin_user_id=$4,resolved_at=now(),updated_at=now() WHERE id=$1
`

type ResolveTicketParams struct {
	ID                    int32   `json:"id"`
	Resolution            *string `json:"resolution"`
	RejectionReason       *string `json:"rejection_reason"`
	ResolvedByAdminUserID *int32  `json:"resolved_by_admin_user_id"`
}

func (q *Queries) ResolveTicket(ctx context.Context, arg ResolveTicketParams) error {
	_, err := q.db.Exec(ctx, resolveTicket,
		arg.ID,
		arg.Resolution,
		arg.RejectionReason,
		arg.ResolvedByAdminUserID,
	)
	return err
}

const reviewTickets = `-- name: ReviewTickets :many
SELECT t.id, t.number, t.status, t.resolution, t.requester_admin_user_id, t.requested_role_code, t.reason, t.rejection_reason, t.resolved_by_admin_user_id, t.resolved_at, t.cancelled_at, t.created_at, t.updated_at, requester.display_name AS requester_name,requester.email AS requester_email,requester.id AS requester_id
FROM tickets t JOIN admin_users requester ON requester.id=t.requester_admin_user_id
WHERE ($1::text = '' OR t.status = $1::text) ORDER BY t.created_at DESC
`

type ReviewTicketsRow struct {
	Ticket         Ticket  `json:"ticket"`
	RequesterName  *string `json:"requester_name"`
	RequesterEmail string  `json:"requester_email"`
	RequesterID    int32   `json:"requester_id"`
}

func (q *Queries) ReviewTickets(ctx context.Context, statusFilter string) ([]ReviewTicketsRow, error) {
	rows, err := q.db.Query(ctx, reviewTickets, statusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewTicketsRow{}
	for rows.Next() {
		var i ReviewTicketsRow
		if err := rows.Scan(
			&i.Ticket.ID,
			&i.Ticket.Number,
			&i.Ticket.Status,
			&i.Ticket.Resolution,
			&i.Ticket.RequesterAdminUserID,
			&i.Ticket.RequestedRoleCode,
			&i.Ticket.Reason,
			&i.Ticket.RejectionReason,
			&i.Ticket.ResolvedByAdminUserID,
			&i.Ticket.ResolvedAt,
			&i.Ticket.CancelledAt,
			&i.Ticket.CreatedAt,
			&i.Ticket.UpdatedAt,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.RequesterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketByID = `-- name: TicketByID :one
SELECT id, number, status, resolution, requester_admin_user_id, requested_role_code, reason, rejection_reason, resolved_by_admin_user_id, resolved_at, cancelled_at, created_at, updated_at FROM tickets WHERE id=$1
`

func (q *Queries) TicketByID(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Resolution,
		&i.RequesterAdminUserID,
		&i.RequestedRoleCode,
		&i.Reason,
		&i.RejectionReason,
		&i.ResolvedByAdminUserID,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ticketDetails = `-- name: TicketDetails :one
SELECT t.id, t.number, t.status, t.resolution, t.requester_admin_user_id, t.requested_role_code, t.reason, t.rejection_reason, t.resolved_by_admin_user_id, t.resolved_at, t.cancelled_at, t.created_at, t.updated_at, requester.display_name AS requester_name,requester.email AS requester_email,reviewer.display_name AS reviewer_name
FROM tickets t JOIN admin_users requester ON requester.id=t.requester_admin_user_id
LEFT JOIN admin_users reviewer ON reviewer.id=t.resolved_by_admin_user_id WHERE t.id=$1
`

type TicketDetailsRow struct {
	Ticket         Ticket  `json:"ticket"`
	RequesterName  *string `json:"requester_name"`
	RequesterEmail string  `json:"requester_email"`
	ReviewerName   *string `json:"reviewer_name"`
}

func (q *Queries) TicketDetails(ctx context.Context, id int32) (TicketDetailsRow, error) {
	row := q.db.QueryRow(ctx, ticketDetails, id)
	var i TicketDetailsRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.Number,
		&i.Ticket.Status,
		&i.Ticket.Resolution,
		&i.Ticket.RequesterAdminUserID,
		&i.Ticket.RequestedRoleCode,
		&i.Ticket.Reason,
		&i.Ticket.RejectionReason,
		&i.Ticket.ResolvedByAdminUserID,
		&i.Ticket.ResolvedAt,
		&i.Ticket.CancelledAt,
		&i.Ticket.CreatedAt,
		&i.Ticket.UpdatedAt,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.ReviewerName,
	)
	return i, err
}
