export async function memberCases(h,password){
  await h.call('member:invalid','POST','/v2/members',{});
  const created=await h.call('member:create-no-account','POST','/v2/members',{name:'Fixture no account',gender:'M',birth_date:'1999-03-15'});
  const user=created.data.user,profile=created.data.profile;
  const credential={email:'member@example.test',password};
  await h.call('member:generate-account','POST',`/v2/members/${user.id}/generate-account`,credential);
  await h.call('member:already-active','POST',`/v2/members/${user.id}/generate-account`,credential);
  await h.call('member:duplicate-email','POST','/v2/members',{name:'Duplicate',email:credential.email});
  await h.call('member:duplicate-number','POST','/v2/members',{name:'Duplicate number',member_id:user.member_id});
  await h.call('member:missing-account','POST','/v2/members/999999/generate-account',credential);
  await h.call('profile:show','GET',`/v2/profiles/${profile.id}`);
  await h.call('profile:by-user','GET',`/v2/profiles/user/${user.id}`);
  await h.call('profile:index','GET','/v2/profiles');
  await h.call('profile:update','PUT',`/v2/profiles/${profile.id}`,{name:'Updated member',badges:['LMD'],education_history:[{degree:'bachelor',institution:'Fixture University',faculty:'Science',major:'Physics',intake_year:2020}],extra_data:{preferred_name:'Fixture'}});
  await h.call('profile:regional','PUT',`/v2/profiles/${profile.id}/regional-assignment`,{alumni_regional_assignment:['Bandung']});
  await h.call('profile:merge-extra','PUT',`/v2/profiles/${profile.id}`,{extra_data:{salman_activity_history:['Fixture activity']}});
  await h.call('profile:filtered','GET',`/v2/profiles?badge=LMD&education_institution=Fixture&member_id=${user.member_id}`);
  await h.call('profile:missing','GET','/v2/profiles/999999');
  await h.call('profile:missing-update','PUT','/v2/profiles/999999',{name:'Missing'});
  await h.call('profile:invalid-update','PUT',`/v2/profiles/${profile.id}`,{gender:'invalid',level:'wrong'});
  await h.call('profile:missing-regional','PUT','/v2/profiles/999999/regional-assignment',{alumni_regional_assignment:[]});
  const active=await h.call('member:create-active','POST','/v2/members',{name:'Active fixture',email:'second-member@example.test',password});
  await h.call('member:update-credentials','PUT',`/v2/profiles/auth/${active.data.user.id}`,{email:'updated-member@example.test',password});
  await h.call('member:credentials-missing','PUT','/v2/profiles/auth/999999',{email:'missing-member@example.test',password});
  await h.call('member:credentials-duplicate','PUT',`/v2/profiles/auth/${active.data.user.id}`,{email:credential.email});
  await h.call('profile:combined-search-member-filter','GET',`/v2/profiles?search=Updated&member_id=${active.data.user.member_id}`);
  await h.call('profile:combined-search-education-filter','GET','/v2/profiles?search=Updated&education_institution=DoesNotExist');
  await h.call('profile:combined-credential-search-filter','GET',`/v2/profiles?search=member@example.test&member_id=${active.data.user.member_id}`);
  await h.seed("INSERT INTO profiles(name,badges,education_history,extra_data,created_at,updated_at) VALUES('Legacy orphan',$1::jsonb,$2::jsonb,NULL,'2024-01-01','2024-01-01')",[JSON.stringify('["LMD","ALUMNI"]'),JSON.stringify('legacy history')]);
  await h.call('profile:nullable-user-legacy-json','GET','/v2/profiles/3');
  await h.call('profile:nullable-user-list','GET','/v2/profiles?search=Legacy');
  await h.seed("UPDATE profiles SET updated_at='2024-01-02' WHERE id=$1",[profile.id]);
  await h.seed("UPDATE public_users SET updated_at='2024-01-02' WHERE id=$1",[active.data.user.id]);
  await h.call('member:credentials-empty','PUT',`/v2/profiles/auth/${active.data.user.id}`,{});
  await h.call('member:credentials-null','PUT',`/v2/profiles/auth/${active.data.user.id}`,{email:null,password:null});
  await h.call('profile:update-empty','PUT',`/v2/profiles/${profile.id}`,{});
  await h.call('profile:update-null','PUT',`/v2/profiles/${profile.id}`,{name:null,badges:null,country:null,extra_data:null});
  await h.call('profile:update-empty-strings','PUT',`/v2/profiles/${profile.id}`,{name:'',country:'',password:''});
  await h.call('member:credentials-unchanged','PUT',`/v2/profiles/auth/${active.data.user.id}`,{email:'updated-member@example.test'});
  await h.call('profile:update-unchanged','PUT',`/v2/profiles/${profile.id}`,{name:'Updated member',badges:['LMD'],extra_data:{}});
  await h.call('profile:update-birth-date','PUT',`/v2/profiles/${profile.id}`,{birth_date:'2000-01-02'});
  await h.call('profile:read-updated-date','GET',`/v2/profiles/${profile.id}`);
  await h.call('profile:update-zero-level','PUT',`/v2/profiles/${profile.id}`,{level:0});
  await h.call('profile:clear-arrays','PUT',`/v2/profiles/${profile.id}`,{badges:[],education_history:[],work_history:[],extra_data:{alumni_regional_assignment:[]}});
  await h.call('profile:work-history','PUT',`/v2/profiles/${profile.id}`,{work_history:[{job_title:'Tester',company:'Fixture',start_year:2020.5,end_year:2026}]});
  await h.seed("UPDATE profiles SET extra_data=$1::jsonb WHERE id=3",[JSON.stringify('legacy')]);
  await h.call('profile:merge-legacy-extra','PUT','/v2/profiles/3',{extra_data:{preferred_name:'Legacy name'}});
  await h.seed("UPDATE profiles SET extra_data=$1::jsonb WHERE id=3",[JSON.stringify(['retained'])]);
  await h.call('profile:regional-legacy-array','PUT','/v2/profiles/3/regional-assignment',{alumni_regional_assignment:['Bandung']});
  await h.call('profile:password-orphan','PUT','/v2/profiles/3',{password});
  await h.call('profile:delete','DELETE',`/v2/profiles/${profile.id}`);
  await h.call('profile:delete-missing','DELETE',`/v2/profiles/${profile.id}`);
}
