export async function clubCases(h){
  await h.call('club:invalid','POST','/v2/clubs',{});
  await h.call('club:create','POST','/v2/clubs',{name:'Fixture club',is_show:true,is_registration_open:true,logo:'ignored'});
  await h.call('club:open-without-form','PUT','/v2/clubs/1',{is_registration_open:true});
  await h.call('club:publish','PUT','/v2/clubs/1',{is_show:true,club_type:'CLUB_BAHASA',start_period:'2026-01-01',end_period:null});
  await h.call('club:list','GET','/v2/clubs?club_type=CLUB_BAHASA&visibility=published&registration=closed');
  await h.call('club:information','PUT','/v2/clubs/1/registration-info',{registration_info:' Fixture instructions '});
  const schema={fields:[{section_name:'questions',fields:[{key:'motivation',label:'Motivasi',required:true,type:'text'}]}]};
  await h.call('form:create','POST','/v2/custom-forms',{formName:'Fixture form',formSchema:schema,isActive:true});
  for(const path of ['/v2/custom-forms?search=Fixture&is_active=true','/v2/custom-forms/unattached','/v2/custom-forms/1','/v2/custom-forms/available-clubs','/v2/custom-forms/available-activities'])await h.call(path,'GET',path);
  await h.call('form:attach-club','PUT','/v2/custom-forms/1/attach-club',{clubId:1});
  await h.call('form:duplicate-attachment','PUT','/v2/custom-forms/1/attach-club',{clubId:1});
  await h.call('form:by-feature','GET','/v2/custom-forms/by-feature?feature_type=club_registration&feature_id=1');
  await h.call('form:feature-missing','GET','/v2/custom-forms/by-feature');
  await h.call('form:attachment-conflict','POST','/v2/custom-forms',{formName:'Conflict',featureType:'club_registration',featureId:1});
  await h.call('club:expired-open','PUT','/v2/clubs/1',{registration_end_date:'2000-01-01',is_registration_open:true});
  await h.call('club:open','PUT','/v2/clubs/1',{registration_end_date:null,is_registration_open:true});
  await h.call('form:rename','PUT','/v2/custom-forms/1',{formName:'Renamed form',formSchema:schema});
  await h.call('form:open-structure-change','PUT','/v2/custom-forms/1',{formSchema:{fields:[]}});
  await h.call('form:open-toggle','PUT','/v2/custom-forms/1/toggle-active',{});
  await h.call('form:open-delete','DELETE','/v2/custom-forms/1');
  await h.call('form:open-detach','PUT','/v2/custom-forms/1/detach-club',{});
  await h.call('club:show-form','GET','/v2/clubs/1');
  const logo=await h.upload('club:logo','/v2/clubs/1/logo');
  await h.inspectObject(logo.data.logo,{width:640,height:480});
  await h.upload('club:replace-logo','/v2/clubs/1/logo');
  const media=await h.upload('club:image','/v2/clubs/1/media/image',{media_type:'image'});
  const image=media.data.media.items[0].media_url;
  await h.call('club:youtube','POST','/v2/clubs/1/media/youtube',{media_url:'https://youtu.be/abc_DEF-123',media_type:'video',video_source:'youtube'});
  await h.call('club:youtube-duplicate','POST','/v2/clubs/1/media/youtube',{media_url:'https://www.youtube.com/watch?v=abc_DEF-123',media_type:'video',video_source:'youtube'});
  await h.call('club:youtube-invalid','POST','/v2/clubs/1/media/youtube',{media_url:'https://invalid.example/watch?v=abc_DEF-123',media_type:'video',video_source:'youtube'});
  await h.call('club:delete-image','PUT','/v2/clubs/1/delete-media',{media_url:image});
  await h.call('club:delete-missing-image','PUT','/v2/clubs/1/delete-media',{media_url:image});
  await h.call('club:close','PUT','/v2/clubs/1',{is_registration_open:false});
  await h.call('form:toggle-off','PUT','/v2/custom-forms/1/toggle-active',{});
  await h.call('form:toggle-on','PUT','/v2/custom-forms/1/toggle-active',{});
  await h.call('form:detach-club','PUT','/v2/custom-forms/1/detach-club',{});
  await h.call('form:activity','POST','/v2/activities',{name:'Form activity'});
  await h.call('form:attach-activity','PUT','/v2/custom-forms/1/attach-activity',{activityId:1});
  await h.call('form:duplicate-activity','PUT','/v2/custom-forms/1/attach-activity',{activityId:1});
  await h.call('form:detach-activity','PUT','/v2/custom-forms/1/detach-activity',{});
  await h.call('form:delete','DELETE','/v2/custom-forms/1');
  await h.call('form:missing','GET','/v2/custom-forms/1');
  await h.call('club:missing','GET','/v2/clubs/999999');
  await h.upload('club:missing-media-type','/v2/clubs/1/media/image');
}
