import assert from 'node:assert/strict';
import {mkdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {parseEnv} from 'node:util';
import {chromium,expect} from '@playwright/test';
import {root,workspace} from './env.mjs';
import {fixturePassword,legacyRequire} from './fixture-db.mjs';
import {borrowWorkspacePort,startAdminFrontend,startPublicFrontend} from './server-process.mjs';

export async function runScoringBrowser({member,participantToken,call,record,restorations,fixture}) {
  const directory=resolve(root,'.artifacts/scoring-browser');mkdirSync(directory,{recursive:true});
  let adminFE,publicFE,browser,admin;
  const errors=[];
  const evidence=async(page,name)=>{
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),{message:`${name}: horizontal overflow`}).toBe(true);
    await page.screenshot({path:resolve(directory,`${name}.png`),fullPage:true,animations:'disabled'});
  };
  try {
    const reuseAdmin=process.argv.includes('--reuse-admin-frontend');
    for(const port of reuseAdmin?[3000]:[3005,3000])restorations.push(await borrowWorkspacePort(port,process.argv.includes('--borrow-workspace')));
    if(reuseAdmin) {
      const source=await (await fetch('http://localhost:3005/src/api/axios.ts')).text();
      assert.match(source,/"VITE_PUBLIC_BE_ADMIN_API"\s*:\s*"http:\/\/localhost:3334\/v2"/,'Existing frontend must use the local fixture API');
    } else adminFE=await startAdminFrontend({...process.env,...parseEnv(readFileSync(resolve(workspace,'docs/.env.test.admin-fe'),'utf8'))});
    publicFE=await startPublicFrontend({...process.env,...parseEnv(readFileSync(resolve(workspace,'docs/.env.test.web-fe'),'utf8'))});
    const activity=await call('admin','browser activity','POST','/activities',{name:'Latihan Penilaian Peserta',activity_type:1});
    await call('admin','browser registration','POST',`/activities/${activity.id}/registrations`,{user_id:member.profile.id,questionnaire_answer:{}});
    await fixture.db.query("UPDATE activities SET is_published=true,description='Kegiatan pengembangan karakter',activity_start='2026-09-13' WHERE id=$1",[activity.id]);
    browser=await chromium.launch();
    const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'id-ID',timezoneId:'Asia/Jakarta'});
    admin=await context.newPage();admin.setDefaultTimeout(15000);admin.on('pageerror',error=>errors.push(error.message));
    await admin.goto('http://localhost:3005/login');
    await admin.getByLabel('Email',{exact:true}).fill('super@example.test');
    await admin.getByLabel('Password',{exact:true}).fill(fixturePassword);
    await admin.getByRole('button',{name:/\bLogin$/}).click();
    await expect(admin).toHaveURL(/\/dashboard$/);
    let releaseRubric;
    const rubricGate=new Promise(resolve=>{releaseRubric=resolve;});
    const rubricURL=`**/v2/activities/${activity.id}/scoring/rubric`;
    await admin.route(rubricURL,async route=>{await rubricGate;await route.continue();});
    await admin.goto(`http://localhost:3005/activity/${activity.id}?tab=scoring`);
    await expect(admin.getByRole('heading',{name:activity.name,exact:true})).toBeVisible();
    await expect(admin.locator('.ant-skeleton').first()).toBeVisible();
    await evidence(admin,'admin-loading-desktop');
    releaseRubric();
    await expect(admin.getByRole('heading',{name:'Penilaian kegiatan'})).toBeVisible();
    await admin.unroute(rubricURL);
    await admin.getByRole('button',{name:'Simpan rubrik',exact:true}).click();
    await expect(admin.getByText('Tambahkan setidaknya satu kelompok')).toBeVisible();
    await admin.getByRole('button',{name:'Tambah kelompok',exact:true}).click();
    await admin.getByLabel('Nama kelompok',{exact:true}).fill('Mujtahid');
    await admin.getByLabel('Aspek 1',{exact:true}).fill('Shiddiq');
    await admin.getByRole('button',{name:'Tambah aspek',exact:true}).click();
    await admin.getByLabel('Aspek 2',{exact:true}).fill('Amanah');
    await admin.getByLabel('Nilai maksimum',{exact:true}).nth(1).fill('50');
    await admin.getByLabel('Bobot',{exact:true}).nth(1).fill('3');
    await admin.getByRole('button',{name:'Tambah indeks',exact:true}).click();
    await admin.getByLabel('Indeks',{exact:true}).fill('B');
    await admin.getByRole('button',{name:'Tambah indeks',exact:true}).click();
    await admin.getByLabel('Indeks',{exact:true}).nth(1).fill('A');
    await admin.getByLabel('Nilai minimum (0–100)',{exact:true}).nth(1).fill('80');
    await admin.getByLabel('Catatan untuk semua peserta',{exact:true}).fill('Terus belajar dan menjaga amanah.');
    await admin.getByRole('button',{name:'Tambah kelompok',exact:true}).click();
    await admin.getByRole('button',{name:'Hapus kelompok',exact:true}).last().click();
    await admin.getByRole('button',{name:'Tambah aspek',exact:true}).click();
    await admin.getByRole('button',{name:'Hapus aspek 3',exact:true}).click();
    await admin.getByRole('button',{name:'Naikkan aspek 2',exact:true}).click();
    await admin.getByRole('button',{name:'Naikkan aspek 2',exact:true}).click();
    await admin.getByRole('button',{name:'Tambah indeks',exact:true}).click();
    await admin.getByRole('button',{name:'Hapus indeks',exact:true}).last().click();
    await evidence(admin,'admin-rubric-desktop');
    await admin.setViewportSize({width:390,height:844});await evidence(admin,'admin-rubric-mobile');
    await admin.getByRole('button',{name:'Simpan rubrik',exact:true}).click();
    await expect(admin.getByText('Rubrik tersimpan.',{exact:true})).toBeVisible();
    await admin.getByRole('tab',{name:'Nilai peserta',exact:true}).click();
    await admin.getByRole('button',{name:'Isi nilai',exact:true}).click();
    let dialog=admin.getByRole('dialog',{name:'Penilaian: Peserta Penilaian'});
    await dialog.getByLabel('Shiddiq (maks. 100, bobot 1)',{exact:true}).fill('100');
    await dialog.getByLabel('Amanah (maks. 50, bobot 3)',{exact:true}).fill('35');
    await dialog.getByLabel('Catatan peserta',{exact:true}).fill('Catatan peserta pertama.');
    await evidence(admin,'admin-entry-mobile');
    await dialog.getByRole('button',{name:'Simpan draf',exact:true}).click();
    await expect(dialog).not.toBeVisible();
    await expect(admin.getByText('77,5',{exact:true})).toBeVisible();
    await admin.getByRole('tab',{name:'Rubrik penilaian',exact:true}).click();
    await expect(admin.getByText('Rubrik terkunci karena nilai sudah diisi')).toBeVisible();
    await admin.getByRole('tab',{name:'Nilai peserta',exact:true}).click();
    const download=admin.waitForEvent('download');
    await admin.getByRole('button',{name:'Unduh templat Excel',exact:true}).click();
    const file=await download;const filePath=resolve(directory,'template.xlsx');await file.saveAs(filePath);
    const book=new (legacyRequire('exceljs').Workbook)();await book.xlsx.readFile(filePath);book.getWorksheet('Scores').getCell('F3').value=40;
    await admin.locator('input[type="file"]').setInputFiles({name:'scores.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(await book.xlsx.writeBuffer())});
    const preview=admin.getByRole('dialog',{name:'Tinjau impor nilai'});
    await expect(preview.getByRole('button',{name:'Simpan 1 draf',exact:true})).toBeEnabled();
    await evidence(admin,'admin-import-mobile');
    await preview.getByRole('button',{name:'Simpan 1 draf',exact:true}).click();await expect(preview).not.toBeVisible();
    await expect(admin.getByText('85',{exact:true})).toBeVisible();
    await admin.getByRole('checkbox').last().check();
    await admin.getByRole('button',{name:'Terbitkan pilihan (1)',exact:true}).click();
    await admin.getByRole('dialog',{name:'Terbitkan hasil penilaian?'}).getByRole('button',{name:'Terbitkan',exact:true}).click();
    await expect(admin.getByText('Hasil penilaian diterbitkan.',{exact:true})).toBeVisible();
    const publicContext=await browser.newContext({viewport:{width:390,height:844},locale:'id-ID',timezoneId:'Asia/Jakarta'});
    await publicContext.addCookies([{name:'session',value:participantToken,domain:'localhost',path:'/'},{name:'name',value:'Peserta Penilaian',domain:'localhost',path:'/'}]);
    const page=await publicContext.newPage();page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://localhost:3000/profile/activity/${activity.slug}`);
    await expect(page.getByRole('heading',{name:'Hasil penilaian',exact:true})).toBeVisible();
    await expect(page.getByText('85 · A',{exact:true})).toBeVisible();
    await evidence(page,'participant-result-mobile');
    await page.setViewportSize({width:1440,height:1000});await evidence(page,'participant-result-desktop');
    await admin.setViewportSize({width:1440,height:1000});await evidence(admin,'admin-scores-desktop');
    await admin.getByRole('button',{name:'Isi nilai',exact:true}).click();
    dialog=admin.getByRole('dialog',{name:'Penilaian: Peserta Penilaian'});
    await dialog.getByLabel('Catatan peserta',{exact:true}).fill('Catatan revisi.');
    await dialog.getByRole('button',{name:'Tutup',exact:true}).click();
    await admin.getByRole('dialog',{name:'Perubahan belum disimpan'}).getByRole('button',{name:'Lanjutkan mengisi',exact:true}).click();
    await dialog.getByRole('button',{name:'Simpan draf',exact:true}).click();
    await expect(dialog).not.toBeVisible();
    await page.reload();await expect(page.getByText('Catatan peserta pertama.',{exact:true})).toBeVisible();await expect(page.getByText('Catatan revisi.',{exact:true})).toHaveCount(0);
    await admin.getByRole('button',{name:'Terbitkan ulang',exact:true}).click();
    await admin.getByRole('dialog',{name:'Terbitkan hasil penilaian?'}).getByRole('button',{name:'Terbitkan',exact:true}).click();
    await expect(admin.getByRole('dialog')).toHaveCount(0);
    await page.reload();await expect(page.getByText('Catatan revisi.',{exact:true})).toBeVisible();
    for(const label of ['Ekspor draf','Ekspor hasil terbit']) {
      const event=admin.waitForEvent('download');await admin.getByRole('button',{name:label,exact:true}).click();await (await event).saveAs(resolve(directory,`${label.replaceAll(' ','-')}.xlsx`));
    }
    await admin.getByRole('button',{name:'Tarik hasil',exact:true}).click();
    await admin.getByRole('dialog',{name:'Tarik hasil penilaian?'}).getByRole('button',{name:'Tarik hasil',exact:true}).click();await expect(admin.getByRole('dialog')).toHaveCount(0);
    await page.reload();await expect(page.getByRole('heading',{name:'Hasil penilaian',exact:true})).toHaveCount(0);
    await admin.getByLabel('Cari peserta penilaian',{exact:true}).fill('Tidak ditemukan');await admin.getByLabel('Cari peserta penilaian',{exact:true}).press('Enter');
    await expect(admin.getByText('Tidak ada peserta yang sesuai')).toBeVisible();
    await admin.getByLabel('Cari peserta penilaian',{exact:true}).fill('');await admin.getByLabel('Cari peserta penilaian',{exact:true}).press('Enter');
    const listURL=`**/v2/activities/${activity.id}/scoring?*`;
    await admin.route(listURL,route=>route.fulfill({status:503,contentType:'application/json',body:'{"message":"SCORING_TEST_FAILURE"}'}));
    await admin.getByLabel('Cari peserta penilaian',{exact:true}).fill('Peserta');await admin.getByLabel('Cari peserta penilaian',{exact:true}).press('Enter');
    await expect(admin.getByText('Pembaruan data gagal dimuat',{exact:true})).toBeVisible();
    await evidence(admin,'admin-retry-desktop');
    await admin.unroute(listURL);await admin.getByRole('button',{name:'Coba lagi',exact:true}).click();
    await expect(admin.getByText('Pembaruan data gagal dimuat',{exact:true})).toHaveCount(0);
    await admin.getByRole('combobox',{name:'Status penilaian'}).focus();await admin.keyboard.press('ArrowDown');await admin.keyboard.press('Enter');await admin.keyboard.press('Escape');
    await admin.setViewportSize({width:390,height:844});await evidence(admin,'admin-scores-mobile');
    await admin.getByRole('tab',{name:'Peserta',exact:true}).click();await expect(admin.getByText('Total Peserta Terdaftar',{exact:true})).toBeVisible();await evidence(admin,'admin-related-participants-mobile');
    await admin.setViewportSize({width:1440,height:1000});await evidence(admin,'admin-related-participants-desktop');
    assert.deepEqual(errors,[],'Browser runtime errors');
    record.checks.push({label:'Browser: rubric validation/setup, draft entry, Excel preview/commit/export, bulk publication, private corrections, republish, withdrawal, filters, keyboard navigation, and desktop/mobile layouts',screenshots:directory});
  } catch(error) {if(admin)await admin.screenshot({path:resolve(directory,'failure.png'),fullPage:true});throw error;}
  finally {await browser?.close();await publicFE?.stop();await adminFE?.stop();}
}
